VERSION 0.7
FROM golang:1.22-alpine
WORKDIR /freighter/integration

deps:
    COPY ../../alamos/go+source/* /alamos/go
    COPY ../../x/go+source/* /x/go
    COPY ../go+source/* /freighter/go
    COPY go.mod go.sum .
    RUN go mod download

build:
    FROM +deps
    COPY . .
    RUN go build -o build/freighter/integration main.go
    SAVE ARTIFACT build/freighter/integration /freighter/integration AS LOCAL build/freighter/integration

docker:
    COPY +build/freighter/integration .
    ENTRYPOINT ["/freighter/integration/integration"]
    SAVE IMAGE --push ghcr.io/synnaxlabs/freighter-go-integration:latest
