// Copyright 2026 Synnax Labs, Inc.
//
// Use of this software is governed by the Business Source License included in the file
// licenses/BSL.txt.
//
// As of the Change Date specified in that file, in accordance with the Business Source
// License, use of this software will be governed by the Apache License, Version 2.0,
// included in the file licenses/APL.txt.

// Code generated by oracle. DO NOT EDIT.

package config

import "github.com/synnaxlabs/synnax/pkg/service/task/config/versions"

// Keyed is the base for every stored task configuration record.
type Keyed = versions.Keyed

// BaseStart carries the configuration fields shared by every task.
type BaseStart = versions.BaseStart

// BasePersist carries the configuration fields shared by tasks that write telemetry.
type BasePersist = versions.BasePersist

// BaseRead carries the configuration fields shared by hardware acquisition tasks.
type BaseRead = versions.BaseRead

// BaseWrite carries the configuration fields shared by hardware control tasks.
type BaseWrite = versions.BaseWrite

// BaseScan carries the fields shared by every scan task configuration.
type BaseScan = versions.BaseScan
