version: "v2.12.2"
plugins:
  - module: "github.com/synnaxlabs/x"
    import: "github.com/synnaxlabs/x/analyzers/mustsucceedlint"
    path: .
  - module: "github.com/synnaxlabs/x"
    import: "github.com/synnaxlabs/x/analyzers/setlint"
    path: .
  - module: "github.com/synnaxlabs/x"
    import: "github.com/synnaxlabs/x/analyzers/leaklint"
    path: .
