version: "v2.12.2"
plugins:
  - module: "github.com/synnaxlabs/x"
    import: "github.com/synnaxlabs/x/analyzers/must"
    path: .
  - module: "github.com/synnaxlabs/x"
    import: "github.com/synnaxlabs/x/analyzers/set"
    path: .
  - module: "github.com/synnaxlabs/x"
    import: "github.com/synnaxlabs/x/analyzers/goroutineleak"
    path: .
