load("@rules_cc//cc:cc_library.bzl", "cc_library")
load("@rules_cc//cc:cc_shared_library.bzl", "cc_shared_library")

cc_library(
    name = "clib",
    srcs = [
        "channel/channel.cpp",
        "framer/framer.cpp",
        "synnax.cpp",
    ],
    hdrs = [
        "channel/channel.h",
        "export.h",
        "framer/framer.h",
        "internal.h",
        "synnax.h",
        "types.h",
    ],
    local_defines = ["SYNNAX_BUILDING_DLL=1"],
    visibility = ["//visibility:public"],
    deps = [
        "//client/cpp:synnax",
        "//client/cpp/errors",
    ],
    alwayslink = True,
)

cc_shared_library(
    name = "synnax_clib",
    visibility = ["//visibility:public"],
    win_def_file = "synnax.def",
    deps = [":clib"],
)
