// Code generated by Oracle. DO NOT EDIT.

import { record } from "@synnaxlabs/x";
import { z } from "zod";

import { ontology } from "@/ontology";

export const keyZ = z.uuid();
export type Key = z.infer<typeof keyZ>;

export const viewZ = z.object({
  key: keyZ,
  name: z.string(),
  type: z.string(),
  query: record.unknownZ.or(z.string().transform((s) => JSON.parse(s))),
});
export type View = z.infer<typeof viewZ>;

export const newZ = z.object({
  key: keyZ.optional(),
  name: z.string(),
  type: z.string(),
  query: record.unknownZ.or(z.string().transform((s) => JSON.parse(s))),
});
export type New = z.infer<typeof newZ>;

export const ONTOLOGY_TYPE = "view";
export const ontologyID = ontology.createIDFactory<Key>("view");
export const TYPE_ONTOLOGY_ID = ontologyID("");
