package api

// Code generated by github.com/tinylib/msgp DO NOT EDIT.

import (
	"github.com/synnaxlabs/synnax/pkg/distribution/framer"
	"github.com/tinylib/msgp/msgp"
)

// DecodeMsg implements msgp.Decodable
func (z *FrameDeleteRequest) DecodeMsg(dc *msgp.Reader) (err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, err = dc.ReadMapHeader()
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, err = dc.ReadMapKeyPtr()
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "keys":
			err = z.Keys.DecodeMsg(dc)
			if err != nil {
				err = msgp.WrapError(err, "Keys")
				return
			}
		case "bounds":
			err = z.Bounds.DecodeMsg(dc)
			if err != nil {
				err = msgp.WrapError(err, "Bounds")
				return
			}
		case "names":
			var zb0002 uint32
			zb0002, err = dc.ReadArrayHeader()
			if err != nil {
				err = msgp.WrapError(err, "Names")
				return
			}
			if cap(z.Names) >= int(zb0002) {
				z.Names = (z.Names)[:zb0002]
			} else {
				z.Names = make([]string, zb0002)
			}
			for za0001 := range z.Names {
				z.Names[za0001], err = dc.ReadString()
				if err != nil {
					err = msgp.WrapError(err, "Names", za0001)
					return
				}
			}
		default:
			err = dc.Skip()
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	return
}

// EncodeMsg implements msgp.Encodable
func (z *FrameDeleteRequest) EncodeMsg(en *msgp.Writer) (err error) {
	// map header, size 3
	// write "keys"
	err = en.Append(0x83, 0xa4, 0x6b, 0x65, 0x79, 0x73)
	if err != nil {
		return
	}
	err = z.Keys.EncodeMsg(en)
	if err != nil {
		err = msgp.WrapError(err, "Keys")
		return
	}
	// write "bounds"
	err = en.Append(0xa6, 0x62, 0x6f, 0x75, 0x6e, 0x64, 0x73)
	if err != nil {
		return
	}
	err = z.Bounds.EncodeMsg(en)
	if err != nil {
		err = msgp.WrapError(err, "Bounds")
		return
	}
	// write "names"
	err = en.Append(0xa5, 0x6e, 0x61, 0x6d, 0x65, 0x73)
	if err != nil {
		return
	}
	err = en.WriteArrayHeader(uint32(len(z.Names)))
	if err != nil {
		err = msgp.WrapError(err, "Names")
		return
	}
	for za0001 := range z.Names {
		err = en.WriteString(z.Names[za0001])
		if err != nil {
			err = msgp.WrapError(err, "Names", za0001)
			return
		}
	}
	return
}

// MarshalMsg implements msgp.Marshaler
func (z *FrameDeleteRequest) MarshalMsg(b []byte) (o []byte, err error) {
	o = msgp.Require(b, z.Msgsize())
	// map header, size 3
	// string "keys"
	o = append(o, 0x83, 0xa4, 0x6b, 0x65, 0x79, 0x73)
	o, err = z.Keys.MarshalMsg(o)
	if err != nil {
		err = msgp.WrapError(err, "Keys")
		return
	}
	// string "bounds"
	o = append(o, 0xa6, 0x62, 0x6f, 0x75, 0x6e, 0x64, 0x73)
	o, err = z.Bounds.MarshalMsg(o)
	if err != nil {
		err = msgp.WrapError(err, "Bounds")
		return
	}
	// string "names"
	o = append(o, 0xa5, 0x6e, 0x61, 0x6d, 0x65, 0x73)
	o = msgp.AppendArrayHeader(o, uint32(len(z.Names)))
	for za0001 := range z.Names {
		o = msgp.AppendString(o, z.Names[za0001])
	}
	return
}

// UnmarshalMsg implements msgp.Unmarshaler
func (z *FrameDeleteRequest) UnmarshalMsg(bts []byte) (o []byte, err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, bts, err = msgp.ReadMapHeaderBytes(bts)
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, bts, err = msgp.ReadMapKeyZC(bts)
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "keys":
			bts, err = z.Keys.UnmarshalMsg(bts)
			if err != nil {
				err = msgp.WrapError(err, "Keys")
				return
			}
		case "bounds":
			bts, err = z.Bounds.UnmarshalMsg(bts)
			if err != nil {
				err = msgp.WrapError(err, "Bounds")
				return
			}
		case "names":
			var zb0002 uint32
			zb0002, bts, err = msgp.ReadArrayHeaderBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Names")
				return
			}
			if cap(z.Names) >= int(zb0002) {
				z.Names = (z.Names)[:zb0002]
			} else {
				z.Names = make([]string, zb0002)
			}
			for za0001 := range z.Names {
				z.Names[za0001], bts, err = msgp.ReadStringBytes(bts)
				if err != nil {
					err = msgp.WrapError(err, "Names", za0001)
					return
				}
			}
		default:
			bts, err = msgp.Skip(bts)
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	o = bts
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z *FrameDeleteRequest) Msgsize() (s int) {
	s = 1 + 5 + z.Keys.Msgsize() + 7 + z.Bounds.Msgsize() + 6 + msgp.ArrayHeaderSize
	for za0001 := range z.Names {
		s += msgp.StringPrefixSize + len(z.Names[za0001])
	}
	return
}

// DecodeMsg implements msgp.Decodable
func (z *FrameService) DecodeMsg(dc *msgp.Reader) (err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, err = dc.ReadMapHeader()
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, err = dc.ReadMapKeyPtr()
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "Instrumentation":
			err = z.Instrumentation.DecodeMsg(dc)
			if err != nil {
				err = msgp.WrapError(err, "Instrumentation")
				return
			}
		case "Internal":
			if dc.IsNil() {
				err = dc.ReadNil()
				if err != nil {
					err = msgp.WrapError(err, "Internal")
					return
				}
				z.Internal = nil
			} else {
				if z.Internal == nil {
					z.Internal = new(framer.Service)
				}
				err = z.Internal.DecodeMsg(dc)
				if err != nil {
					err = msgp.WrapError(err, "Internal")
					return
				}
			}
		default:
			err = dc.Skip()
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	return
}

// EncodeMsg implements msgp.Encodable
func (z *FrameService) EncodeMsg(en *msgp.Writer) (err error) {
	// map header, size 2
	// write "Instrumentation"
	err = en.Append(0x82, 0xaf, 0x49, 0x6e, 0x73, 0x74, 0x72, 0x75, 0x6d, 0x65, 0x6e, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e)
	if err != nil {
		return
	}
	err = z.Instrumentation.EncodeMsg(en)
	if err != nil {
		err = msgp.WrapError(err, "Instrumentation")
		return
	}
	// write "Internal"
	err = en.Append(0xa8, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c)
	if err != nil {
		return
	}
	if z.Internal == nil {
		err = en.WriteNil()
		if err != nil {
			return
		}
	} else {
		err = z.Internal.EncodeMsg(en)
		if err != nil {
			err = msgp.WrapError(err, "Internal")
			return
		}
	}
	return
}

// MarshalMsg implements msgp.Marshaler
func (z *FrameService) MarshalMsg(b []byte) (o []byte, err error) {
	o = msgp.Require(b, z.Msgsize())
	// map header, size 2
	// string "Instrumentation"
	o = append(o, 0x82, 0xaf, 0x49, 0x6e, 0x73, 0x74, 0x72, 0x75, 0x6d, 0x65, 0x6e, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e)
	o, err = z.Instrumentation.MarshalMsg(o)
	if err != nil {
		err = msgp.WrapError(err, "Instrumentation")
		return
	}
	// string "Internal"
	o = append(o, 0xa8, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c)
	if z.Internal == nil {
		o = msgp.AppendNil(o)
	} else {
		o, err = z.Internal.MarshalMsg(o)
		if err != nil {
			err = msgp.WrapError(err, "Internal")
			return
		}
	}
	return
}

// UnmarshalMsg implements msgp.Unmarshaler
func (z *FrameService) UnmarshalMsg(bts []byte) (o []byte, err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, bts, err = msgp.ReadMapHeaderBytes(bts)
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, bts, err = msgp.ReadMapKeyZC(bts)
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "Instrumentation":
			bts, err = z.Instrumentation.UnmarshalMsg(bts)
			if err != nil {
				err = msgp.WrapError(err, "Instrumentation")
				return
			}
		case "Internal":
			if msgp.IsNil(bts) {
				bts, err = msgp.ReadNilBytes(bts)
				if err != nil {
					return
				}
				z.Internal = nil
			} else {
				if z.Internal == nil {
					z.Internal = new(framer.Service)
				}
				bts, err = z.Internal.UnmarshalMsg(bts)
				if err != nil {
					err = msgp.WrapError(err, "Internal")
					return
				}
			}
		default:
			bts, err = msgp.Skip(bts)
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	o = bts
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z *FrameService) Msgsize() (s int) {
	s = 1 + 16 + z.Instrumentation.Msgsize() + 9
	if z.Internal == nil {
		s += msgp.NilSize
	} else {
		s += z.Internal.Msgsize()
	}
	return
}

// DecodeMsg implements msgp.Decodable
func (z *FrameWriterConfig) DecodeMsg(dc *msgp.Reader) (err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, err = dc.ReadMapHeader()
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, err = dc.ReadMapKeyPtr()
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "authorities":
			var zb0002 uint32
			zb0002, err = dc.ReadArrayHeader()
			if err != nil {
				err = msgp.WrapError(err, "Authorities")
				return
			}
			if cap(z.Authorities) >= int(zb0002) {
				z.Authorities = (z.Authorities)[:zb0002]
			} else {
				z.Authorities = make([]uint32, zb0002)
			}
			for za0001 := range z.Authorities {
				z.Authorities[za0001], err = dc.ReadUint32()
				if err != nil {
					err = msgp.WrapError(err, "Authorities", za0001)
					return
				}
			}
		case "control_subject":
			err = z.ControlSubject.DecodeMsg(dc)
			if err != nil {
				err = msgp.WrapError(err, "ControlSubject")
				return
			}
		case "start":
			err = z.Start.DecodeMsg(dc)
			if err != nil {
				err = msgp.WrapError(err, "Start")
				return
			}
		case "keys":
			err = z.Keys.DecodeMsg(dc)
			if err != nil {
				err = msgp.WrapError(err, "Keys")
				return
			}
		case "mode":
			err = z.Mode.DecodeMsg(dc)
			if err != nil {
				err = msgp.WrapError(err, "Mode")
				return
			}
		case "err_on_unauthorized":
			z.ErrOnUnauthorized, err = dc.ReadBool()
			if err != nil {
				err = msgp.WrapError(err, "ErrOnUnauthorized")
				return
			}
		case "enable_auto_commit":
			z.EnableAutoCommit, err = dc.ReadBool()
			if err != nil {
				err = msgp.WrapError(err, "EnableAutoCommit")
				return
			}
		case "auto_index_persist_interval":
			err = z.AutoIndexPersistInterval.DecodeMsg(dc)
			if err != nil {
				err = msgp.WrapError(err, "AutoIndexPersistInterval")
				return
			}
		default:
			err = dc.Skip()
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	return
}

// EncodeMsg implements msgp.Encodable
func (z *FrameWriterConfig) EncodeMsg(en *msgp.Writer) (err error) {
	// map header, size 8
	// write "authorities"
	err = en.Append(0x88, 0xab, 0x61, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x69, 0x74, 0x69, 0x65, 0x73)
	if err != nil {
		return
	}
	err = en.WriteArrayHeader(uint32(len(z.Authorities)))
	if err != nil {
		err = msgp.WrapError(err, "Authorities")
		return
	}
	for za0001 := range z.Authorities {
		err = en.WriteUint32(z.Authorities[za0001])
		if err != nil {
			err = msgp.WrapError(err, "Authorities", za0001)
			return
		}
	}
	// write "control_subject"
	err = en.Append(0xaf, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x5f, 0x73, 0x75, 0x62, 0x6a, 0x65, 0x63, 0x74)
	if err != nil {
		return
	}
	err = z.ControlSubject.EncodeMsg(en)
	if err != nil {
		err = msgp.WrapError(err, "ControlSubject")
		return
	}
	// write "start"
	err = en.Append(0xa5, 0x73, 0x74, 0x61, 0x72, 0x74)
	if err != nil {
		return
	}
	err = z.Start.EncodeMsg(en)
	if err != nil {
		err = msgp.WrapError(err, "Start")
		return
	}
	// write "keys"
	err = en.Append(0xa4, 0x6b, 0x65, 0x79, 0x73)
	if err != nil {
		return
	}
	err = z.Keys.EncodeMsg(en)
	if err != nil {
		err = msgp.WrapError(err, "Keys")
		return
	}
	// write "mode"
	err = en.Append(0xa4, 0x6d, 0x6f, 0x64, 0x65)
	if err != nil {
		return
	}
	err = z.Mode.EncodeMsg(en)
	if err != nil {
		err = msgp.WrapError(err, "Mode")
		return
	}
	// write "err_on_unauthorized"
	err = en.Append(0xb3, 0x65, 0x72, 0x72, 0x5f, 0x6f, 0x6e, 0x5f, 0x75, 0x6e, 0x61, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x69, 0x7a, 0x65, 0x64)
	if err != nil {
		return
	}
	err = en.WriteBool(z.ErrOnUnauthorized)
	if err != nil {
		err = msgp.WrapError(err, "ErrOnUnauthorized")
		return
	}
	// write "enable_auto_commit"
	err = en.Append(0xb2, 0x65, 0x6e, 0x61, 0x62, 0x6c, 0x65, 0x5f, 0x61, 0x75, 0x74, 0x6f, 0x5f, 0x63, 0x6f, 0x6d, 0x6d, 0x69, 0x74)
	if err != nil {
		return
	}
	err = en.WriteBool(z.EnableAutoCommit)
	if err != nil {
		err = msgp.WrapError(err, "EnableAutoCommit")
		return
	}
	// write "auto_index_persist_interval"
	err = en.Append(0xbb, 0x61, 0x75, 0x74, 0x6f, 0x5f, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x5f, 0x70, 0x65, 0x72, 0x73, 0x69, 0x73, 0x74, 0x5f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x76, 0x61, 0x6c)
	if err != nil {
		return
	}
	err = z.AutoIndexPersistInterval.EncodeMsg(en)
	if err != nil {
		err = msgp.WrapError(err, "AutoIndexPersistInterval")
		return
	}
	return
}

// MarshalMsg implements msgp.Marshaler
func (z *FrameWriterConfig) MarshalMsg(b []byte) (o []byte, err error) {
	o = msgp.Require(b, z.Msgsize())
	// map header, size 8
	// string "authorities"
	o = append(o, 0x88, 0xab, 0x61, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x69, 0x74, 0x69, 0x65, 0x73)
	o = msgp.AppendArrayHeader(o, uint32(len(z.Authorities)))
	for za0001 := range z.Authorities {
		o = msgp.AppendUint32(o, z.Authorities[za0001])
	}
	// string "control_subject"
	o = append(o, 0xaf, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x5f, 0x73, 0x75, 0x62, 0x6a, 0x65, 0x63, 0x74)
	o, err = z.ControlSubject.MarshalMsg(o)
	if err != nil {
		err = msgp.WrapError(err, "ControlSubject")
		return
	}
	// string "start"
	o = append(o, 0xa5, 0x73, 0x74, 0x61, 0x72, 0x74)
	o, err = z.Start.MarshalMsg(o)
	if err != nil {
		err = msgp.WrapError(err, "Start")
		return
	}
	// string "keys"
	o = append(o, 0xa4, 0x6b, 0x65, 0x79, 0x73)
	o, err = z.Keys.MarshalMsg(o)
	if err != nil {
		err = msgp.WrapError(err, "Keys")
		return
	}
	// string "mode"
	o = append(o, 0xa4, 0x6d, 0x6f, 0x64, 0x65)
	o, err = z.Mode.MarshalMsg(o)
	if err != nil {
		err = msgp.WrapError(err, "Mode")
		return
	}
	// string "err_on_unauthorized"
	o = append(o, 0xb3, 0x65, 0x72, 0x72, 0x5f, 0x6f, 0x6e, 0x5f, 0x75, 0x6e, 0x61, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x69, 0x7a, 0x65, 0x64)
	o = msgp.AppendBool(o, z.ErrOnUnauthorized)
	// string "enable_auto_commit"
	o = append(o, 0xb2, 0x65, 0x6e, 0x61, 0x62, 0x6c, 0x65, 0x5f, 0x61, 0x75, 0x74, 0x6f, 0x5f, 0x63, 0x6f, 0x6d, 0x6d, 0x69, 0x74)
	o = msgp.AppendBool(o, z.EnableAutoCommit)
	// string "auto_index_persist_interval"
	o = append(o, 0xbb, 0x61, 0x75, 0x74, 0x6f, 0x5f, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x5f, 0x70, 0x65, 0x72, 0x73, 0x69, 0x73, 0x74, 0x5f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x76, 0x61, 0x6c)
	o, err = z.AutoIndexPersistInterval.MarshalMsg(o)
	if err != nil {
		err = msgp.WrapError(err, "AutoIndexPersistInterval")
		return
	}
	return
}

// UnmarshalMsg implements msgp.Unmarshaler
func (z *FrameWriterConfig) UnmarshalMsg(bts []byte) (o []byte, err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, bts, err = msgp.ReadMapHeaderBytes(bts)
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, bts, err = msgp.ReadMapKeyZC(bts)
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "authorities":
			var zb0002 uint32
			zb0002, bts, err = msgp.ReadArrayHeaderBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Authorities")
				return
			}
			if cap(z.Authorities) >= int(zb0002) {
				z.Authorities = (z.Authorities)[:zb0002]
			} else {
				z.Authorities = make([]uint32, zb0002)
			}
			for za0001 := range z.Authorities {
				z.Authorities[za0001], bts, err = msgp.ReadUint32Bytes(bts)
				if err != nil {
					err = msgp.WrapError(err, "Authorities", za0001)
					return
				}
			}
		case "control_subject":
			bts, err = z.ControlSubject.UnmarshalMsg(bts)
			if err != nil {
				err = msgp.WrapError(err, "ControlSubject")
				return
			}
		case "start":
			bts, err = z.Start.UnmarshalMsg(bts)
			if err != nil {
				err = msgp.WrapError(err, "Start")
				return
			}
		case "keys":
			bts, err = z.Keys.UnmarshalMsg(bts)
			if err != nil {
				err = msgp.WrapError(err, "Keys")
				return
			}
		case "mode":
			bts, err = z.Mode.UnmarshalMsg(bts)
			if err != nil {
				err = msgp.WrapError(err, "Mode")
				return
			}
		case "err_on_unauthorized":
			z.ErrOnUnauthorized, bts, err = msgp.ReadBoolBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "ErrOnUnauthorized")
				return
			}
		case "enable_auto_commit":
			z.EnableAutoCommit, bts, err = msgp.ReadBoolBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "EnableAutoCommit")
				return
			}
		case "auto_index_persist_interval":
			bts, err = z.AutoIndexPersistInterval.UnmarshalMsg(bts)
			if err != nil {
				err = msgp.WrapError(err, "AutoIndexPersistInterval")
				return
			}
		default:
			bts, err = msgp.Skip(bts)
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	o = bts
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z *FrameWriterConfig) Msgsize() (s int) {
	s = 1 + 12 + msgp.ArrayHeaderSize + (len(z.Authorities) * (msgp.Uint32Size)) + 16 + z.ControlSubject.Msgsize() + 6 + z.Start.Msgsize() + 5 + z.Keys.Msgsize() + 5 + z.Mode.Msgsize() + 20 + msgp.BoolSize + 19 + msgp.BoolSize + 28 + z.AutoIndexPersistInterval.Msgsize()
	return
}

// DecodeMsg implements msgp.Decodable
func (z *FrameWriterRequest) DecodeMsg(dc *msgp.Reader) (err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, err = dc.ReadMapHeader()
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, err = dc.ReadMapKeyPtr()
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "config":
			err = z.Config.DecodeMsg(dc)
			if err != nil {
				err = msgp.WrapError(err, "Config")
				return
			}
		case "command":
			err = z.Command.DecodeMsg(dc)
			if err != nil {
				err = msgp.WrapError(err, "Command")
				return
			}
		case "frame":
			err = z.Frame.DecodeMsg(dc)
			if err != nil {
				err = msgp.WrapError(err, "Frame")
				return
			}
		default:
			err = dc.Skip()
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	return
}

// EncodeMsg implements msgp.Encodable
func (z *FrameWriterRequest) EncodeMsg(en *msgp.Writer) (err error) {
	// map header, size 3
	// write "config"
	err = en.Append(0x83, 0xa6, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67)
	if err != nil {
		return
	}
	err = z.Config.EncodeMsg(en)
	if err != nil {
		err = msgp.WrapError(err, "Config")
		return
	}
	// write "command"
	err = en.Append(0xa7, 0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64)
	if err != nil {
		return
	}
	err = z.Command.EncodeMsg(en)
	if err != nil {
		err = msgp.WrapError(err, "Command")
		return
	}
	// write "frame"
	err = en.Append(0xa5, 0x66, 0x72, 0x61, 0x6d, 0x65)
	if err != nil {
		return
	}
	err = z.Frame.EncodeMsg(en)
	if err != nil {
		err = msgp.WrapError(err, "Frame")
		return
	}
	return
}

// MarshalMsg implements msgp.Marshaler
func (z *FrameWriterRequest) MarshalMsg(b []byte) (o []byte, err error) {
	o = msgp.Require(b, z.Msgsize())
	// map header, size 3
	// string "config"
	o = append(o, 0x83, 0xa6, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67)
	o, err = z.Config.MarshalMsg(o)
	if err != nil {
		err = msgp.WrapError(err, "Config")
		return
	}
	// string "command"
	o = append(o, 0xa7, 0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64)
	o, err = z.Command.MarshalMsg(o)
	if err != nil {
		err = msgp.WrapError(err, "Command")
		return
	}
	// string "frame"
	o = append(o, 0xa5, 0x66, 0x72, 0x61, 0x6d, 0x65)
	o, err = z.Frame.MarshalMsg(o)
	if err != nil {
		err = msgp.WrapError(err, "Frame")
		return
	}
	return
}

// UnmarshalMsg implements msgp.Unmarshaler
func (z *FrameWriterRequest) UnmarshalMsg(bts []byte) (o []byte, err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, bts, err = msgp.ReadMapHeaderBytes(bts)
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, bts, err = msgp.ReadMapKeyZC(bts)
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "config":
			bts, err = z.Config.UnmarshalMsg(bts)
			if err != nil {
				err = msgp.WrapError(err, "Config")
				return
			}
		case "command":
			bts, err = z.Command.UnmarshalMsg(bts)
			if err != nil {
				err = msgp.WrapError(err, "Command")
				return
			}
		case "frame":
			bts, err = z.Frame.UnmarshalMsg(bts)
			if err != nil {
				err = msgp.WrapError(err, "Frame")
				return
			}
		default:
			bts, err = msgp.Skip(bts)
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	o = bts
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z *FrameWriterRequest) Msgsize() (s int) {
	s = 1 + 7 + z.Config.Msgsize() + 8 + z.Command.Msgsize() + 6 + z.Frame.Msgsize()
	return
}
