// Copyright 2026 Synnax Labs, Inc.
//
// Use of this software is governed by the Business Source License included in the file
// licenses/BSL.txt.
//
// As of the Change Date specified in that file, in accordance with the Business Source
// License, use of this software will be governed by the Apache License, Version 2.0,
// included in the file licenses/APL.txt.

// Code generated by oracle. DO NOT EDIT.

package pb

import (
	"context"
	"github.com/samber/lo"
	irpb "github.com/synnaxlabs/arc/ir/pb"
	"github.com/synnaxlabs/arc/program"
)

// ProgramToPB converts Program to Program.
func ProgramToPB(ctx context.Context, r program.Program) (*Program, error) {
	functionsVal, err := irpb.FunctionsToPB(ctx, r.Functions)
	if err != nil {
		return nil, err
	}
	nodesVal, err := irpb.NodesToPB(ctx, r.Nodes)
	if err != nil {
		return nil, err
	}
	edgesVal, err := irpb.EdgesToPB(ctx, r.Edges)
	if err != nil {
		return nil, err
	}
	sequencesVal, err := irpb.SequencesToPB(ctx, r.Sequences)
	if err != nil {
		return nil, err
	}
	authoritiesVal, err := irpb.AuthoritiesToPB(ctx, r.Authorities)
	if err != nil {
		return nil, err
	}
	pb := &Program{
		Strata:            lo.Map(r.Strata, func(inner []string, _ int) *StratumWrapper { return &StratumWrapper{Values: inner} }),
		Wasm:              r.WASM,
		OutputMemoryBases: r.OutputMemoryBases,
		Functions:         functionsVal,
		Nodes:             nodesVal,
		Edges:             edgesVal,
		Sequences:         sequencesVal,
		Authorities:       authoritiesVal,
	}
	return pb, nil
}

// ProgramFromPB converts Program to Program.
func ProgramFromPB(ctx context.Context, pb *Program) (program.Program, error) {
	var r program.Program
	if pb == nil {
		return r, nil
	}
	var err error
	r.Functions, err = irpb.FunctionsFromPB(ctx, pb.Functions)
	if err != nil {
		return program.Program{}, err
	}
	r.Nodes, err = irpb.NodesFromPB(ctx, pb.Nodes)
	if err != nil {
		return program.Program{}, err
	}
	r.Edges, err = irpb.EdgesFromPB(ctx, pb.Edges)
	if err != nil {
		return program.Program{}, err
	}
	r.Sequences, err = irpb.SequencesFromPB(ctx, pb.Sequences)
	if err != nil {
		return program.Program{}, err
	}
	r.Authorities, err = irpb.AuthoritiesFromPB(ctx, pb.Authorities)
	if err != nil {
		return program.Program{}, err
	}
	r.Strata = lo.Map(pb.Strata, func(w *StratumWrapper, _ int) []string { return w.Values })
	r.WASM = pb.Wasm
	r.OutputMemoryBases = pb.OutputMemoryBases
	return r, nil
}

// ProgramsToPB converts a slice of Program to Program.
func ProgramsToPB(ctx context.Context, rs []program.Program) ([]*Program, error) {
	result := make([]*Program, len(rs))
	for i := range rs {
		var err error
		result[i], err = ProgramToPB(ctx, rs[i])
		if err != nil {
			return nil, err
		}
	}
	return result, nil
}

// ProgramsFromPB converts a slice of Program to Program.
func ProgramsFromPB(ctx context.Context, pbs []*Program) ([]program.Program, error) {
	result := make([]program.Program, len(pbs))
	for i, pb := range pbs {
		var err error
		result[i], err = ProgramFromPB(ctx, pb)
		if err != nil {
			return nil, err
		}
	}
	return result, nil
}
