load("@protobuf//bazel:proto_library.bzl", "proto_library")
load("@rules_proto_grpc_cpp//:defs.bzl", "cpp_grpc_library")

proto_library(
    name = "crdt_proto",
    srcs = ["pb/crdt.proto"],
    visibility = ["//visibility:public"],
    deps = ["//x/go/spatial:spatial_proto"],
)

cpp_grpc_library(
    name = "crdt_grpc",
    output_mode = "NO_PREFIX",
    protos = [":crdt_proto"],
    visibility = ["//visibility:public"],
    deps = ["//x/go/spatial:spatial_grpc"],
)
