// Copyright 2026 Synnax Labs, Inc.
//
// Use of this software is governed by the Business Source License included in the file
// licenses/BSL.txt.
//
// As of the Change Date specified in that file, in accordance with the Business Source
// License, use of this software will be governed by the Apache License, Version 2.0,
// included in the file licenses/APL.txt.

// Code generated by oracle. DO NOT EDIT.

package crdt

import (
	"github.com/synnaxlabs/x/encoding/orc"
	spatialv0 "github.com/synnaxlabs/x/spatial/types/v0"
)

func (d Delete) EncodeOrc(w *orc.Writer) error {
	if err := d.ID.EncodeOrc(w); err != nil {
		return err
	}
	return nil
}

func (d *Delete) DecodeOrc(r *orc.Reader) error {
	var err error
	if err = d.ID.DecodeOrc(r); err != nil {
		return err
	}
	return nil
}

func (id ID) EncodeOrc(w *orc.Writer) error {
	w.Uint32(uint32(id.Replica))
	w.Uint32(uint32(id.Counter))
	return nil
}

func (id *ID) DecodeOrc(r *orc.Reader) error {
	var err error
	if id.Replica, err = r.Uint32(); err != nil {
		return err
	}
	if id.Counter, err = r.Uint32(); err != nil {
		return err
	}
	return nil
}

func (iv Insert) EncodeOrc(w *orc.Writer) error {
	if err := iv.ID.EncodeOrc(w); err != nil {
		return err
	}
	if err := iv.Origin.EncodeOrc(w); err != nil {
		return err
	}
	w.String(string(iv.Side))
	w.Int32(int32(iv.Char))
	return nil
}

func (iv *Insert) DecodeOrc(r *orc.Reader) error {
	var err error
	if err = iv.ID.DecodeOrc(r); err != nil {
		return err
	}
	if err = iv.Origin.DecodeOrc(r); err != nil {
		return err
	}
	{
		v, err := r.String()
		if err != nil {
			return err
		}
		iv.Side = spatialv0.XLocation(v)
	}
	if iv.Char, err = r.Int32(); err != nil {
		return err
	}
	return nil
}
