// Copyright 2026 Synnax Labs, Inc.
//
// Use of this software is governed by the Business Source License included in the file
// licenses/BSL.txt.
//
// As of the Change Date specified in that file, in accordance with the Business Source
// License, use of this software will be governed by the Apache License, Version 2.0,
// included in the file licenses/APL.txt.

// Code generated by oracle. DO NOT EDIT.

#pragma once

#include <string>

#include "x/cpp/color/json.gen.h"
#include "x/cpp/json/json.h"
#include "x/cpp/label/types.gen.h"

namespace x::label {

inline Label Label::parse(x::json::Parser parser) {
    return Label{
        .key = parser.field<std::string>("key"),
        .name = parser.field<std::string>("name"),
        .color = parser.field<x::color::Color>("color"),
    };
}

inline x::json::json Label::to_json() const {
    x::json::json j;
    j["key"] = this->key;
    j["name"] = this->name;
    j["color"] = this->color;
    return j;
}

inline New New::parse(x::json::Parser parser) {
    New result;
    static_cast<Label &>(result) = Label::parse(parser);
    result.key = parser.field<std::string>("key", "");
    return result;
}

inline x::json::json New::to_json() const {
    x::json::json j;
    for (auto &[k, v]: Label::to_json().items())
        j[k] = v;
    j["key"] = this->key;
    return j;
}

}
