// Copyright 2026 Synnax Labs, Inc.
//
// Use of this software is governed by the Business Source License included in the file
// licenses/BSL.txt.
//
// As of the Change Date specified in that file, in accordance with the Business Source
// License, use of this software will be governed by the Apache License, Version 2.0,
// included in the file licenses/APL.txt.

// Code generated by oracle. DO NOT EDIT.

package arc

import (
	"github.com/synnaxlabs/x/union"
)

const (
	ActionTypeInsertChar = "insert_char"
	ActionTypeDeleteChar = "delete_char"
)

// InsertCharPayload carries a single collaborative-edit character insertion against the
// module's text. The payload is a sequence CRDT operation; the server relays it to the
// other editors of the module without interpreting it.
type InsertCharPayload struct {
}

// DeleteCharPayload carries a single collaborative-edit character deletion against the
// module's text. The payload is a sequence CRDT operation; the server relays it to the
// other editors of the module without interpreting it.
type DeleteCharPayload struct {
}

// Action is a discriminated union for all Arc mutations. Type names
// the variant; the matching pointer field carries the payload and others are nil.
type Action struct {
	Type       string             `json:"type" msgpack:"type"`
	InsertChar *InsertCharPayload `json:"insert_char,omitempty" msgpack:"insert_char,omitempty"`
	DeleteChar *DeleteCharPayload `json:"delete_char,omitempty" msgpack:"delete_char,omitempty"`
}

// Reduce applies the given actions sequentially to state by dispatching on
// each action's Type to the matching payload's Handle method. Unknown action
// types leave state unchanged. An action whose Type names a known variant but
// carries a nil payload pointer returns an error. Returns the first error
// encountered along with the partially-reduced state.
func Reduce(state Arc, actions ...Action) (Arc, error) {
	var err error
	for _, a := range actions {
		switch a.Type {
		case ActionTypeInsertChar:
			if a.InsertChar == nil {
				return state, union.MissingPayload(a.Type)
			}
			state, err = a.InsertChar.Handle(state)
		case ActionTypeDeleteChar:
			if a.DeleteChar == nil {
				return state, union.MissingPayload(a.Type)
			}
			state, err = a.DeleteChar.Handle(state)
		default:
			continue
		}
		if err != nil {
			return state, err
		}
	}
	return state, nil
}

// NewInsertCharAction wraps a InsertCharPayload in an Action envelope.
func NewInsertCharAction(p InsertCharPayload) Action {
	return Action{Type: ActionTypeInsertChar, InsertChar: &p}
}

// NewDeleteCharAction wraps a DeleteCharPayload in an Action envelope.
func NewDeleteCharAction(p DeleteCharPayload) Action {
	return Action{Type: ActionTypeDeleteChar, DeleteChar: &p}
}
