// Copyright 2026 Synnax Labs, Inc.
//
// Use of this software is governed by the Business Source License included in the file
// licenses/BSL.txt.
//
// As of the Change Date specified in that file, in accordance with the Business Source
// License, use of this software will be governed by the Apache License, Version 2.0,
// included in the file licenses/APL.txt.

// Code generated by oracle. DO NOT EDIT.

package arc

import (
	"context"
	"github.com/synnaxlabs/arc/graph"
	"github.com/synnaxlabs/arc/program"
	"github.com/synnaxlabs/arc/text"
	xbinary "github.com/synnaxlabs/x/binary"
	"github.com/synnaxlabs/x/encoding/orc"
	"github.com/synnaxlabs/x/status"
	"io"
	"sync"
)

func EncodeArc(w *orc.Writer, s *Arc) error {
	w.Write(s.Key[:])
	w.String(s.Name)
	w.String(string(s.Mode))
	if err := graph.EncodeGraph(w, &s.Graph); err != nil {
		return err
	}
	if err := text.EncodeText(w, &s.Text); err != nil {
		return err
	}
	if s.Program != nil {
		w.Bool(true)
		if err := program.EncodeProgram(w, &(*s.Program)); err != nil {
			return err
		}
	} else {
		w.Bool(false)
	}
	if s.Status != nil {
		w.Bool(true)
		if err := status.EncodeStatus[StatusDetails](w, &(*s.Status), EncodeStatusDetails); err != nil {
			return err
		}
	} else {
		w.Bool(false)
	}
	return nil
}

func DecodeArc(r *orc.Reader, s *Arc) error {
	var err error
	if _, err := r.Read(s.Key[:]); err != nil {
		return err
	}
	if s.Name, err = r.String(); err != nil {
		return err
	}
	{
		v, err := r.String()
		if err != nil {
			return err
		}
		s.Mode = Mode(v)
	}
	if err = graph.DecodeGraph(r, &s.Graph); err != nil {
		return err
	}
	if err = text.DecodeText(r, &s.Text); err != nil {
		return err
	}
	{
		present, err := r.Bool()
		if err != nil {
			return err
		}
		if present {
			var v program.Program
			if err = program.DecodeProgram(r, &v); err != nil {
				return err
			}
			s.Program = &v
		}
	}
	{
		present, err := r.Bool()
		if err != nil {
			return err
		}
		if present {
			var v Status
			if err = status.DecodeStatus[StatusDetails](r, &v, DecodeStatusDetails); err != nil {
				return err
			}
			s.Status = &v
		}
	}
	return nil
}

func EncodeStatusDetails(w *orc.Writer, s *StatusDetails) error {
	w.Bool(s.Running)
	return nil
}

func DecodeStatusDetails(r *orc.Reader, s *StatusDetails) error {
	var err error
	if s.Running, err = r.Bool(); err != nil {
		return err
	}
	return nil
}

var writerPool = sync.Pool{New: func() any { return orc.NewWriter(0) }}
var readerPool = sync.Pool{New: func() any { return orc.NewReader(nil) }}

type arcCodec struct{}

var ArcCodec xbinary.Codec = arcCodec{}

func (arcCodec) Encode(ctx context.Context, value any) ([]byte, error) {
	s := value.(Arc)
	w := writerPool.Get().(*orc.Writer)
	w.Reset()
	err := EncodeArc(w, &s)
	out := w.Copy()
	writerPool.Put(w)
	return out, err
}

func (c arcCodec) EncodeStream(ctx context.Context, w io.Writer, value any) error {
	b, err := c.Encode(ctx, value)
	if err != nil {
		return err
	}
	_, err = w.Write(b)
	return err
}

func (arcCodec) Decode(ctx context.Context, data []byte, value any) error {
	s := value.(*Arc)
	r := readerPool.Get().(*orc.Reader)
	r.ResetBytes(data)
	err := DecodeArc(r, s)
	readerPool.Put(r)
	return err
}

func (c arcCodec) DecodeStream(ctx context.Context, rd io.Reader, value any) error {
	data, err := io.ReadAll(rd)
	if err != nil {
		return err
	}
	return c.Decode(ctx, data, value)
}
