// Copyright 2026 Synnax Labs, Inc.
//
// Use of this software is governed by the Business Source License included in the file
// licenses/BSL.txt.
//
// As of the Change Date specified in that file, in accordance with the Business Source
// License, use of this software will be governed by the Apache License, Version 2.0,
// included in the file licenses/APL.txt.

// Code generated by oracle. DO NOT EDIT.

package versions

import (
	"context"

	"github.com/synnaxlabs/synnax/pkg/service/imex"
	"github.com/synnaxlabs/synnax/pkg/service/log/versions/v2"
)

// Latest is the portable schema version stamped on exported Log envelopes and the
// highest version import accepts. It equals the resource's current schema version.
const Latest = v2.Version

// autoDecodeEnvelope decodes a server-exported envelope as its version's Log
// shape and lifts it through the per-version migration chain to the current shape. A
// version the ladder does not cover is rejected with a path-scoped validation error.
func autoDecodeEnvelope(ctx context.Context, env imex.Envelope) (Log, error) {
	switch env.Version {
	case v2.Version:
		return imex.Decode[Log](ctx, env)
	}
	return Log{}, imex.NewErrUnsupportedVersion(env.Type, env.Version, Latest)
}
