name: Test Python
description: Common steps for testing Python packages

inputs:
  directory:
    description: The directory containing the Python package to test
    required: true
  coverage:
    description: Whether to collect and upload coverage
    required: false
    default: "false"
  coverage_module:
    description: The module name for pytest --cov (e.g., alamos, freighter, synnax)
    required: false
    default: ""
  coverage_flag:
    description: The codecov flag for this module
    required: false
    default: ""
  type_check:
    description: Whether to run mypy type checking
    required: false
    default: "false"
  format_check:
    description: Whether to run formatting checks (isort, black)
    required: false
    default: "false"

runs:
  using: composite
  steps:
    - name: Install uv
      uses: astral-sh/setup-uv@v7

    - name: Set up Python
      uses: actions/setup-python@v6
      with:
        python-version-file: ${{ inputs.directory }}/pyproject.toml

    - name: Check import order
      if: inputs.format_check == 'true'
      run: uv run isort -c .
      shell: bash
      working-directory: ${{ inputs.directory }}

    - name: Check formatting
      if: inputs.format_check == 'true'
      run: uv run black --check --diff --color .
      shell: bash
      working-directory: ${{ inputs.directory }}

    - name: Check types
      if: inputs.format_check == 'true' && inputs.type_check == 'true'
      run: uv run mypy .
      shell: bash
      working-directory: ${{ inputs.directory }}

    - name: Test
      if: inputs.coverage != 'true'
      run: uv run pytest
      shell: bash
      working-directory: ${{ inputs.directory }}

    - name: Test with coverage
      if: inputs.coverage == 'true'
      run: uv run pytest --cov=${{ inputs.coverage_module }} --cov-report=xml
      shell: bash
      working-directory: ${{ inputs.directory }}

    - name: Upload coverage
      if: inputs.coverage == 'true'
      uses: codecov/codecov-action@v5
      with:
        fail_ci_if_error: true
        flags: ${{ inputs.coverage_flag }}
        directory: ${{ inputs.directory }}
