version: "2"
linters:
  enable:
    - revive
    - mustsucceedlint
  settings:
    govet:
      enable-all: true
      disable:
        - shadow
        - fieldalignment
    revive:
      rules:
        - name: error-naming
        - name: var-declaration
        - name: var-naming
          arguments:
            - []
            - []
            - - skip-package-name-checks: true
  exclusions:
    generated: lax
  custom:
    mustsucceedlint:
      type: "module"
      description: >
        Detects Expect(err).ToNot(HaveOccurred()) patterns that can be replaced with
        MustSucceed.

run:
  build-tags:
    - console
    - driver
