version: "2"
linters:
  enable:
    - revive
  settings:
    govet:
      enable-all: true
      disable:
        - shadow
        - fieldalignment
    revive:
      rules:
        - name: error-naming
        - name: var-declaration
        - name: var-naming
          arguments:
            - []
            - []
            - - skip-package-name-checks: true
  exclusions:
    generated: lax

run:
  build-tags:
    - console
    - driver
