version: "2"
linters:
  enable:
    - revive
    - mustsucceedlint
    - setlint
  settings:
    govet:
      enable-all: true
      disable:
        - shadow
        - fieldalignment
    revive:
      rules:
        - name: error-naming
        - name: var-declaration
        - name: var-naming
          arguments:
            - []
            - []
            - - skip-package-name-checks: true
    custom:
      mustsucceedlint:
        type: "module"
        description: >
          Detects Expect(err).ToNot(HaveOccurred()) patterns that can be replaced with
          MustSucceed.
      setlint:
        type: "module"
        description: >
          Detects map[T]struct{} and map[T]bool patterns that should use set.Set[T].

run:
  build-tags:
    - console
    - driver
