packages:
  - alamos/ts
  - client/ts
  - configs/**
  - console
  - docs/site
  - docs/videos
  - drift
  - freighter/ts
  - pluto
  - x/media
  - x/ts

catalog:
  '@eslint/compat': ^1.3.2
  '@fontsource/geist-mono': ^5.2.6
  '@fontsource/inter': ^5.2.7
  '@reduxjs/toolkit': ^2.9.0
  '@tauri-apps/api': ^2.8.0
  '@testing-library/react': ^16.3.0
  '@types/node': ^24.4.0
  '@types/offscreencanvas': ^2019.7.3
  '@types/react': ^19.1.13
  '@types/react-dom': ^19.1.9
  '@vitejs/plugin-react': ^5.0.2
  '@vitest/coverage-v8': ^3.2.4
  async-mutex: ^0.5.0
  clsx: ^2.1.1
  compromise: ^14.14.4
  compromise-dates: ^3.7.1
  eslint: ^9.35.0
  madge: ^8.0.0
  prettier: ^3.6.2
  proxy-memoize: 2.0.3
  react: ^19.1.1
  react-dom: ^19.1.1
  react-icons: ^5.5.0
  react-redux: ^9.2.0
  typescript: ^5.9.2
  vite: ^7.1.5
  vitest: ^3.2.4
  zod: ^4.1.8
