packages:
  - alamos/ts
  - client/ts
  - configs/**
  - console
  - docs/site
  - docs/videos
  - drift
  - freighter/ts
  - integration/ts
  - pluto
  - x/media
  - x/ts

catalog:
  '@eslint/compat': ^1.3.0
  '@fontsource/geist-mono': ^5.2.6
  '@fontsource/inter': ^5.2.6
  '@reduxjs/toolkit': ^2.8.2
  '@tauri-apps/api': ^2.5.0
  '@testing-library/react': ^16.3.0
  '@types/node': ^24.0.1
  '@types/offscreencanvas': ^2019.7.3
  '@types/react': ^19.1.8
  '@types/react-dom': ^19.1.6
  '@vitejs/plugin-react': ^4.5.2
  '@vitest/coverage-v8': ^3.2.3
  async-mutex: ^0.5.0
  clsx: ^2.1.1
  compromise: ^14.14.4
  compromise-dates: ^3.7.1
  eslint: ^9.29.0
  madge: ^8.0.0
  prettier: ^3.5.3
  proxy-memoize: 2.0.3
  react: ^19.1.0
  react-dom: ^19.1.0
  react-icons: ^5.5.0
  react-redux: ^9.2.0
  typescript: ^5.8.3
  vite: ^7.0.4
  vitest: ^3.2.3
  zod: ^4.0.2
