packages:
  - alamos/ts
  - arc/ts
  - client/ts
  - configs/**
  - console
  - docs/site
  - drift
  - freighter/ts
  - pluto
  - x/media
  - x/ts

catalog:
  '@fontsource/geist-mono': ^5.2.7
  '@fontsource/inter': ^5.2.8
  '@reduxjs/toolkit': ^2.11.2
  '@tauri-apps/api': ^2.9.1
  '@testing-library/react': ^16.3.2
  '@types/node': ^25.1.0
  '@types/offscreencanvas': ^2019.7.3
  '@types/pluralize': ^0.0.33
  '@types/react': ^19.2.10
  '@types/react-dom': ^19.2.3
  '@vitejs/plugin-react': ^5.1.2
  '@vitest/coverage-v8': ^3.2.4
  async-mutex: ^0.5.0
  clsx: ^2.1.1
  compromise: ^14.14.5
  compromise-dates: ^3.7.1
  eslint: ^9.39.2
  madge: ^8.0.0
  pluralize: ^8.0.0
  prettier: ^3.7.4
  proxy-memoize: 2.0.3
  react: ^19.2.4
  react-dom: ^19.2.4
  react-icons: ^5.5.0
  react-redux: ^9.2.0
  typescript: ^5.9.3
  vite: ^7.2.7
  vitest: ^3.2.4
  zod: ^4.1.13
