packages:
  - alamos/ts
  - arc/ts
  - client/ts
  - configs/**
  - console
  - docs/site
  - drift
  - freighter/ts
  - pluto
  - x/media
  - x/ts

allowBuilds:
  core-js: false
  esbuild: true
  protobufjs: false
  sharp: true

catalog:
  '@fontsource/geist-mono': ^5.2.8
  '@fontsource/inter': ^5.2.8
  '@reduxjs/toolkit': ^2.12.0
  '@tauri-apps/api': ^2.11.1
  '@testing-library/react': ^16.3.2
  '@types/node': ^25.9.0
  '@types/offscreencanvas': ^2019.7.3
  '@types/pluralize': ^0.0.33
  '@types/react': ^19.2.14
  '@types/react-dom': ^19.2.3
  '@vitejs/plugin-react': ^6.0.2
  '@vitest/coverage-v8': ^4.1.6
  async-mutex: ^0.5.0
  clsx: ^2.1.1
  compromise: ^14.15.0
  compromise-dates: ^3.7.1
  eslint: ^10.4.0
  immer: ^11.1.8
  jsdom: ^29.1.1
  madge: ^8.0.0
  pluralize: ^8.0.0
  react: ^19.2.6
  react-dom: ^19.2.6
  react-icons: ^5.6.0
  react-redux: ^9.3.0
  stylelint: ^17.11.1
  stylelint-config-standard: ^40.0.0
  typescript: ^6.0.3
  vite: ^8.0.13
  vitest: ^4.1.6
  zod: ^4.4.3
