# Copyright 2026 Synnax Labs, Inc.
#
# Use of this software is governed by the Business Source License included in the file
# licenses/BSL.txt.
#
# As of the Change Date specified in that file, in accordance with the Business Source
# License, use of this software will be governed by the Apache License, Version 2.0,
# included in the file licenses/APL.txt.

[project]
name = "synnax-workspace"
version = "0.0.0"
description = "Synnax Python Workspace"
requires-python = ">=3.12,<4"

[dependency-groups]
dev = ["vermin>=1.8.0,<2"]

[tool.uv]
managed = true

[tool.uv.workspace]
members = ["alamos/py", "client/py", "freighter/py", "integration", "x/py"]

[tool.uv.sources]
alamos = { workspace = true }
synnax-freighter = { workspace = true }
synnax = { workspace = true }
synnax-x = { workspace = true }
