// Copyright 2026 Synnax Labs, Inc.
//
// Use of this software is governed by the Business Source License included in the file
// licenses/BSL.txt.
//
// As of the Change Date specified in that file, in accordance with the Business Source
// License, use of this software will be governed by the Apache License, Version 2.0,
// included in the file licenses/APL.txt.

// Code generated by Oracle. DO NOT EDIT.

import { id } from "@synnaxlabs/x";
import { z } from "zod";

import { channel } from "@/channel";
import { device } from "@/device";
import { http } from "@/http";
import { task } from "@/task";

export const START_OFFSETS = ["latest", "earliest", "none"] as const;
export const startOffsetZ = z.enum(START_OFFSETS);
export type StartOffset = z.infer<typeof startOffsetZ>;

export const RECORD_KEYS = ["none", "channel_name"] as const;
export const recordKeyZ = z.enum(RECORD_KEYS);
export type RecordKey = z.infer<typeof recordKeyZ>;

/** Credentials carries the username and password of a SASL mechanism. */
export const credentialsZ = z.object({
  /** username is the SASL username. */
  username: z.string().default(""),
  /** password is the SASL password. */
  password: z.string().default(""),
});
export interface Credentials extends z.infer<typeof credentialsZ> {}

export const scanConfigZ = task.scanConfigZ;
export interface ScanConfig extends z.infer<typeof scanConfigZ> {}

/** ReadField is a single value extracted from a record's JSON value. */
export const readFieldZ = z.object({
  /** key uniquely identifies the field within the task. */
  key: z.string().default(id.create),
  /** disabled is true when the field is excluded from the task. */
  disabled: z.boolean().default(false),
  /** name is the name given to the channel when the task creates it. */
  name: z.string().default(""),
  /** channel is the Synnax channel the extracted value is written to. */
  channel: channel.keyZ.default(0),
  /** pointer is the JSON Pointer to the value within the record value. */
  pointer: z.string().default(""),
  /** dataType is the data type of the extracted value. */
  dataType: z.string().default("float64"),
  /**
   * timeFormat is the encoding of the JSON value when the target channel holds
   * timestamps. Required for timestamp channels.
   */
  timeFormat: http.timeFormatZ.optional(),
  /** enumValues maps string labels in the record to numeric channel values. */
  enumValues: http.enumEntryZ.array().default(() => []),
  /**
   * recordKey is the group the field belongs to: records with this key, or every record
   * not claimed by another group when empty. A group shares one index.
   */
  recordKey: z.string().default(""),
});
export interface ReadField extends z.infer<typeof readFieldZ> {}

/** WriteChannel is a channel whose samples a write task produces as records. */
export const writeChannelZ = z.object({
  /** key uniquely identifies the channel within the task. */
  key: z.string().default(id.create),
  /** disabled is true when the channel is excluded from the task. */
  disabled: z.boolean().default(false),
  /** channel is the Synnax channel whose samples are produced. */
  channel: channel.keyZ.default(0),
  /** jsonType is the JSON type the sample value is serialized as. */
  jsonType: http.jsonTypeZ.default("number"),
  /**
   * timeFormat is the output encoding when the channel holds timestamps. Required for
   * timestamp channels.
   */
  timeFormat: http.timeFormatZ.optional(),
  /**
   * enumValues maps numeric channel values to string labels. Only valid when json_type
   * is 'string'.
   */
  enumValues: http.enumEntryZ.array().default(() => []),
});
export interface WriteChannel extends z.infer<typeof writeChannelZ> {}

/** Record is the shape of every record a write task produces. */
export const recordZ = z.object({
  /** valuePointer is the JSON Pointer where the sample value is placed. */
  valuePointer: z.string().default("/value"),
  /**
   * channelPointer is the JSON Pointer where the channel name is placed. Empty omits
   * the name.
   */
  channelPointer: z.string().default("/channel"),
  /**
   * timestampPointer is the JSON Pointer where the sample timestamp is placed. Empty
   * omits the timestamp.
   */
  timestampPointer: z.string().default("/timestamp"),
  /** timeFormat is the encoding of the sample timestamp. */
  timeFormat: http.timeFormatZ.default("unix_ns"),
  /** fields contains additional static or generated record fields. */
  fields: http.writeFieldZ.array().default(() => []),
});
export interface Record extends z.infer<typeof recordZ> {}

/** NoneSASL authenticates with no credentials. */
export const noneSASLZ = z.object({
  mechanism: z.literal("none"),
});
export interface NoneSASL extends z.infer<typeof noneSASLZ> {}

/** PlainSASL authenticates with the PLAIN mechanism. */
export const plainSASLZ = credentialsZ.extend({
  mechanism: z.literal("plain"),
});
export interface PlainSASL extends z.infer<typeof plainSASLZ> {}

/** ScramSha256SASL authenticates with the SCRAM-SHA-256 mechanism. */
export const scramSha256SASLZ = credentialsZ.extend({
  mechanism: z.literal("scram_sha_256"),
});
export interface ScramSha256SASL extends z.infer<typeof scramSha256SASLZ> {}

/** ScramSha512SASL authenticates with the SCRAM-SHA-512 mechanism. */
export const scramSha512SASLZ = credentialsZ.extend({
  mechanism: z.literal("scram_sha_512"),
});
export interface ScramSha512SASL extends z.infer<typeof scramSha512SASLZ> {}

export const SASL_TYPES = ["none", "plain", "scram_sha_256", "scram_sha_512"] as const;
export const saslTypeZ = z.enum(SASL_TYPES);
export type SASLType = z.infer<typeof saslTypeZ>;

/** SASL selects the SASL mechanism and the credentials it carries. */
export const saslZ = z.discriminatedUnion("mechanism", [
  noneSASLZ,
  plainSASLZ,
  scramSha256SASLZ,
  scramSha512SASLZ,
]);
export type SASL = NoneSASL | PlainSASL | ScramSha256SASL | ScramSha512SASL;

export const SASL_SCHEMAS: {
  [K in SASLType]: z.ZodType<Extract<SASL, { mechanism: K }>>;
} = {
  none: noneSASLZ,
  plain: plainSASLZ,
  scram_sha_256: scramSha256SASLZ,
  scram_sha_512: scramSha512SASLZ,
};

export const readConfigZ = task.persistConfigZ.extend({
  device: device.keyZ.default(""),
  topic: z.string().default(""),
  group: z.string().default(""),
  startOffset: startOffsetZ.default("latest"),
  fields: readFieldZ.array().default(() => []),
});
export interface ReadConfig extends z.infer<typeof readConfigZ> {}

export const writeConfigZ = task.startConfigZ.extend({
  device: device.keyZ.default(""),
  topic: z.string().default(""),
  recordKey: recordKeyZ.default("channel_name"),
  record: recordZ.prefault({}),
  channels: writeChannelZ.array().default(() => []),
});
export interface WriteConfig extends z.infer<typeof writeConfigZ> {}

/** Properties configures the connection to a Kafka cluster device. */
export const propertiesZ = z.object({
  /** brokers contains the bootstrap broker addresses, as host:port. */
  brokers: z
    .string()
    .array()
    .default(() => []),
  /** tls is true when every broker connection uses TLS. */
  tls: z.boolean().default(false),
  /** sasl is the authentication the brokers require. */
  sasl: saslZ.prefault({ mechanism: "none" }),
});
export interface Properties extends z.infer<typeof propertiesZ> {}
