# Code generated by Oracle. DO NOT EDIT.

from __future__ import annotations
from typing import Any, NewType
from enum import IntEnum
from pydantic import BaseModel
from synnax.telem import TimeSpan
from synnax.ontology.payload import ID
from control import control
from node import node

Key = int

Key = NewType("Key", int)

LocalKey = NewType("LocalKey", Any)


class Concurrency(IntEnum):
    exclusive = 0
    shared = 1


class Operation(BaseModel):
    type: str
    reset_channel: Key
    duration: TimeSpan


class Channel(BaseModel):
    name: str
    leaseholder: node.Key
    data_type: Any
    is_index: bool
    local_key: LocalKey
    local_index: LocalKey
    virtual: bool
    concurrency: control.Concurrency
    internal: bool
    operations: list[Operation]
    expression: str


class Channel(BaseModel):
    key: Key
    name: str
    leaseholder: int
    data_type: str
    density: int
    is_index: bool
    index: Key
    alias: str | None = None
    virtual: bool | None = None
    internal: bool | None = None
    expression: str | None = None
    operations: list[Operation] | None = None


APICHANNEL_ONTOLOGY_TYPE = ID(type="channel")


def ontology_id(key: int) -> ID:
    return ID(type="channel", key=str(key))
