import re
from playwright.sync_api import Page, expect


def test_example(page: Page) -> None:
    # Set timeouts for this test
    page.set_default_timeout(10000)  # 10 seconds for actions
    page.set_default_navigation_timeout(30000)  # 30 seconds for navigation
    
    page.goto("http://localhost:5173/")
    page.get_by_role("textbox", name="synnax").fill("synnax")
    page.get_by_role("textbox", name="seldon").click()
    page.get_by_role("textbox", name="seldon").fill("seldon")
    page.get_by_role("button", name="Sign In").click()
    page.get_by_role("button").filter(has_text=re.compile(r"^$")).nth(2).click()
    page.get_by_role("button", name="pluto-icon--line-plot Line").click()
    page.locator("[id=\"«r5»\"]").click()
    page.get_by_role("button", name="pluto-icon--schematic").click()
    page.locator("[id=\"«r5»\"]").click()
    page.get_by_role("button", name="pluto-icon--log Log").click()
    page.locator("#tab-1").get_by_role("button").nth(4).click()
    page.get_by_role("button", name="pluto-icon--table Table").click()
    page.locator("[id=\"«r5»\"]").click()
    page.get_by_role("button", name="pluto-icon--logo-ni NI Analog Read Task").click()
    page.locator("[id=\"«r5»\"]").click()
    page.get_by_role("button", name="pluto-icon--logo-ni NI Analog Write Task").click()
    page.locator("[id=\"«r5»\"]").click()
    page.get_by_role("button", name="pluto-icon--logo-ni NI Digital Read Task").click()
    page.locator("[id=\"«r5»\"]").click()
    page.get_by_role("button", name="pluto-icon--logo-ni NI Digital Write Task").click()
    page.locator("[id=\"«r5»\"]").click()
    page.get_by_role("button", name="pluto-icon--logo-labjack LabJack Read Task").click()
    page.locator("[id=\"«r5»\"]").click()
    page.get_by_role("button", name="pluto-icon--logo-labjack LabJack Write Task").click()
    page.locator("[id=\"«r5»\"]").click()
    page.get_by_role("button", name="pluto-icon--logo-opc OPC UA Read Task").click()
    page.locator("[id=\"«r5»\"]").click()
    page.get_by_role("button", name="pluto-icon--logo-opc OPC UA Write Task").click()
    page.locator("[id=\"«r5»\"]").click()
    page.get_by_role("button", name="pluto-icon--control Control").click()
    page.get_by_role("textbox", name="Name").fill("sequence")
    page.get_by_role("textbox", name="Name").press("ControlOrMeta+Enter")
    page.locator("#getStarted").get_by_role("button", name="pluto-tabs__close").click()
    page.locator("div").filter(has_text=re.compile(r"^Line Plot$")).get_by_label("pluto-tabs__close").click()
    page.locator("div").filter(has_text=re.compile(r"^Schematic$")).get_by_label("pluto-tabs__close").click()
    page.locator("div").filter(has_text=re.compile(r"^Log$")).get_by_label("pluto-tabs__close").click()
    page.locator("div").filter(has_text=re.compile(r"^Table$")).get_by_label("pluto-tabs__close").click()
    page.locator("div").filter(has_text=re.compile(r"^NI Analog Read Task$")).get_by_label("pluto-tabs__close").click()
    page.locator("div").filter(has_text=re.compile(r"^NI Analog Write Task$")).get_by_label("pluto-tabs__close").click()
    page.locator("div").filter(has_text=re.compile(r"^NI Digital Read Task$")).get_by_label("pluto-tabs__close").click()
    page.locator("div").filter(has_text=re.compile(r"^NI Digital Write Task$")).get_by_label("pluto-tabs__close").click()
    page.locator("div").filter(has_text=re.compile(r"^LabJack Read Task$")).get_by_label("pluto-tabs__close").click()
    page.locator("div").filter(has_text=re.compile(r"^LabJack Write Task$")).get_by_label("pluto-tabs__close").click()
    page.locator("div").filter(has_text=re.compile(r"^OPC UA Read Task$")).get_by_label("pluto-tabs__close").click()
    page.locator("div").filter(has_text=re.compile(r"^OPC UA Write Task$")).get_by_label("pluto-tabs__close").click()
    page.get_by_role("button", name="pluto-tabs__close").click()
