import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('http://localhost:5173/');
  await page.getByRole('textbox', { name: 'synnax' }).fill('synnax');
  await page.getByRole('textbox', { name: 'seldon' }).click();
  await page.getByRole('textbox', { name: 'seldon' }).fill('seldon');
  await page.getByRole('button', { name: 'Sign In' }).click();
  await page.getByRole('button').filter({ hasText: /^$/ }).nth(2).click();
  await page.getByRole('button', { name: 'pluto-icon--line-plot Line' }).click();
  await page.locator('[id="«r5»"]').click();
  await page.getByRole('button', { name: 'pluto-icon--schematic' }).click();
  await page.locator('[id="«r5»"]').click();
  await page.getByRole('button', { name: 'pluto-icon--log Log' }).click();
  await page.locator('#tab-1').getByRole('button').nth(4).click();
  await page.getByRole('button', { name: 'pluto-icon--table Table' }).click();
  await page.locator('[id="«r5»"]').click();
  await page.getByRole('button', { name: 'pluto-icon--logo-ni NI Analog Read Task' }).click();
  await page.locator('[id="«r5»"]').click();
  await page.getByRole('button', { name: 'pluto-icon--logo-ni NI Analog Write Task' }).click();
  await page.locator('[id="«r5»"]').click();
  await page.getByRole('button', { name: 'pluto-icon--logo-ni NI Digital Read Task' }).click();
  await page.locator('[id="«r5»"]').click();
  await page.getByRole('button', { name: 'pluto-icon--logo-ni NI Digital Write Task' }).click();
  await page.locator('[id="«r5»"]').click();
  await page.getByRole('button', { name: 'pluto-icon--logo-labjack LabJack Read Task' }).click();
  await page.locator('[id="«r5»"]').click();
  await page.getByRole('button', { name: 'pluto-icon--logo-labjack LabJack Write Task' }).click();
  await page.locator('[id="«r5»"]').click();
  await page.getByRole('button', { name: 'pluto-icon--logo-opc OPC UA Read Task' }).click();
  await page.locator('[id="«r5»"]').click();
  await page.getByRole('button', { name: 'pluto-icon--logo-opc OPC UA Write Task' }).click();
  await page.locator('[id="«r5»"]').click();
  await page.getByRole('button', { name: 'pluto-icon--control Control' }).click();
  await page.getByRole('textbox', { name: 'Name' }).fill('sequence');
  await page.getByRole('textbox', { name: 'Name' }).press('ControlOrMeta+Enter');
  await page.locator('#getStarted').getByRole('button', { name: 'pluto-tabs__close' }).click();
  await page.locator('div').filter({ hasText: /^Line Plot$/ }).getByLabel('pluto-tabs__close').click();
  await page.locator('div').filter({ hasText: /^Schematic$/ }).getByLabel('pluto-tabs__close').click();
  await page.locator('div').filter({ hasText: /^Log$/ }).getByLabel('pluto-tabs__close').click();
  await page.locator('div').filter({ hasText: /^Table$/ }).getByLabel('pluto-tabs__close').click();
  await page.locator('div').filter({ hasText: /^NI Analog Read Task$/ }).getByLabel('pluto-tabs__close').click();
  await page.locator('div').filter({ hasText: /^NI Analog Write Task$/ }).getByLabel('pluto-tabs__close').click();
  await page.locator('div').filter({ hasText: /^NI Digital Read Task$/ }).getByLabel('pluto-tabs__close').click();
  await page.locator('div').filter({ hasText: /^NI Digital Write Task$/ }).getByLabel('pluto-tabs__close').click();
  await page.locator('div').filter({ hasText: /^LabJack Read Task$/ }).getByLabel('pluto-tabs__close').click();
  await page.locator('div').filter({ hasText: /^LabJack Write Task$/ }).getByLabel('pluto-tabs__close').click();
  await page.locator('div').filter({ hasText: /^OPC UA Read Task$/ }).getByLabel('pluto-tabs__close').click();
  await page.locator('div').filter({ hasText: /^OPC UA Write Task$/ }).getByLabel('pluto-tabs__close').click();
  await page.getByRole('button', { name: 'pluto-tabs__close' }).click();
});