// Copyright 2026 Synnax Labs, Inc.
//
// Use of this software is governed by the Business Source License included in the file
// licenses/BSL.txt.
//
// As of the Change Date specified in that file, in accordance with the Business Source
// License, use of this software will be governed by the Apache License, Version 2.0,
// included in the file licenses/APL.txt.

// Package actions generates a discriminated-union action codec for any oracle
// struct that declares one or more actions. Each action becomes a payload type
// with JSON+msgpack tags, an Action envelope dispatches by Type, and Reduce /
// ReduceAll apply actions sequentially to the target struct value. Per-action
// behavior (the Handle method on each payload type) is hand-written in a sibling
// file and is not generated by this plugin.
package actions

import (
	"bytes"
	"strings"
	"text/template"

	"github.com/samber/lo"
	"github.com/synnaxlabs/oracle/domain/doc"
	"github.com/synnaxlabs/oracle/exec"
	"github.com/synnaxlabs/oracle/plugin"
	"github.com/synnaxlabs/oracle/plugin/go/internal/imports"
	"github.com/synnaxlabs/oracle/plugin/go/internal/naming"
	goprimitives "github.com/synnaxlabs/oracle/plugin/go/primitives"
	gotypes "github.com/synnaxlabs/oracle/plugin/go/types"
	"github.com/synnaxlabs/oracle/plugin/output"
	"github.com/synnaxlabs/oracle/plugin/resolver"
	"github.com/synnaxlabs/oracle/resolution"
)

// Options configures the actions plugin output.
type Options struct {
	// FileNamePattern is the basename written for each output package.
	FileNamePattern string
}

// DefaultOptions returns the production defaults: actions.gen.go.
func DefaultOptions() Options {
	return Options{FileNamePattern: "actions.gen.go"}
}

// Plugin emits the generated action codec.
type Plugin struct{ Options Options }

// New constructs a Plugin with the given options.
func New(opts Options) *Plugin { return &Plugin{Options: opts} }

func (p *Plugin) Name() string                  { return "go/actions" }
func (p *Plugin) Domains() []string             { return []string{"go"} }
func (p *Plugin) Requires() []string            { return []string{"go/types"} }
func (p *Plugin) Check(_ *plugin.Request) error { return nil }

var goPostWriter = &exec.PostWriter{
	Extensions: []string{".go"},
	Commands:   [][]string{{"gofmt", "-w"}},
}

// PostWrite runs gofmt on the generated files.
func (p *Plugin) PostWrite(files []string) error {
	return goPostWriter.PostWrite(files)
}

// Generate emits one actions.gen.go per output package containing structs that
// declare actions. Structs without actions are skipped.
func (p *Plugin) Generate(req *plugin.Request) (*plugin.Response, error) {
	resp := &plugin.Response{}
	for _, typ := range req.Resolutions.StructTypes() {
		form, ok := typ.Form.(resolution.StructForm)
		if !ok || len(form.Actions) == 0 {
			continue
		}
		outputPath := output.GetPath(typ, "go")
		if outputPath == "" {
			continue
		}
		content, err := p.generateFile(typ, form, outputPath, req)
		if err != nil {
			return nil, err
		}
		resp.Files = append(resp.Files, plugin.File{
			Path:    outputPath + "/" + p.Options.FileNamePattern,
			Content: content,
		})
	}
	return resp, nil
}

func (p *Plugin) generateFile(
	typ resolution.Type,
	form resolution.StructForm,
	outputPath string,
	req *plugin.Request,
) ([]byte, error) {
	pkg := naming.DerivePackageName(outputPath)
	mgr := imports.NewManager()
	ctx := &resolver.Context{
		Table:                         req.Resolutions,
		OutputPath:                    outputPath,
		Namespace:                     typ.Namespace,
		RepoRoot:                      req.RepoRoot,
		DomainName:                    "go",
		SubstituteDefaultedTypeParams: true,
	}
	r := &resolver.Resolver{
		Formatter:       gotypes.GoFormatter(),
		ImportResolver:  &gotypes.GoImportResolver{RepoRoot: req.RepoRoot, CurrentPackage: pkg},
		ImportAdder:     mgr,
		PrimitiveMapper: goprimitives.Mapper(),
	}

	data := templateData{
		Package:    pkg,
		TargetType: naming.GetGoName(typ),
		imports:    mgr,
	}

	for _, action := range form.Actions {
		ad := actionData{
			Name:     naming.ToPascalCase(action.Name),
			TypeName: lo.SnakeCase(action.Name),
			Doc:      doc.Get(action.Domains),
		}
		for _, field := range action.Fields {
			ad.Fields = append(ad.Fields, processField(field, r, ctx))
		}
		data.Actions = append(data.Actions, ad)
	}

	var buf bytes.Buffer
	if err := fileTemplate.Execute(&buf, &data); err != nil {
		return nil, err
	}
	return buf.Bytes(), nil
}

// processField mirrors gotypes' optionality handling: hard-optional values get a
// pointer prefix only when the underlying type is not already a slice, map, or
// msgpack.EncodedJSON (which carry their own nil semantics).
func processField(
	field resolution.Field,
	r *resolver.Resolver,
	ctx *resolver.Context,
) fieldData {
	goType := r.ResolveTypeRef(field.Type, ctx)
	if field.IsHardOptional &&
		!strings.HasPrefix(goType, "[]") &&
		!strings.HasPrefix(goType, "map[") &&
		!strings.HasPrefix(goType, "msgpack.EncodedJSON") {
		goType = "*" + goType
	}
	return fieldData{
		GoName:         naming.GetFieldName(field),
		GoType:         goType,
		JSONName:       lo.SnakeCase(field.Name),
		IsHardOptional: field.IsHardOptional,
	}
}

type templateData struct {
	Package    string
	TargetType string
	Actions    []actionData
	imports    *imports.Manager
}

func (d *templateData) HasImports() bool          { return d.imports.HasImports() }
func (d *templateData) ExternalImports() []string { return d.imports.ExternalImports() }
func (d *templateData) InternalImports() []imports.InternalImportData {
	return d.imports.InternalImports()
}

type actionData struct {
	Name     string
	TypeName string
	Doc      string
	Fields   []fieldData
}

type fieldData struct {
	GoName         string
	GoType         string
	JSONName       string
	IsHardOptional bool
}

// TagSuffix returns the JSON/msgpack tag suffix that controls omitempty
// emission for hard-optional fields.
func (f fieldData) TagSuffix() string {
	if f.IsHardOptional {
		return ",omitempty"
	}
	return ""
}

var templateFuncs = template.FuncMap{
	"formatDoc": doc.FormatGo,
}

var fileTemplate = template.Must(template.New("go-actions").Funcs(templateFuncs).Parse(`// Code generated by oracle. DO NOT EDIT.

package {{.Package}}
{{- if .HasImports}}

import (
{{- range .ExternalImports}}
	"{{.}}"
{{- end}}
{{- range .InternalImports}}
{{- if .NeedsAlias}}
	{{.Alias}} "{{.Path}}"
{{- else}}
	"{{.Path}}"
{{- end}}
{{- end}}
)
{{- end}}

const (
{{- range .Actions}}
	ActionType{{.Name}} = "{{.TypeName}}"
{{- end}}
)
{{range .Actions}}
{{- if .Doc}}
{{formatDoc .Name .Doc}}
{{end -}}
type {{.Name}} struct {
{{- range .Fields}}
	{{.GoName}} {{.GoType}} ` + "`" + `json:"{{.JSONName}}{{.TagSuffix}}" msgpack:"{{.JSONName}}{{.TagSuffix}}"` + "`" + `
{{- end}}
}
{{end}}
// Action is a discriminated union for all {{.TargetType}} mutations. Type names
// the variant; the matching pointer field carries the payload and others are nil.
type Action struct {
	Type string ` + "`" + `json:"type" msgpack:"type"` + "`" + `
{{- range .Actions}}
	{{.Name}} *{{.Name}} ` + "`" + `json:"{{.TypeName}},omitempty" msgpack:"{{.TypeName}},omitempty"` + "`" + `
{{- end}}
}

// Reduce applies the action to the given state by dispatching on Type to the
// matching payload's Handle method. Unknown action types return state unchanged.
func (a Action) Reduce(state {{.TargetType}}) ({{.TargetType}}, error) {
	switch a.Type {
{{- range .Actions}}
	case ActionType{{.Name}}:
		return a.{{.Name}}.Handle(state)
{{- end}}
	default:
		return state, nil
	}
}

// ReduceAll applies a sequence of actions to the given state. Returns the first
// error encountered along with the partially-reduced state.
func ReduceAll(state {{.TargetType}}, actions []Action) ({{.TargetType}}, error) {
	var err error
	for _, a := range actions {
		state, err = a.Reduce(state)
		if err != nil {
			return state, err
		}
	}
	return state, nil
}
{{range .Actions}}
// New{{.Name}}Action wraps a {{.Name}} payload in an Action envelope.
func New{{.Name}}Action(p {{.Name}}) Action {
	return Action{Type: ActionType{{.Name}}, {{.Name}}: &p}
}
{{end -}}
`))
