load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

http_archive(
  name = "com_google_protobuf",
  strip_prefix = "protobuf-23.4",
  urls = ["https://github.com/protocolbuffers/protobuf/archive/v23.4.tar.gz"],
)

http_archive(
  name = "com_github_grpc_grpc",
  strip_prefix = "grpc-1.57.0",
  urls = ["https://github.com/grpc/grpc/archive/v1.57.0.tar.gz"],
)

http_archive(
    name = "rules_proto_grpc",
    sha256 = "9ba7299c5eb6ec45b6b9a0ceb9916d0ab96789ac8218269322f0124c0c0d24e2",
    strip_prefix = "rules_proto_grpc-4.5.0",
    urls = ["https://github.com/rules-proto-grpc/rules_proto_grpc/releases/download/4.5.0/rules_proto_grpc-4.5.0.tar.gz"],
)

load("@rules_proto_grpc//:repositories.bzl", "rules_proto_grpc_repos", "rules_proto_grpc_toolchains")

rules_proto_grpc_toolchains()

rules_proto_grpc_repos()

load("@rules_proto//proto:repositories.bzl", "rules_proto_dependencies", "rules_proto_toolchains")

rules_proto_dependencies()

rules_proto_toolchains()

load("@rules_proto_grpc//cpp:repositories.bzl", "cpp_repos")

cpp_repos()

load("@com_github_grpc_grpc//bazel:grpc_deps.bzl", "grpc_deps")

grpc_deps()

load("@com_github_grpc_grpc//bazel:grpc_extra_deps.bzl", "grpc_extra_deps")

grpc_extra_deps()

# Synnax Telemetry Protos
local_repository(
    name = "telem_protos",
    path = "../../../../x/go/telem",
)

# Synnax Freighter Errors Protos
local_repository(
    name = "ferrors_protos",
    path = "../../../../freighter/go",
)
