// Copyright 2026 Synnax Labs, Inc.
//
// Use of this software is governed by the Business Source License included in the file
// licenses/BSL.txt.
//
// As of the Change Date specified in that file, in accordance with the Business Source
// License, use of this software will be governed by the Apache License, Version 2.0,
// included in the file licenses/APL.txt.

// Code generated by oracle. DO NOT EDIT.

package versions

import "github.com/synnaxlabs/synnax/pkg/service/task/versions/v2"

// Key is a unique identifier for a task.
type Key = v2.Key

// StatusDetails contains task-specific status details including execution state.
type StatusDetails = v2.StatusDetails

// Status is task-specific status information including execution state and
// task-specific data.
type Status = v2.Status

// Task is an executable unit of work in the Driver system. Tasks represent specific
// hardware operations such as reading sensor data, writing control signals, or scanning
// for devices.
type Task = v2.Task
