// Copyright 2026 Synnax Labs, Inc.
//
// Use of this software is governed by the Business Source License included in the file
// licenses/BSL.txt.
//
// As of the Change Date specified in that file, in accordance with the Business Source
// License, use of this software will be governed by the Apache License, Version 2.0,
// included in the file licenses/APL.txt.

// Code generated by oracle. DO NOT EDIT.

package v1

import "github.com/synnaxlabs/x/encoding/orc"

// EncodeOrc writes the value to w in the Orc binary format.
func (bv Band) EncodeOrc(w *orc.Writer) error {
	w.String(bv.Key)
	w.Float64(float64(bv.Threshold))
	if err := bv.Color.EncodeOrc(w); err != nil {
		return err
	}
	w.Bool(bv.Flashing)
	return nil
}

// DecodeOrc reads the value from r in the Orc binary format.
func (bv *Band) DecodeOrc(r *orc.Reader) error {
	var err error
	if bv.Key, err = r.String(); err != nil {
		return err
	}
	if bv.Threshold, err = r.Float64(); err != nil {
		return err
	}
	if err = bv.Color.DecodeOrc(r); err != nil {
		return err
	}
	if bv.Flashing, err = r.Bool(); err != nil {
		return err
	}
	return nil
}

// EncodeOrc writes the value to w in the Orc binary format.
func (s Scale) EncodeOrc(w *orc.Writer) error {
	w.Bool(s.Bands != nil)
	if s.Bands != nil {
		w.Uint32(uint32(len(s.Bands)))
		for i := range s.Bands {
			if err := s.Bands[i].EncodeOrc(w); err != nil {
				return err
			}
		}
	}
	w.Bool(s.Smooth)
	return nil
}

// DecodeOrc reads the value from r in the Orc binary format.
func (s *Scale) DecodeOrc(r *orc.Reader) error {
	var err error
	{
		present, err := r.Bool()
		if err != nil {
			return err
		}
		if present {
			n, err := r.CollectionLen()
			if err != nil {
				return err
			}
			s.Bands = make([]Band, n)
			for i := range s.Bands {
				if err = s.Bands[i].DecodeOrc(r); err != nil {
					return err
				}
			}
		}
	}
	if s.Smooth, err = r.Bool(); err != nil {
		return err
	}
	return nil
}
