// Copyright 2026 Synnax Labs, Inc.
//
// Use of this software is governed by the Business Source License included in the file
// licenses/BSL.txt.
//
// As of the Change Date specified in that file, in accordance with the Business Source
// License, use of this software will be governed by the Apache License, Version 2.0,
// included in the file licenses/APL.txt.

package pb

import (
	"strings"
	"text/template"
)

var templateFuncs = template.FuncMap{
	"join": strings.Join,
	"needsSemicolon": func(s string) bool {
		trimmed := strings.TrimSpace(s)
		if len(trimmed) == 0 {
			return true
		}
		lastChar := trimmed[len(trimmed)-1]
		return lastChar != '}' && lastChar != ';'
	},
	"lbrace": func() string { return "{" },
}

var protoTemplate = template.Must(
	template.New("cpp-pb-proto").
		Funcs(templateFuncs).
		Parse(`// Code generated by oracle. DO NOT EDIT.

#pragma once
{{- if .HasIncludes}}

{{range .SystemIncludes -}}
#include <{{.}}>
{{end -}}
{{if .SystemIncludes}}
{{end -}}
{{range .InternalIncludes -}}
#include "{{.}}"
{{end}}
{{- end}}
namespace {{.Namespace}} {
{{- range .EnumTranslators}}
{{$enum := .}}

inline std::pair<{{.PBNamespace}}::{{.Name}}, x::errors::Error> {{.FuncName}}_to_pb(const std::string& cpp) {
    static const std::unordered_map<std::string, {{.PBNamespace}}::{{.Name}}> kMap = {
{{- range .Values}}
        {{lbrace}}{{.CppValue}}, {{$enum.PBNamespace}}::{{.PBValue}}},
{{- end}}
    };
    auto it = kMap.find(cpp);
    if (it == kMap.end()) return {{lbrace}}{{lbrace}}}, x::errors::Error("unrecognized {{.Name}} value: " + cpp)};
    return {it->second, x::errors::NIL};
}

inline std::pair<std::string, x::errors::Error> {{.FuncName}}_from_pb({{.PBNamespace}}::{{.Name}} pb) {
    switch (pb) {
{{- range .Values}}
    case {{$enum.PBNamespace}}::{{.PBValue}}: return {{lbrace}}{{.CppValue}}, x::errors::NIL};
{{- end}}
    default: return {{lbrace}}"", x::errors::Error("unrecognized {{.Name}} protobuf value")};
    }
}
{{- end}}
{{- range .Translators}}
{{- if .IsGeneric}}

template <typename {{.TypeParamNames}}>
inline std::pair<{{.PBNamespace}}::{{.PBName}}, x::errors::Error> {{.CppName}}<{{.TypeParamNames}}>::to_proto() const {
    {{.PBNamespace}}::{{.PBName}} pb;
{{- range .Fields}}
{{- if .IsGenericField}}
    if constexpr (std::is_same_v<{{.TypeParamName}}, x::json::json>) {
        {{.ForwardJSONExpr}}{{if needsSemicolon .ForwardJSONExpr}};{{end}}
    } else {
        {{.ForwardExpr}}{{if needsSemicolon .ForwardExpr}};{{end}}
    }
{{- else}}
    {{.ForwardExpr}}{{if needsSemicolon .ForwardExpr}};{{end}}
{{- end}}
{{- end}}
    return {pb, x::errors::NIL};
}

template <typename {{.TypeParamNames}}>
inline std::pair<{{.CppName}}<{{.TypeParamNames}}>, x::errors::Error> {{.CppName}}<{{.TypeParamNames}}>::from_proto(
    const {{.PBNamespace}}::{{.PBName}}& pb
) {
    {{.CppName}}<{{.TypeParamNames}}> cpp;
{{- range .Fields}}
{{- if .IsGenericField}}
    if constexpr (std::is_same_v<{{.TypeParamName}}, x::json::json>) {
        {{.BackwardJSONExpr}}{{if needsSemicolon .BackwardJSONExpr}};{{end}}
    } else {
        {{.BackwardExpr}}{{if needsSemicolon .BackwardExpr}};{{end}}
    }
{{- else}}
    {{.BackwardExpr}}{{if needsSemicolon .BackwardExpr}};{{end}}
{{- end}}
{{- end}}
    return {cpp, x::errors::NIL};
}
{{- else if .HasExtends}}

inline std::pair<{{.PBNamespace}}::{{.PBName}}, x::errors::Error> {{.CppName}}::to_proto() const {
    {{.PBNamespace}}::{{.PBName}} pb;
{{- range .AllFields}}
    {{.ForwardExpr}}{{if needsSemicolon .ForwardExpr}};{{end}}
{{- end}}
    return {pb, x::errors::NIL};
}

inline std::pair<{{.CppName}}, x::errors::Error> {{.CppName}}::from_proto(
    const {{.PBNamespace}}::{{.PBName}}& pb
) {
    {{.CppName}} cpp;
{{- range .AllFields}}
    {{.BackwardExpr}}{{if needsSemicolon .BackwardExpr}};{{end}}
{{- end}}
    return {cpp, x::errors::NIL};
}
{{- else}}

inline std::pair<{{.PBNamespace}}::{{.PBName}}, x::errors::Error> {{.CppName}}::to_proto() const {
    {{.PBNamespace}}::{{.PBName}} pb;
{{- range .Fields}}
    {{.ForwardExpr}}{{if needsSemicolon .ForwardExpr}};{{end}}
{{- end}}
    return {pb, x::errors::NIL};
}

inline std::pair<{{.CppName}}, x::errors::Error> {{.CppName}}::from_proto(
    const {{.PBNamespace}}::{{.PBName}}& pb
) {
    {{.CppName}} cpp;
{{- range .Fields}}
    {{.BackwardExpr}}{{if needsSemicolon .BackwardExpr}};{{end}}
{{- end}}
    return {cpp, x::errors::NIL};
}
{{- end}}
{{- end}}
{{- range .ArrayWrappers}}

inline std::pair<{{.PBNamespace}}::{{.PBName}}, x::errors::Error> {{.CppName}}::to_proto() const {
    {{.PBNamespace}}::{{.PBName}} pb;
{{- if .ElementNeedsConvert}}
    for (const auto& item : *this) {
        auto [v, err] = item.to_proto();
        if (err) return {{lbrace}}{{lbrace}}}, err};
        *pb.add_values() = v;
    }
{{- else}}
    for (const auto& item : *this) pb.add_values(item);
{{- end}}
    return {pb, x::errors::NIL};
}

inline std::pair<{{.CppName}}, x::errors::Error> {{.CppName}}::from_proto(
    const {{.PBNamespace}}::{{.PBName}}& pb
) {
    {{.CppName}} cpp;
{{- if .ElementNeedsConvert}}
    if (auto err = x::pb::from_proto_repeated<{{.ElementType}}>(cpp, pb.values())) return {{lbrace}}{{lbrace}}}, err};
{{- else}}
    for (const auto& item : pb.values()) cpp.push_back(item);
{{- end}}
    return {cpp, x::errors::NIL};
}
{{- end}}
{{- range .UnionTranslators}}
{{- $u := .}}

inline std::pair<{{.PBType}}, x::errors::Error> to_proto(const {{.CppName}}& value) {
    {{.PBType}} pb;
    const auto visit_err = std::visit([&pb](const auto& v) -> x::errors::Error {
        using V = std::decay_t<decltype(v)>;
        auto [inner, err] = v.to_proto();
        if (err) return err;
{{- range $u.Bases}}
        {
            auto [base, base_err] = static_cast<const {{.CppType}}&>(v).to_proto();
            if (base_err) return base_err;
            *pb.mutable_{{.PBAccessor}}() = base;
        }
{{- end}}
{{- range $i, $v := $u.Variants}}
        {{if $i}}else {{end}}if constexpr (std::is_same_v<V, {{$v.TypeName}}>) *pb.mutable_{{$v.PBAccessor}}() = inner;
{{- end}}
        return x::errors::NIL;
    }, value);
    return {pb, visit_err};
}

inline std::pair<{{.CppName}}, x::errors::Error> {{.SnakeName}}_from_proto(const {{.PBType}}& pb) {
    switch (pb.variant_case()) {
{{- range $u.Variants}}
    case {{$u.PBType}}::k{{.CaseName}}: {
        auto [v, err] = {{.TypeName}}::from_proto(pb.{{.PBAccessor}}());
        if (err) return {{lbrace}}{{lbrace}}}, err};
{{- range $u.Bases}}
        {
            auto [base, base_err] = {{.CppType}}::from_proto(pb.{{.PBAccessor}}());
            if (base_err) return {{lbrace}}{{lbrace}}}, base_err};
            static_cast<{{.CppType}}&>(v) = base;
        }
{{- end}}
        return {v, x::errors::NIL};
    }
{{- end}}
    default:
        return {{lbrace}}{{lbrace}}}, x::errors::Error(x::errors::VALIDATION, "{{.CppName}}: no variant set")};
    }
}
{{- end}}

}
`),
)
