# Copyright 2026 Synnax Labs, Inc.
#
# Use of this software is governed by the Business Source License included in the file
# licenses/BSL.txt.
#
# As of the Change Date specified in that file, in accordance with the Business Source
# License, use of this software will be governed by the Apache License, Version 2.0,
# included in the file licenses/APL.txt.

load("@rules_cc//cc:cc_binary.bzl", "cc_binary")
load("@rules_cc//cc:cc_library.bzl", "cc_library")

cc_library(
    name = "mock",
    hdrs = ["server.h"],
    visibility = ["//visibility:public"],
    deps = [
        "//driver/opc/types",
        "//vendor/open62541",
        "@abseil-cpp//absl/log",
    ],
)

cc_binary(
    name = "opc_mock_server",
    srcs = ["main.cpp"],
    deps = [
        ":mock",
        "//driver/opc/testutil",
        "//vendor/open62541",
        "@abseil-cpp//absl/log",
    ],
)
