// Code generated by oracle. DO NOT EDIT.

package compiler

type Output struct {
	WASM              []byte            `json:"wasm" msgpack:"wasm"`
	OutputMemoryBases map[string]uint32 `json:"output_memory_bases" msgpack:"output_memory_bases"`
}
