// Copyright 2026 Synnax Labs, Inc.
//
// Use of this software is governed by the Business Source License included in the file
// licenses/BSL.txt.
//
// As of the Change Date specified in that file, in accordance with the Business Source
// License, use of this software will be governed by the Apache License, Version 2.0,
// included in the file licenses/APL.txt.

// Code generated by Oracle. DO NOT EDIT.

import { array, filter } from "@synnaxlabs/x";
import { z } from "zod";

import { baseZ } from "@/ranger/types.gen";

export interface RangeFilterNode {
  name?: filter.StringFilter;
  and?: RangeFilterNode[];
  or?: RangeFilterNode[];
  not?: RangeFilterNode;
}

export const rangeFilterNodeZ: z.ZodType<RangeFilterNode> = z.lazy(() =>
  z.object({
    name: filter.stringFilterZ.optional(),
    and: z.array(rangeFilterNodeZ).optional(),
    or: z.array(rangeFilterNodeZ).optional(),
    not: rangeFilterNodeZ.optional(),
  }),
);

export interface RangeFilter {
  name?: string | string[] | RegExp | filter.OpNode<string>;
}

export type RangeFilterArg = RangeFilter | filter.Node<"range">;

export const RANGE_FILTER_DESCRIPTOR: filter.Descriptor = {
  entity: "range",
  fields: {
    name: "string",
  },
  orderFields: {},
};

export const IDENTIFYING_FIELDS: ReadonlySet<string> = new Set([]);

export interface RangeRetrieveOptions {
  limit?: number;
  offset?: number;
  searchTerm?: string;
}

export type RangeRetrieveArg =
  | (RangeFilter & RangeRetrieveOptions)
  | filter.Node<"range">;

export const retrieveReqZ = z.object({
  where: rangeFilterNodeZ.optional(),
  searchTerm: z.string().optional(),
  limit: z.int().optional(),
  offset: z.int().optional(),
});

export const retrieveResZ = z.object({
  ranges: array.nullishToEmpty(baseZ),
});

type TwoOrMore = [RangeFilterArg, RangeFilterArg, ...RangeFilterArg[]];

export const or = (...args: TwoOrMore): filter.Node<"range"> => ({
  kind: "or",
  children: args,
  [filter.NODE_TAG]: "range",
});

export const and = (...args: TwoOrMore): filter.Node<"range"> => ({
  kind: "and",
  children: args,
  [filter.NODE_TAG]: "range",
});

export const not = (arg: RangeFilterArg): filter.Node<"range"> => ({
  kind: "not",
  children: [arg],
  [filter.NODE_TAG]: "range",
});

export const eq = <T>(value: T): filter.OpNode<T, "eq"> => ({
  value,
  [filter.OP_TAG]: "eq",
});

export const gt = <T>(value: T): filter.OpNode<T, "gt"> => ({
  value,
  [filter.OP_TAG]: "gt",
});

export const lt = <T>(value: T): filter.OpNode<T, "lt"> => ({
  value,
  [filter.OP_TAG]: "lt",
});

export const gte = <T>(value: T): filter.OpNode<T, "gte"> => ({
  value,
  [filter.OP_TAG]: "gte",
});

export const lte = <T>(value: T): filter.OpNode<T, "lte"> => ({
  value,
  [filter.OP_TAG]: "lte",
});

export const between = <T>(lo: T, hi: T): filter.OpNode<T, "between"> => ({
  value: [lo, hi] as const,
  [filter.OP_TAG]: "between",
});

export const toWire = (
  args: readonly filter.FilterArg[],
): filter.WireNode | undefined => filter.toWire(args, RANGE_FILTER_DESCRIPTOR);
