// Code generated by Oracle. DO NOT EDIT.

import { status, zod } from "@synnaxlabs/x";
import { z } from "zod";

import { ontology } from "@/ontology";

export const keyZ = zod.uint32Z;
export type Key = z.infer<typeof keyZ>;

export const statusDetailsZ = z.object({
  rack: zod.uint32Z,
});
export type StatusDetails = z.infer<typeof statusDetailsZ>;

export const statusZ = status.statusZ(statusDetailsZ);
export type Status = z.infer<typeof statusZ>;

export const payloadZ = z.object({
  key: keyZ,
  name: z.string().min(1, "Name is required"),
  status: statusZ.optional(),
});
export type Payload = z.infer<typeof payloadZ>;

export const newZ = z.object({
  key: keyZ.optional(),
  name: z.string().min(1, "Name is required"),
  status: statusZ.optional(),
});
export type New = z.input<typeof newZ>;

export const ontologyID = ontology.createIDFactory<Key>("rack");
export const TYPE_ONTOLOGY_ID = ontologyID(0);
