// Copyright 2026 Synnax Labs, Inc.
//
// Use of this software is governed by the Business Source License included in the file
// licenses/BSL.txt.
//
// As of the Change Date specified in that file, in accordance with the Business Source
// License, use of this software will be governed by the Apache License, Version 2.0,
// included in the file licenses/APL.txt.

// Code generated by oracle. DO NOT EDIT.

package v2

import (
	"context"

	"github.com/samber/lo"
	v1 "github.com/synnaxlabs/synnax/pkg/service/modbus/versions/v1"
	"github.com/synnaxlabs/x/errors"
)

func autoMigrateReadConfig(ctx context.Context, old v1.ReadConfig) (ReadConfig, error) {
	channels, err := lo.MapErr(old.Channels, func(v v1.ReadChannel, _ int) (ReadChannel, error) {
		return autoMigrateReadChannel(ctx, v)
	})
	if err != nil {
		return ReadConfig{}, err
	}
	return ReadConfig{
		ReadConfig: old.ReadConfig,
		Device:     old.Device,
		Channels:   channels,
	}, nil
}

func autoMigrateWriteConfig(ctx context.Context, old v1.WriteConfig) (WriteConfig, error) {
	channels, err := lo.MapErr(old.Channels, func(v v1.WriteChannel, _ int) (WriteChannel, error) {
		return autoMigrateWriteChannel(ctx, v)
	})
	if err != nil {
		return WriteConfig{}, err
	}
	return WriteConfig{
		WriteConfig: old.WriteConfig,
		Channels:    channels,
	}, nil
}

func autoMigrateCoilReadChannel(_ context.Context, old v1.CoilReadChannel) (CoilReadChannel, error) {
	return CoilReadChannel{
		BaseReadChannel: old.BaseReadChannel,
	}, nil
}

func autoMigrateDiscreteInputReadChannel(_ context.Context, old v1.DiscreteInputReadChannel) (DiscreteInputReadChannel, error) {
	return DiscreteInputReadChannel{
		BaseReadChannel: old.BaseReadChannel,
	}, nil
}

func autoMigrateHoldingRegisterReadChannel(ctx context.Context, old v1.HoldingRegisterReadChannel) (HoldingRegisterReadChannel, error) {
	registerValue, err := MigrateRegisterValue(ctx, old.RegisterValue)
	if err != nil {
		return HoldingRegisterReadChannel{}, err
	}
	return HoldingRegisterReadChannel{
		BaseReadChannel: old.BaseReadChannel,
		RegisterValue:   registerValue,
		StringLength:    old.StringLength,
	}, nil
}

func autoMigrateInputRegisterReadChannel(ctx context.Context, old v1.InputRegisterReadChannel) (InputRegisterReadChannel, error) {
	registerValue, err := MigrateRegisterValue(ctx, old.RegisterValue)
	if err != nil {
		return InputRegisterReadChannel{}, err
	}
	return InputRegisterReadChannel{
		BaseReadChannel: old.BaseReadChannel,
		RegisterValue:   registerValue,
		StringLength:    old.StringLength,
	}, nil
}

func autoMigrateReadChannel(ctx context.Context, old v1.ReadChannel) (ReadChannel, error) {
	switch v := old.Variant.(type) {
	case nil:
		return ReadChannel{}, nil
	case v1.CoilReadChannel:
		nv, err := autoMigrateCoilReadChannel(ctx, v)
		if err != nil {
			return ReadChannel{}, err
		}
		return ReadChannel{Variant: nv}, nil
	case v1.DiscreteInputReadChannel:
		nv, err := autoMigrateDiscreteInputReadChannel(ctx, v)
		if err != nil {
			return ReadChannel{}, err
		}
		return ReadChannel{Variant: nv}, nil
	case v1.HoldingRegisterReadChannel:
		nv, err := autoMigrateHoldingRegisterReadChannel(ctx, v)
		if err != nil {
			return ReadChannel{}, err
		}
		return ReadChannel{Variant: nv}, nil
	case v1.InputRegisterReadChannel:
		nv, err := autoMigrateInputRegisterReadChannel(ctx, v)
		if err != nil {
			return ReadChannel{}, err
		}
		return ReadChannel{Variant: nv}, nil
	default:
		return ReadChannel{}, errors.Newf("ReadChannel: unknown variant %T", v)
	}
}

func autoMigrateCoilWriteChannel(_ context.Context, old v1.CoilWriteChannel) (CoilWriteChannel, error) {
	return CoilWriteChannel{
		BaseWriteChannel: old.BaseWriteChannel,
	}, nil
}

func autoMigrateHoldingRegisterWriteChannel(ctx context.Context, old v1.HoldingRegisterWriteChannel) (HoldingRegisterWriteChannel, error) {
	registerValue, err := MigrateRegisterValue(ctx, old.RegisterValue)
	if err != nil {
		return HoldingRegisterWriteChannel{}, err
	}
	return HoldingRegisterWriteChannel{
		BaseWriteChannel: old.BaseWriteChannel,
		RegisterValue:    registerValue,
	}, nil
}

func autoMigrateWriteChannel(ctx context.Context, old v1.WriteChannel) (WriteChannel, error) {
	switch v := old.Variant.(type) {
	case nil:
		return WriteChannel{}, nil
	case v1.CoilWriteChannel:
		nv, err := autoMigrateCoilWriteChannel(ctx, v)
		if err != nil {
			return WriteChannel{}, err
		}
		return WriteChannel{Variant: nv}, nil
	case v1.HoldingRegisterWriteChannel:
		nv, err := autoMigrateHoldingRegisterWriteChannel(ctx, v)
		if err != nil {
			return WriteChannel{}, err
		}
		return WriteChannel{Variant: nv}, nil
	default:
		return WriteChannel{}, errors.Newf("WriteChannel: unknown variant %T", v)
	}
}

func autoMigrateRegisterValue(_ context.Context, old v1.RegisterValue) (RegisterValue, error) {
	return RegisterValue{
		DataType: old.DataType,
	}, nil
}
