# Copyright 2026 Synnax Labs, Inc.
#
# Use of this software is governed by the Business Source License included in the file
# licenses/BSL.txt.
#
# As of the Change Date specified in that file, in accordance with the Business Source
# License, use of this software will be governed by the Apache License, Version 2.0,
# included in the file licenses/APL.txt.

load("@rules_cc//cc:cc_library.bzl", "cc_library")
load("@rules_cc//cc:cc_test.bzl", "cc_test")

cc_library(
    name = "channel",
    srcs = ["channel.cpp"],
    hdrs = [
        "channel.h",
        "json.gen.h",
        "proto.gen.h",
        "types.gen.h",
    ],
    visibility = ["//visibility:public"],
    deps = [
        "//client/cpp/node",
        "//client/cpp/errors",
        "//client/cpp/ontology",
        "//client/cpp/status",
        "//core/pkg/service/status:status_grpc",
        "//core/pkg/transport/grpc:api_grpc",
        "//freighter/cpp:freighter",
        "//freighter/cpp/grpc",
        "//x/cpp/control",
        "//x/cpp/errors",
        "//x/cpp/json",
        "//x/cpp/pb",
        "//x/cpp/telem",
        "@grpc//:grpc++",
    ],
)

cc_test(
    name = "channel_test",
    srcs = ["channel_test.cpp"],
    deps = [
        ":channel",
        "//client/cpp:synnax",
        "//client/cpp/testutil",
        "//x/cpp/pb",
        "//x/cpp/test",
        "@googletest//:gtest_main",
    ],
)
