// Copyright 2026 Synnax Labs, Inc.
//
// Use of this software is governed by the Business Source License included in the file
// licenses/BSL.txt.
//
// As of the Change Date specified in that file, in accordance with the Business Source
// License, use of this software will be governed by the Apache License, Version 2.0,
// included in the file licenses/APL.txt.

// Code generated by oracle. DO NOT EDIT.

#pragma once

#include <type_traits>
#include <utility>

#include "client/cpp/channel/types.gen.h"
#include "x/cpp/errors/errors.h"

#include "core/pkg/distribution/channel/pb/channel.pb.h"

namespace synnax::channel {

inline ::distribution::channel::pb::OperationType
OperationTypeToPB(const std::string &cpp) {
    if (cpp == OPERATION_TYPE_MIN)
        return ::distribution::channel::pb::OPERATION_TYPE_MIN;
    if (cpp == OPERATION_TYPE_MAX)
        return ::distribution::channel::pb::OPERATION_TYPE_MAX;
    if (cpp == OPERATION_TYPE_AVG)
        return ::distribution::channel::pb::OPERATION_TYPE_AVG;
    if (cpp == OPERATION_TYPE_NONE)
        return ::distribution::channel::pb::OPERATION_TYPE_NONE;
    return ::distribution::channel::pb::OPERATION_TYPE_UNSPECIFIED;
}

inline std::string OperationTypeFromPB(::distribution::channel::pb::OperationType pb) {
    switch (pb) {
        case ::distribution::channel::pb::OPERATION_TYPE_MIN:
            return OPERATION_TYPE_MIN;
        case ::distribution::channel::pb::OPERATION_TYPE_MAX:
            return OPERATION_TYPE_MAX;
        case ::distribution::channel::pb::OPERATION_TYPE_AVG:
            return OPERATION_TYPE_AVG;
        case ::distribution::channel::pb::OPERATION_TYPE_NONE:
            return OPERATION_TYPE_NONE;
        default:
            return OPERATION_TYPE_MIN;
    }
}

inline ::distribution::channel::pb::Operation Operation::to_proto() const {
    ::distribution::channel::pb::Operation pb;
    pb.set_type(OperationTypeToPB(this->type));
    pb.set_reset_channel(static_cast<uint32_t>(this->reset_channel));
    pb.set_duration(this->duration.nanoseconds());
    return pb;
}

inline std::pair<Operation, x::errors::Error>
Operation::from_proto(const ::distribution::channel::pb::Operation &pb) {
    Operation cpp;
    cpp.type = OperationTypeFromPB(pb.type());
    cpp.reset_channel = Key(pb.reset_channel());
    cpp.duration = x::telem::TimeSpan(pb.duration());
    return {cpp, x::errors::NIL};
}

}
