import { Icon } from "@synnaxlabs/pluto";

import type { DiagramDef } from "@/components/stream/diagrams/types";

const VIEWBOX = "0 0 900 350";

export const CONVERSION_DIAGRAM: DiagramDef = {
  viewBox: VIEWBOX,
  nodes: [
    {
      id: "celsius",
      x: 150,
      y: 175,
      w: 140,
      h: 62,
      label: "celsius",
      icon: Icon.Channel,
    },
    {
      id: "compute",
      x: 450,
      y: 175,
      w: 140,
      h: 62,
      label: "× 9/5 + 32",
      icon: Icon.Calculation,
    },
    {
      id: "fahrenheit",
      x: 750,
      y: 175,
      w: 140,
      h: 62,
      label: "fahrenheit",
      icon: Icon.Value,
    },
  ],
  edges: [
    { from: "celsius", to: "compute" },
    { from: "compute", to: "fahrenheit" },
  ],
};

export const MIXTURE_DIAGRAM: DiagramDef = {
  viewBox: VIEWBOX,
  nodes: [
    {
      id: "ox",
      x: 150,
      y: 110,
      w: 140,
      h: 62,
      label: "ox_flow",
      icon: Icon.Channel,
    },
    {
      id: "fuel",
      x: 150,
      y: 240,
      w: 140,
      h: 62,
      label: "fuel_flow",
      icon: Icon.Channel,
    },
    {
      id: "compute",
      x: 450,
      y: 175,
      w: 140,
      h: 62,
      label: "÷",
      icon: Icon.Calculation,
    },
    {
      id: "ratio",
      x: 750,
      y: 175,
      w: 140,
      h: 62,
      label: "mix_ratio",
      icon: Icon.Value,
    },
  ],
  edges: [
    { from: "ox", to: "compute" },
    { from: "fuel", to: "compute" },
    { from: "compute", to: "ratio" },
  ],
};

export const ALARM_DIAGRAM: DiagramDef = {
  viewBox: VIEWBOX,
  nodes: [
    {
      id: "pressure",
      x: 150,
      y: 175,
      w: 140,
      h: 62,
      label: "pressure",
      icon: Icon.Channel,
    },
    {
      id: "decision",
      x: 450,
      y: 175,
      w: 140,
      h: 62,
      label: "> 750?",
      icon: Icon.Calculation,
    },
    {
      id: "alarm_on",
      x: 750,
      y: 95,
      w: 140,
      h: 62,
      label: "alarm",
      icon: Icon.Value,
    },
    {
      id: "alarm_off",
      x: 750,
      y: 255,
      w: 140,
      h: 62,
      label: "alarm",
      icon: Icon.Value,
    },
  ],
  edges: [
    { from: "pressure", to: "decision" },
    { from: "decision", to: "alarm_on" },
    { from: "decision", to: "alarm_off" },
  ],
};

export const MASSFLOW_DIAGRAM: DiagramDef = {
  viewBox: VIEWBOX,
  nodes: [
    {
      id: "upstream",
      x: 100,
      y: 65,
      w: 140,
      h: 62,
      label: "upstream_pt",
      icon: Icon.Channel,
    },
    {
      id: "downstream",
      x: 100,
      y: 175,
      w: 140,
      h: 62,
      label: "downstream_pt",
      icon: Icon.Channel,
    },
    {
      id: "ox_temp",
      x: 100,
      y: 285,
      w: 140,
      h: 62,
      label: "ox_temp",
      icon: Icon.Channel,
    },
    {
      id: "density",
      x: 350,
      y: 175,
      w: 140,
      h: 62,
      label: "fluids.density",
      icon: Icon.Calculation,
    },
    {
      id: "orifice",
      x: 570,
      y: 175,
      w: 140,
      h: 62,
      label: "fluids.orifice",
      icon: Icon.Calculation,
    },
    {
      id: "mass_flow",
      x: 790,
      y: 175,
      w: 140,
      h: 62,
      label: "mass_flow",
      icon: Icon.Value,
    },
  ],
  edges: [
    { from: "upstream", to: "density" },
    { from: "downstream", to: "density" },
    { from: "ox_temp", to: "density" },
    { from: "density", to: "orifice" },
    { from: "orifice", to: "mass_flow" },
  ],
};

export const VOTING_DIAGRAM: DiagramDef = {
  viewBox: VIEWBOX,
  nodes: [
    {
      id: "p1",
      x: 130,
      y: 65,
      w: 140,
      h: 62,
      label: "press_1",
      icon: Icon.Channel,
    },
    {
      id: "p2",
      x: 130,
      y: 175,
      w: 140,
      h: 62,
      label: "press_2",
      icon: Icon.Channel,
    },
    {
      id: "p3",
      x: 130,
      y: 285,
      w: 140,
      h: 62,
      label: "press_3",
      icon: Icon.Channel,
    },
    {
      id: "vote",
      x: 430,
      y: 175,
      w: 140,
      h: 62,
      label: "VOTE",
      icon: Icon.Calculation,
    },
    {
      id: "trusted",
      x: 700,
      y: 175,
      w: 140,
      h: 62,
      label: "trusted",
      icon: Icon.Value,
    },
  ],
  edges: [
    { from: "p1", to: "vote" },
    { from: "p2", to: "vote" },
    { from: "p3", to: "vote" },
    { from: "vote", to: "trusted" },
  ],
};

export const AUTOMATE_ALARM_DIAGRAM: DiagramDef = {
  viewBox: VIEWBOX,
  nodes: [
    {
      id: "sensor",
      x: 100,
      y: 175,
      w: 140,
      h: 62,
      label: "press_pt",
      icon: Icon.Channel,
    },
    {
      id: "check",
      x: 310,
      y: 175,
      w: 140,
      h: 62,
      label: "check",
      icon: Icon.Calculation,
    },
    {
      id: "stable",
      x: 520,
      y: 175,
      w: 140,
      h: 62,
      label: "stable_for",
      icon: Icon.Calculation,
    },
    {
      id: "warning",
      x: 770,
      y: 95,
      w: 140,
      h: 62,
      label: "warning",
      icon: Icon.Value,
    },
    {
      id: "nominal",
      x: 770,
      y: 255,
      w: 140,
      h: 62,
      label: "nominal",
      icon: Icon.Value,
    },
  ],
  edges: [
    { from: "sensor", to: "check" },
    { from: "check", to: "stable" },
    { from: "stable", to: "warning" },
    { from: "stable", to: "nominal" },
  ],
};

export const FFT_DIAGRAM: DiagramDef = {
  viewBox: VIEWBOX,
  nodes: [
    {
      id: "accel",
      x: 100,
      y: 110,
      w: 140,
      h: 62,
      label: "accel_x",
      icon: Icon.Channel,
    },
    {
      id: "window",
      x: 330,
      y: 110,
      w: 140,
      h: 62,
      label: "series.last",
      icon: Icon.Calculation,
    },
    {
      id: "fft",
      x: 560,
      y: 110,
      w: 140,
      h: 62,
      label: "math.fft",
      icon: Icon.Calculation,
    },
    {
      id: "freqs",
      x: 560,
      y: 250,
      w: 140,
      h: 62,
      label: "fft_freqs",
      icon: Icon.Calculation,
    },
    {
      id: "freq",
      x: 790,
      y: 175,
      w: 140,
      h: 62,
      label: "peak_freq",
      icon: Icon.Value,
    },
  ],
  edges: [
    { from: "accel", to: "window" },
    { from: "window", to: "fft" },
    { from: "fft", to: "freq" },
    { from: "freqs", to: "freq" },
  ],
};
