# Copyright 2026 Synnax Labs, Inc.
#
# Use of this software is governed by the Business Source License included in the file
# licenses/BSL.txt.
#
# As of the Change Date specified in that file, in accordance with the Business Source
# License, use of this software will be governed by the Apache License, Version 2.0,
# included in the file licenses/APL.txt.

load("@rules_cc//cc:cc_library.bzl", "cc_library")
load("@rules_cc//cc:cc_test.bzl", "cc_test")

cc_library(
    name = "connection",
    srcs = [
        "connection.cpp",
        "pool.cpp",
    ],
    hdrs = [
        "connection.h",
    ],
    visibility = ["//visibility:public"],
    deps = [
        "//driver/errors",
        "//driver/opc/errors",
        "//driver/task",
        "//vendor/mbedtls",
        "//vendor/open62541",
        "//x/cpp/errors",
        "//x/cpp/json",
        "@abseil-cpp//absl/log",
        "@nlohmann_json//:json",
    ],
)

cc_test(
    name = "connection_test",
    srcs = [
        "connection_test.cpp",
        "keepalive_test.cpp",
        "pool_test.cpp",
    ],
    deps = [
        ":connection",
        "//driver/opc/mock",
        "//driver/opc/testutil",
        "//x/cpp/test",
        "@googletest//:gtest_main",
    ],
)
