// Copyright 2026 Synnax Labs, Inc.
//
// Use of this software is governed by the Business Source License included in the file
// licenses/BSL.txt.
//
// As of the Change Date specified in that file, in accordance with the Business Source
// License, use of this software will be governed by the Apache License, Version 2.0,
// included in the file licenses/APL.txt.

// Code generated by oracle. DO NOT EDIT.

package v1

import (
	channel "github.com/synnaxlabs/synnax/pkg/service/channel/versions/v0"
	device "github.com/synnaxlabs/synnax/pkg/service/device/versions/v1"
	config "github.com/synnaxlabs/synnax/pkg/service/task/config/versions/v2"
	telem "github.com/synnaxlabs/x/telem/versions/v0"
)

// BaseChannel carries the fields every OPC UA channel shares.
type BaseChannel struct {
	// Key uniquely identifies the channel within the task.
	Key string `json:"key" msgpack:"key"`
	// Name is the human-readable channel name.
	Name string `json:"name" msgpack:"name"`
	// Disabled is true when the channel is excluded from the task.
	Disabled bool `json:"disabled" msgpack:"disabled"`
	// NodeID is the OPC UA node id the channel is bound to.
	NodeID string `json:"node_id" msgpack:"node_id"`
	// NodeName is the browse name of the OPC UA node.
	NodeName string `json:"node_name" msgpack:"node_name"`
	// DataType is the data type of the Synnax channel.
	DataType telem.DataType `json:"data_type" msgpack:"data_type"`
}

// ApplyDefaults fills zero-valued fields with their schema-declared defaults.
func (b *BaseChannel) ApplyDefaults() {
	if b.DataType == "" {
		b.DataType = "float32"
	}
}

// ReadChannel is a single OPC UA node the task reads from.
type ReadChannel struct {
	BaseChannel
	// Channel is the Synnax channel that samples are written to.
	Channel channel.Key `json:"channel" msgpack:"channel"`
	// UseAsIndex is true when the channel's Synnax channel is the task's index.
	UseAsIndex bool `json:"use_as_index" msgpack:"use_as_index"`
}

// ApplyDefaults fills zero-valued fields with their schema-declared defaults.
func (r *ReadChannel) ApplyDefaults() {
	r.BaseChannel.ApplyDefaults()
}

// WriteChannel is a single OPC UA node the task drives.
type WriteChannel struct {
	BaseChannel
	// CmdChannel is the Synnax channel commands are read from.
	CmdChannel channel.Key `json:"cmd_channel" msgpack:"cmd_channel"`
}

// ApplyDefaults fills zero-valued fields with their schema-declared defaults.
func (w *WriteChannel) ApplyDefaults() {
	w.BaseChannel.ApplyDefaults()
}

// ReadConfig configures an OPC UA read task.
type ReadConfig struct {
	config.BaseRead
	// Device is the key of the device representing the OPC UA server.
	Device device.Key `json:"device" msgpack:"device"`
	// ArrayMode is true when each read returns an array of samples per node.
	ArrayMode bool `json:"array_mode" msgpack:"array_mode"`
	// ArraySize is the number of samples in each array when array_mode is true.
	ArraySize int32 `json:"array_size" msgpack:"array_size"`
	// Channels are the OPC UA nodes the task acquires.
	Channels []ReadChannel `json:"channels,omitzero" msgpack:"channels,omitzero"`
}

// ApplyDefaults fills zero-valued fields with their schema-declared defaults.
func (r *ReadConfig) ApplyDefaults() {
	if r.SampleRate == 0 {
		r.SampleRate = 50
	}
	if r.StreamRate == 0 {
		r.StreamRate = 25
	}
	if r.ArraySize == 0 {
		r.ArraySize = 1
	}
	r.BaseRead.ApplyDefaults()
	for i := range r.Channels {
		r.Channels[i].ApplyDefaults()
	}
}

// WriteConfig configures an OPC UA write task.
type WriteConfig struct {
	config.BaseWrite
	// Channels are the OPC UA nodes the task drives.
	Channels []WriteChannel `json:"channels,omitzero" msgpack:"channels,omitzero"`
}

// ApplyDefaults fills zero-valued fields with their schema-declared defaults.
func (w *WriteConfig) ApplyDefaults() {
	for i := range w.Channels {
		w.Channels[i].ApplyDefaults()
	}
}

// ScanConfig configures an OPC UA scan task.
type ScanConfig struct {
	config.BaseScan
}

// ApplyDefaults fills zero-valued fields with their schema-declared defaults.
func (s *ScanConfig) ApplyDefaults() {
	s.BaseScan.ApplyDefaults()
}
