// Code generated by oracle. DO NOT EDIT.

#pragma once

#include <vector>
#include <cstdint>
#include <unordered_map>
#include <string>
#include <utility>
#include "arc/cpp/ir/types.gen.h"
#include "x/cpp/json/json.h"
#include "x/cpp/errors/errors.h"
#include "arc/go/module/pb/module.pb.h"


namespace synnax::module {
struct Module {
    synnax::ir::Functions functions;
    synnax::ir::Nodes nodes;
    synnax::ir::Edges edges;
    synnax::ir::Strata strata;
    synnax::ir::Sequences sequences;
    std::vector<std::uint8_t> WASM;
    std::unordered_map<std::string, std::uint32_t> OutputMemoryBases;

    static Module parse(x::json::Parser parser);
    [[nodiscard]] x::json::json to_json() const;

    using proto_type = ::arc::module::pb::Module;
    [[nodiscard]] ::arc::module::pb::Module to_proto() const;
    static std::pair<Module, x::errors::Error> from_proto(const ::arc::module::pb::Module& pb);
};
}
