# Copyright 2026 Synnax Labs, Inc.
#
# Use of this software is governed by the Business Source License included in the file
# licenses/BSL.txt.
#
# As of the Change Date specified in that file, in accordance with the Business Source
# License, use of this software will be governed by the Apache License, Version 2.0,
# included in the file licenses/APL.txt.

load("@rules_cc//cc:cc_library.bzl", "cc_library")
load("@rules_cc//cc:cc_test.bzl", "cc_test")

cc_library(
    name = "ontology",
    srcs = [
        "id.cpp",
    ],
    hdrs = [
        "id.h",
        "proto.gen.h",
        "types.gen.h",
    ],
    visibility = ["//visibility:public"],
    deps = [
        "//core/pkg/service/ontology:ontology_grpc",
        "//x/cpp/errors",
        "//x/cpp/json",
        "//x/cpp/pb",
    ],
)

cc_test(
    name = "id_test",
    srcs = ["id_test.cpp"],
    deps = [
        ":ontology",
        "//x/cpp/test",
        "@googletest//:gtest_main",
    ],
)
