// Copyright 2026 Synnax Labs, Inc.
//
// Use of this software is governed by the Business Source License included in the file
// licenses/BSL.txt.
//
// As of the Change Date specified in that file, in accordance with the Business Source
// License, use of this software will be governed by the Apache License, Version 2.0,
// included in the file licenses/APL.txt.

// Code generated by oracle. DO NOT EDIT.

package v0_test

import (
	"testing"
	"uuid"

	. "github.com/onsi/ginkgo/v2"
	. "github.com/onsi/gomega"
	channel "github.com/synnaxlabs/synnax/pkg/service/channel/versions/v0"
	http "github.com/synnaxlabs/synnax/pkg/service/http/versions/v2"
	"github.com/synnaxlabs/synnax/pkg/service/kafka/versions/v0"
	"github.com/synnaxlabs/x/encoding/orc"
	telem "github.com/synnaxlabs/x/telem/versions/v0"
	"github.com/synnaxlabs/x/testutil"
)

var _ = Describe("Codec", func() {
	Describe("ReadConfig", func() {
		DescribeTable("should round-trip encode and decode",
			func(original v0.ReadConfig) {
				w := orc.NewWriter(0)
				Expect(original.EncodeOrc(w)).To(Succeed())
				var decoded v0.ReadConfig
				r := orc.NewReader(nil)
				r.ResetBytes(w.Bytes())
				Expect(decoded.DecodeOrc(r)).To(Succeed())
				Expect(decoded).To(Equal(original))
			},
			Entry("fully populated", v0.ReadConfig{
				Key:                uuid.MustParse("a1b2c3d4-e5f6-7890-abcd-ef1234567801"),
				AutoStart:          false,
				DataSavingDisabled: true,
				Device:             "test_4",
				Topic:              "test_5",
				Group:              "test_6",
				StartOffset:        v0.StartOffset("latest"),
				Fields: []v0.ReadField{
					{
						Key:        "test_9",
						Disabled:   false,
						Name:       "test_11",
						Channel:    channel.Key(13),
						Pointer:    "test_13",
						DataType:   telem.DataType("test_14"),
						TimeFormat: new(http.TimeFormat("iso8601")),
						EnumValues: []http.EnumEntry{{Label: "test_17", Value: 18.5}},
						RecordKey:  "test_19",
					},
				},
			}),
			Entry("zero values", v0.ReadConfig{
				Key:                uuid.Nil(),
				AutoStart:          false,
				DataSavingDisabled: false,
				Device:             "",
				Topic:              "",
				Group:              "",
				StartOffset:        v0.StartOffset(""),
				Fields:             []v0.ReadField{},
			}),
			Entry("empty collections", v0.ReadConfig{
				Key:                uuid.MustParse("a1b2c3d4-e5f6-7890-abcd-ef1234567801"),
				AutoStart:          false,
				DataSavingDisabled: true,
				Device:             "test_4",
				Topic:              "test_5",
				Group:              "test_6",
				StartOffset:        v0.StartOffset("latest"),
				Fields:             []v0.ReadField{},
			}),
		)
	})
	Describe("ReadField", func() {
		DescribeTable("should round-trip encode and decode",
			func(original v0.ReadField) {
				w := orc.NewWriter(0)
				Expect(original.EncodeOrc(w)).To(Succeed())
				var decoded v0.ReadField
				r := orc.NewReader(nil)
				r.ResetBytes(w.Bytes())
				Expect(decoded.DecodeOrc(r)).To(Succeed())
				Expect(decoded).To(Equal(original))
			},
			Entry("fully populated", v0.ReadField{
				Key:        "test_1",
				Disabled:   false,
				Name:       "test_3",
				Channel:    channel.Key(5),
				Pointer:    "test_5",
				DataType:   telem.DataType("test_6"),
				TimeFormat: new(http.TimeFormat("iso8601")),
				EnumValues: []http.EnumEntry{{Label: "test_9", Value: 10.5}},
				RecordKey:  "test_11",
			}),
			Entry("zero values", v0.ReadField{
				Key:        "",
				Disabled:   false,
				Name:       "",
				Channel:    channel.Key(0),
				Pointer:    "",
				DataType:   telem.DataType(""),
				TimeFormat: nil,
				EnumValues: []http.EnumEntry{},
				RecordKey:  "",
			}),
			Entry("empty collections", v0.ReadField{
				Key:        "test_1",
				Disabled:   false,
				Name:       "test_3",
				Channel:    channel.Key(5),
				Pointer:    "test_5",
				DataType:   telem.DataType("test_6"),
				TimeFormat: new(http.TimeFormat("iso8601")),
				EnumValues: []http.EnumEntry{},
				RecordKey:  "test_9",
			}),
		)
	})
	Describe("Record", func() {
		DescribeTable("should round-trip encode and decode",
			func(original v0.Record) {
				w := orc.NewWriter(0)
				Expect(original.EncodeOrc(w)).To(Succeed())
				var decoded v0.Record
				r := orc.NewReader(nil)
				r.ResetBytes(w.Bytes())
				Expect(decoded.DecodeOrc(r)).To(Succeed())
				Expect(decoded).To(Equal(original))
			},
			Entry("fully populated", v0.Record{
				ValuePointer:     "test_1",
				ChannelPointer:   "test_2",
				TimestampPointer: "test_3",
				TimeFormat:       http.TimeFormat("iso8601"),
				Fields: []http.WriteField{
					{Variant: http.StaticWriteField{
						BaseWriteField: http.BaseWriteField{Key: "test_6", Pointer: "test_7"},
						JSONType:       http.JSONType("number"),
						Value:          any(map[string]any{"key_9": "value_9"}),
					}},
				},
			}),
			Entry("zero values", v0.Record{
				ValuePointer:     "",
				ChannelPointer:   "",
				TimestampPointer: "",
				TimeFormat:       http.TimeFormat(""),
				Fields:           []http.WriteField{},
			}),
			Entry("empty collections", v0.Record{
				ValuePointer:     "test_1",
				ChannelPointer:   "test_2",
				TimestampPointer: "test_3",
				TimeFormat:       http.TimeFormat("iso8601"),
				Fields:           []http.WriteField{},
			}),
		)
	})
	Describe("ScanConfig", func() {
		DescribeTable("should round-trip encode and decode",
			func(original v0.ScanConfig) {
				w := orc.NewWriter(0)
				Expect(original.EncodeOrc(w)).To(Succeed())
				var decoded v0.ScanConfig
				r := orc.NewReader(nil)
				r.ResetBytes(w.Bytes())
				Expect(decoded.DecodeOrc(r)).To(Succeed())
				Expect(decoded).To(Equal(original))
			},
			Entry("fully populated", v0.ScanConfig{
				Key:      uuid.MustParse("a1b2c3d4-e5f6-7890-abcd-ef1234567801"),
				Rate:     telem.Rate(2.5),
				Disabled: true,
			}),
			Entry("zero values", v0.ScanConfig{
				Key:      uuid.Nil(),
				Rate:     telem.Rate(0),
				Disabled: false,
			}),
		)
	})
	Describe("WriteChannel", func() {
		DescribeTable("should round-trip encode and decode",
			func(original v0.WriteChannel) {
				w := orc.NewWriter(0)
				Expect(original.EncodeOrc(w)).To(Succeed())
				var decoded v0.WriteChannel
				r := orc.NewReader(nil)
				r.ResetBytes(w.Bytes())
				Expect(decoded.DecodeOrc(r)).To(Succeed())
				Expect(decoded).To(Equal(original))
			},
			Entry("fully populated", v0.WriteChannel{
				Key:        "test_1",
				Disabled:   false,
				Channel:    channel.Key(4),
				JSONType:   http.JSONType("number"),
				TimeFormat: new(http.TimeFormat("iso8601")),
				EnumValues: []http.EnumEntry{{Label: "test_7", Value: 8.5}},
			}),
			Entry("zero values", v0.WriteChannel{
				Key:        "",
				Disabled:   false,
				Channel:    channel.Key(0),
				JSONType:   http.JSONType(""),
				TimeFormat: nil,
				EnumValues: []http.EnumEntry{},
			}),
			Entry("empty collections", v0.WriteChannel{
				Key:        "test_1",
				Disabled:   false,
				Channel:    channel.Key(4),
				JSONType:   http.JSONType("number"),
				TimeFormat: new(http.TimeFormat("iso8601")),
				EnumValues: []http.EnumEntry{},
			}),
		)
	})
	Describe("WriteConfig", func() {
		DescribeTable("should round-trip encode and decode",
			func(original v0.WriteConfig) {
				w := orc.NewWriter(0)
				Expect(original.EncodeOrc(w)).To(Succeed())
				var decoded v0.WriteConfig
				r := orc.NewReader(nil)
				r.ResetBytes(w.Bytes())
				Expect(decoded.DecodeOrc(r)).To(Succeed())
				Expect(decoded).To(Equal(original))
			},
			Entry("fully populated", v0.WriteConfig{
				Key:       uuid.MustParse("a1b2c3d4-e5f6-7890-abcd-ef1234567801"),
				AutoStart: false,
				Device:    "test_3",
				Topic:     "test_4",
				RecordKey: v0.RecordKey("none"),
				Record: v0.Record{
					ValuePointer:     "test_7",
					ChannelPointer:   "test_8",
					TimestampPointer: "test_9",
					TimeFormat:       http.TimeFormat("iso8601"),
					Fields: []http.WriteField{
						{Variant: http.StaticWriteField{
							BaseWriteField: http.BaseWriteField{Key: "test_12", Pointer: "test_13"},
							JSONType:       http.JSONType("number"),
							Value:          any(map[string]any{"key_15": "value_15"}),
						}},
					},
				},
				Channels: []v0.WriteChannel{
					{
						Key:        "test_17",
						Disabled:   false,
						Channel:    channel.Key(20),
						JSONType:   http.JSONType("number"),
						TimeFormat: new(http.TimeFormat("iso8601")),
						EnumValues: []http.EnumEntry{{Label: "test_23", Value: 24.5}},
					},
				},
			}),
			Entry("zero values", v0.WriteConfig{
				Key:       uuid.Nil(),
				AutoStart: false,
				Device:    "",
				Topic:     "",
				RecordKey: v0.RecordKey(""),
				Record: v0.Record{
					ValuePointer:     "",
					ChannelPointer:   "",
					TimestampPointer: "",
					TimeFormat:       http.TimeFormat(""),
					Fields:           []http.WriteField{},
				},
				Channels: []v0.WriteChannel{},
			}),
			Entry("empty collections", v0.WriteConfig{
				Key:       uuid.MustParse("a1b2c3d4-e5f6-7890-abcd-ef1234567801"),
				AutoStart: false,
				Device:    "test_3",
				Topic:     "test_4",
				RecordKey: v0.RecordKey("none"),
				Record: v0.Record{
					ValuePointer:     "test_7",
					ChannelPointer:   "test_8",
					TimestampPointer: "test_9",
					TimeFormat:       http.TimeFormat("iso8601"),
					Fields:           []http.WriteField{},
				},
				Channels: []v0.WriteChannel{},
			}),
		)
	})
})

func BenchmarkEncodeDecodeReadConfig(b *testing.B) {
	seed := v0.ReadConfig{
		Key:                uuid.MustParse("a1b2c3d4-e5f6-7890-abcd-ef1234567801"),
		AutoStart:          false,
		DataSavingDisabled: true,
		Device:             "test_4",
		Topic:              "test_5",
		Group:              "test_6",
		StartOffset:        v0.StartOffset("latest"),
		Fields: []v0.ReadField{
			{
				Key:        "test_9",
				Disabled:   false,
				Name:       "test_11",
				Channel:    channel.Key(13),
				Pointer:    "test_13",
				DataType:   telem.DataType("test_14"),
				TimeFormat: new(http.TimeFormat("iso8601")),
				EnumValues: []http.EnumEntry{{Label: "test_17", Value: 18.5}},
				RecordKey:  "test_19",
			},
		},
	}
	w := orc.NewWriter(0)
	r := orc.NewReader(nil)
	for b.Loop() {
		w.Reset()
		if err := seed.EncodeOrc(w); err != nil {
			b.Fatal(err)
		}
		var decoded v0.ReadConfig
		r.ResetBytes(w.Bytes())
		if err := decoded.DecodeOrc(r); err != nil {
			b.Fatal(err)
		}
	}
}

func BenchmarkEncodeDecodeReadField(b *testing.B) {
	seed := v0.ReadField{
		Key:        "test_1",
		Disabled:   false,
		Name:       "test_3",
		Channel:    channel.Key(5),
		Pointer:    "test_5",
		DataType:   telem.DataType("test_6"),
		TimeFormat: new(http.TimeFormat("iso8601")),
		EnumValues: []http.EnumEntry{{Label: "test_9", Value: 10.5}},
		RecordKey:  "test_11",
	}
	w := orc.NewWriter(0)
	r := orc.NewReader(nil)
	for b.Loop() {
		w.Reset()
		if err := seed.EncodeOrc(w); err != nil {
			b.Fatal(err)
		}
		var decoded v0.ReadField
		r.ResetBytes(w.Bytes())
		if err := decoded.DecodeOrc(r); err != nil {
			b.Fatal(err)
		}
	}
}

func BenchmarkEncodeDecodeRecord(b *testing.B) {
	seed := v0.Record{
		ValuePointer:     "test_1",
		ChannelPointer:   "test_2",
		TimestampPointer: "test_3",
		TimeFormat:       http.TimeFormat("iso8601"),
		Fields: []http.WriteField{
			{Variant: http.StaticWriteField{
				BaseWriteField: http.BaseWriteField{Key: "test_6", Pointer: "test_7"},
				JSONType:       http.JSONType("number"),
				Value:          any(map[string]any{"key_9": "value_9"}),
			}},
		},
	}
	w := orc.NewWriter(0)
	r := orc.NewReader(nil)
	for b.Loop() {
		w.Reset()
		if err := seed.EncodeOrc(w); err != nil {
			b.Fatal(err)
		}
		var decoded v0.Record
		r.ResetBytes(w.Bytes())
		if err := decoded.DecodeOrc(r); err != nil {
			b.Fatal(err)
		}
	}
}

func BenchmarkEncodeDecodeScanConfig(b *testing.B) {
	seed := v0.ScanConfig{
		Key:      uuid.MustParse("a1b2c3d4-e5f6-7890-abcd-ef1234567801"),
		Rate:     telem.Rate(2.5),
		Disabled: true,
	}
	w := orc.NewWriter(0)
	r := orc.NewReader(nil)
	for b.Loop() {
		w.Reset()
		if err := seed.EncodeOrc(w); err != nil {
			b.Fatal(err)
		}
		var decoded v0.ScanConfig
		r.ResetBytes(w.Bytes())
		if err := decoded.DecodeOrc(r); err != nil {
			b.Fatal(err)
		}
	}
}

func BenchmarkEncodeDecodeWriteChannel(b *testing.B) {
	seed := v0.WriteChannel{
		Key:        "test_1",
		Disabled:   false,
		Channel:    channel.Key(4),
		JSONType:   http.JSONType("number"),
		TimeFormat: new(http.TimeFormat("iso8601")),
		EnumValues: []http.EnumEntry{{Label: "test_7", Value: 8.5}},
	}
	w := orc.NewWriter(0)
	r := orc.NewReader(nil)
	for b.Loop() {
		w.Reset()
		if err := seed.EncodeOrc(w); err != nil {
			b.Fatal(err)
		}
		var decoded v0.WriteChannel
		r.ResetBytes(w.Bytes())
		if err := decoded.DecodeOrc(r); err != nil {
			b.Fatal(err)
		}
	}
}

func BenchmarkEncodeDecodeWriteConfig(b *testing.B) {
	seed := v0.WriteConfig{
		Key:       uuid.MustParse("a1b2c3d4-e5f6-7890-abcd-ef1234567801"),
		AutoStart: false,
		Device:    "test_3",
		Topic:     "test_4",
		RecordKey: v0.RecordKey("none"),
		Record: v0.Record{
			ValuePointer:     "test_7",
			ChannelPointer:   "test_8",
			TimestampPointer: "test_9",
			TimeFormat:       http.TimeFormat("iso8601"),
			Fields: []http.WriteField{
				{Variant: http.StaticWriteField{
					BaseWriteField: http.BaseWriteField{Key: "test_12", Pointer: "test_13"},
					JSONType:       http.JSONType("number"),
					Value:          any(map[string]any{"key_15": "value_15"}),
				}},
			},
		},
		Channels: []v0.WriteChannel{
			{
				Key:        "test_17",
				Disabled:   false,
				Channel:    channel.Key(20),
				JSONType:   http.JSONType("number"),
				TimeFormat: new(http.TimeFormat("iso8601")),
				EnumValues: []http.EnumEntry{{Label: "test_23", Value: 24.5}},
			},
		},
	}
	w := orc.NewWriter(0)
	r := orc.NewReader(nil)
	for b.Loop() {
		w.Reset()
		if err := seed.EncodeOrc(w); err != nil {
			b.Fatal(err)
		}
		var decoded v0.WriteConfig
		r.ResetBytes(w.Bytes())
		if err := decoded.DecodeOrc(r); err != nil {
			b.Fatal(err)
		}
	}
}

func FuzzDecodeReadConfig(f *testing.F) {
	{
		seed := v0.ReadConfig{
			Key:                uuid.MustParse("a1b2c3d4-e5f6-7890-abcd-ef1234567801"),
			AutoStart:          false,
			DataSavingDisabled: true,
			Device:             "test_4",
			Topic:              "test_5",
			Group:              "test_6",
			StartOffset:        v0.StartOffset("latest"),
			Fields: []v0.ReadField{
				{
					Key:        "test_9",
					Disabled:   false,
					Name:       "test_11",
					Channel:    channel.Key(13),
					Pointer:    "test_13",
					DataType:   telem.DataType("test_14"),
					TimeFormat: new(http.TimeFormat("iso8601")),
					EnumValues: []http.EnumEntry{{Label: "test_17", Value: 18.5}},
					RecordKey:  "test_19",
				},
			},
		}
		w := orc.NewWriter(0)
		if err := seed.EncodeOrc(w); err != nil {
			f.Fatal(err)
		}
		f.Add(w.Bytes())
	}
	{
		seed := v0.ReadConfig{
			Key:                uuid.Nil(),
			AutoStart:          false,
			DataSavingDisabled: false,
			Device:             "",
			Topic:              "",
			Group:              "",
			StartOffset:        v0.StartOffset(""),
			Fields:             []v0.ReadField{},
		}
		w := orc.NewWriter(0)
		if err := seed.EncodeOrc(w); err != nil {
			f.Fatal(err)
		}
		f.Add(w.Bytes())
	}
	{
		seed := v0.ReadConfig{
			Key:                uuid.MustParse("a1b2c3d4-e5f6-7890-abcd-ef1234567801"),
			AutoStart:          false,
			DataSavingDisabled: true,
			Device:             "test_4",
			Topic:              "test_5",
			Group:              "test_6",
			StartOffset:        v0.StartOffset("latest"),
			Fields:             []v0.ReadField{},
		}
		w := orc.NewWriter(0)
		if err := seed.EncodeOrc(w); err != nil {
			f.Fatal(err)
		}
		f.Add(w.Bytes())
	}
	f.Fuzz(func(t *testing.T, data []byte) {
		var decoded v0.ReadConfig
		r := orc.NewReader(nil)
		r.ResetBytes(data)
		if err := decoded.DecodeOrc(r); err != nil {
			return
		}
		w1 := orc.NewWriter(len(data))
		if err := decoded.EncodeOrc(w1); err != nil {
			t.Fatalf("encode after successful decode failed: %v", err)
		}
		var redecoded v0.ReadConfig
		r.ResetBytes(w1.Bytes())
		if err := redecoded.DecodeOrc(r); err != nil {
			t.Fatalf("re-decode failed: %v", err)
		}
		if !testutil.DeepEqual(decoded, redecoded) {
			t.Fatal("round-trip mismatch: decoded value changed after an encode/decode cycle")
		}
	})
}

func FuzzDecodeReadField(f *testing.F) {
	{
		seed := v0.ReadField{
			Key:        "test_1",
			Disabled:   false,
			Name:       "test_3",
			Channel:    channel.Key(5),
			Pointer:    "test_5",
			DataType:   telem.DataType("test_6"),
			TimeFormat: new(http.TimeFormat("iso8601")),
			EnumValues: []http.EnumEntry{{Label: "test_9", Value: 10.5}},
			RecordKey:  "test_11",
		}
		w := orc.NewWriter(0)
		if err := seed.EncodeOrc(w); err != nil {
			f.Fatal(err)
		}
		f.Add(w.Bytes())
	}
	{
		seed := v0.ReadField{
			Key:        "",
			Disabled:   false,
			Name:       "",
			Channel:    channel.Key(0),
			Pointer:    "",
			DataType:   telem.DataType(""),
			TimeFormat: nil,
			EnumValues: []http.EnumEntry{},
			RecordKey:  "",
		}
		w := orc.NewWriter(0)
		if err := seed.EncodeOrc(w); err != nil {
			f.Fatal(err)
		}
		f.Add(w.Bytes())
	}
	{
		seed := v0.ReadField{
			Key:        "test_1",
			Disabled:   false,
			Name:       "test_3",
			Channel:    channel.Key(5),
			Pointer:    "test_5",
			DataType:   telem.DataType("test_6"),
			TimeFormat: new(http.TimeFormat("iso8601")),
			EnumValues: []http.EnumEntry{},
			RecordKey:  "test_9",
		}
		w := orc.NewWriter(0)
		if err := seed.EncodeOrc(w); err != nil {
			f.Fatal(err)
		}
		f.Add(w.Bytes())
	}
	f.Fuzz(func(t *testing.T, data []byte) {
		var decoded v0.ReadField
		r := orc.NewReader(nil)
		r.ResetBytes(data)
		if err := decoded.DecodeOrc(r); err != nil {
			return
		}
		w1 := orc.NewWriter(len(data))
		if err := decoded.EncodeOrc(w1); err != nil {
			t.Fatalf("encode after successful decode failed: %v", err)
		}
		var redecoded v0.ReadField
		r.ResetBytes(w1.Bytes())
		if err := redecoded.DecodeOrc(r); err != nil {
			t.Fatalf("re-decode failed: %v", err)
		}
		if !testutil.DeepEqual(decoded, redecoded) {
			t.Fatal("round-trip mismatch: decoded value changed after an encode/decode cycle")
		}
	})
}

func FuzzDecodeRecord(f *testing.F) {
	{
		seed := v0.Record{
			ValuePointer:     "test_1",
			ChannelPointer:   "test_2",
			TimestampPointer: "test_3",
			TimeFormat:       http.TimeFormat("iso8601"),
			Fields: []http.WriteField{
				{Variant: http.StaticWriteField{
					BaseWriteField: http.BaseWriteField{Key: "test_6", Pointer: "test_7"},
					JSONType:       http.JSONType("number"),
					Value:          any(map[string]any{"key_9": "value_9"}),
				}},
			},
		}
		w := orc.NewWriter(0)
		if err := seed.EncodeOrc(w); err != nil {
			f.Fatal(err)
		}
		f.Add(w.Bytes())
	}
	{
		seed := v0.Record{
			ValuePointer:     "",
			ChannelPointer:   "",
			TimestampPointer: "",
			TimeFormat:       http.TimeFormat(""),
			Fields:           []http.WriteField{},
		}
		w := orc.NewWriter(0)
		if err := seed.EncodeOrc(w); err != nil {
			f.Fatal(err)
		}
		f.Add(w.Bytes())
	}
	{
		seed := v0.Record{
			ValuePointer:     "test_1",
			ChannelPointer:   "test_2",
			TimestampPointer: "test_3",
			TimeFormat:       http.TimeFormat("iso8601"),
			Fields:           []http.WriteField{},
		}
		w := orc.NewWriter(0)
		if err := seed.EncodeOrc(w); err != nil {
			f.Fatal(err)
		}
		f.Add(w.Bytes())
	}
	f.Fuzz(func(t *testing.T, data []byte) {
		var decoded v0.Record
		r := orc.NewReader(nil)
		r.ResetBytes(data)
		if err := decoded.DecodeOrc(r); err != nil {
			return
		}
		w1 := orc.NewWriter(len(data))
		if err := decoded.EncodeOrc(w1); err != nil {
			t.Fatalf("encode after successful decode failed: %v", err)
		}
		var redecoded v0.Record
		r.ResetBytes(w1.Bytes())
		if err := redecoded.DecodeOrc(r); err != nil {
			t.Fatalf("re-decode failed: %v", err)
		}
		if !testutil.DeepEqual(decoded, redecoded) {
			t.Fatal("round-trip mismatch: decoded value changed after an encode/decode cycle")
		}
	})
}

func FuzzDecodeScanConfig(f *testing.F) {
	{
		seed := v0.ScanConfig{
			Key:      uuid.MustParse("a1b2c3d4-e5f6-7890-abcd-ef1234567801"),
			Rate:     telem.Rate(2.5),
			Disabled: true,
		}
		w := orc.NewWriter(0)
		if err := seed.EncodeOrc(w); err != nil {
			f.Fatal(err)
		}
		f.Add(w.Bytes())
	}
	{
		seed := v0.ScanConfig{
			Key:      uuid.Nil(),
			Rate:     telem.Rate(0),
			Disabled: false,
		}
		w := orc.NewWriter(0)
		if err := seed.EncodeOrc(w); err != nil {
			f.Fatal(err)
		}
		f.Add(w.Bytes())
	}
	f.Fuzz(func(t *testing.T, data []byte) {
		var decoded v0.ScanConfig
		r := orc.NewReader(nil)
		r.ResetBytes(data)
		if err := decoded.DecodeOrc(r); err != nil {
			return
		}
		w1 := orc.NewWriter(len(data))
		if err := decoded.EncodeOrc(w1); err != nil {
			t.Fatalf("encode after successful decode failed: %v", err)
		}
		var redecoded v0.ScanConfig
		r.ResetBytes(w1.Bytes())
		if err := redecoded.DecodeOrc(r); err != nil {
			t.Fatalf("re-decode failed: %v", err)
		}
		if !testutil.DeepEqual(decoded, redecoded) {
			t.Fatal("round-trip mismatch: decoded value changed after an encode/decode cycle")
		}
	})
}

func FuzzDecodeWriteChannel(f *testing.F) {
	{
		seed := v0.WriteChannel{
			Key:        "test_1",
			Disabled:   false,
			Channel:    channel.Key(4),
			JSONType:   http.JSONType("number"),
			TimeFormat: new(http.TimeFormat("iso8601")),
			EnumValues: []http.EnumEntry{{Label: "test_7", Value: 8.5}},
		}
		w := orc.NewWriter(0)
		if err := seed.EncodeOrc(w); err != nil {
			f.Fatal(err)
		}
		f.Add(w.Bytes())
	}
	{
		seed := v0.WriteChannel{
			Key:        "",
			Disabled:   false,
			Channel:    channel.Key(0),
			JSONType:   http.JSONType(""),
			TimeFormat: nil,
			EnumValues: []http.EnumEntry{},
		}
		w := orc.NewWriter(0)
		if err := seed.EncodeOrc(w); err != nil {
			f.Fatal(err)
		}
		f.Add(w.Bytes())
	}
	{
		seed := v0.WriteChannel{
			Key:        "test_1",
			Disabled:   false,
			Channel:    channel.Key(4),
			JSONType:   http.JSONType("number"),
			TimeFormat: new(http.TimeFormat("iso8601")),
			EnumValues: []http.EnumEntry{},
		}
		w := orc.NewWriter(0)
		if err := seed.EncodeOrc(w); err != nil {
			f.Fatal(err)
		}
		f.Add(w.Bytes())
	}
	f.Fuzz(func(t *testing.T, data []byte) {
		var decoded v0.WriteChannel
		r := orc.NewReader(nil)
		r.ResetBytes(data)
		if err := decoded.DecodeOrc(r); err != nil {
			return
		}
		w1 := orc.NewWriter(len(data))
		if err := decoded.EncodeOrc(w1); err != nil {
			t.Fatalf("encode after successful decode failed: %v", err)
		}
		var redecoded v0.WriteChannel
		r.ResetBytes(w1.Bytes())
		if err := redecoded.DecodeOrc(r); err != nil {
			t.Fatalf("re-decode failed: %v", err)
		}
		if !testutil.DeepEqual(decoded, redecoded) {
			t.Fatal("round-trip mismatch: decoded value changed after an encode/decode cycle")
		}
	})
}

func FuzzDecodeWriteConfig(f *testing.F) {
	{
		seed := v0.WriteConfig{
			Key:       uuid.MustParse("a1b2c3d4-e5f6-7890-abcd-ef1234567801"),
			AutoStart: false,
			Device:    "test_3",
			Topic:     "test_4",
			RecordKey: v0.RecordKey("none"),
			Record: v0.Record{
				ValuePointer:     "test_7",
				ChannelPointer:   "test_8",
				TimestampPointer: "test_9",
				TimeFormat:       http.TimeFormat("iso8601"),
				Fields: []http.WriteField{
					{Variant: http.StaticWriteField{
						BaseWriteField: http.BaseWriteField{Key: "test_12", Pointer: "test_13"},
						JSONType:       http.JSONType("number"),
						Value:          any(map[string]any{"key_15": "value_15"}),
					}},
				},
			},
			Channels: []v0.WriteChannel{
				{
					Key:        "test_17",
					Disabled:   false,
					Channel:    channel.Key(20),
					JSONType:   http.JSONType("number"),
					TimeFormat: new(http.TimeFormat("iso8601")),
					EnumValues: []http.EnumEntry{{Label: "test_23", Value: 24.5}},
				},
			},
		}
		w := orc.NewWriter(0)
		if err := seed.EncodeOrc(w); err != nil {
			f.Fatal(err)
		}
		f.Add(w.Bytes())
	}
	{
		seed := v0.WriteConfig{
			Key:       uuid.Nil(),
			AutoStart: false,
			Device:    "",
			Topic:     "",
			RecordKey: v0.RecordKey(""),
			Record: v0.Record{
				ValuePointer:     "",
				ChannelPointer:   "",
				TimestampPointer: "",
				TimeFormat:       http.TimeFormat(""),
				Fields:           []http.WriteField{},
			},
			Channels: []v0.WriteChannel{},
		}
		w := orc.NewWriter(0)
		if err := seed.EncodeOrc(w); err != nil {
			f.Fatal(err)
		}
		f.Add(w.Bytes())
	}
	{
		seed := v0.WriteConfig{
			Key:       uuid.MustParse("a1b2c3d4-e5f6-7890-abcd-ef1234567801"),
			AutoStart: false,
			Device:    "test_3",
			Topic:     "test_4",
			RecordKey: v0.RecordKey("none"),
			Record: v0.Record{
				ValuePointer:     "test_7",
				ChannelPointer:   "test_8",
				TimestampPointer: "test_9",
				TimeFormat:       http.TimeFormat("iso8601"),
				Fields:           []http.WriteField{},
			},
			Channels: []v0.WriteChannel{},
		}
		w := orc.NewWriter(0)
		if err := seed.EncodeOrc(w); err != nil {
			f.Fatal(err)
		}
		f.Add(w.Bytes())
	}
	f.Fuzz(func(t *testing.T, data []byte) {
		var decoded v0.WriteConfig
		r := orc.NewReader(nil)
		r.ResetBytes(data)
		if err := decoded.DecodeOrc(r); err != nil {
			return
		}
		w1 := orc.NewWriter(len(data))
		if err := decoded.EncodeOrc(w1); err != nil {
			t.Fatalf("encode after successful decode failed: %v", err)
		}
		var redecoded v0.WriteConfig
		r.ResetBytes(w1.Bytes())
		if err := redecoded.DecodeOrc(r); err != nil {
			t.Fatalf("re-decode failed: %v", err)
		}
		if !testutil.DeepEqual(decoded, redecoded) {
			t.Fatal("round-trip mismatch: decoded value changed after an encode/decode cycle")
		}
	})
}
