#  Copyright 2026 Synnax Labs, Inc.
#
#  Use of this software is governed by the Business Source License included in the file
#  licenses/BSL.txt.
#
#  As of the Change Date specified in that file, in accordance with the Business Source
#  License, use of this software will be governed by the Apache License, Version 2.0,
#  included in the file licenses/APL.txt.

from synnax.ni.types import (
    MAKE,
    AnalogReadTask,
    AnalogWriteTask,
    CounterReadTask,
    Device,
    DigitalReadTask,
    DigitalWriteTask,
)
from synnax.ni.types_gen import (
    CJC,
    AccelChargeSensitivityUnits,
    AccelSensitivityUnits,
    AccelUnits,
    AIAccel4WireDCVoltageChannel,
    AIAccelChannel,
    AIAccelChargeChannel,
    AIBridgeChannel,
    AIChannel,
    AIChargeChannel,
    AICurrentChannel,
    AICurrentRMSChannel,
    AIForceBridgePolynomialChannel,
    AIForceBridgeTableChannel,
    AIForceBridgeTwoPointLinChannel,
    AIForceIEPEChannel,
    AIFreqVoltageChannel,
    AIMicrophoneChannel,
    AIPressureBridgePolynomialChannel,
    AIPressureBridgeTableChannel,
    AIPressureBridgeTwoPointLinChannel,
    AIResistanceChannel,
    AIRTDChannel,
    AIStrainGaugeChannel,
    AITempBuiltinChannel,
    AIThermistorIexChannel,
    AIThermistorVexChannel,
    AIThermocoupleChannel,
    AITorqueBridgePolynomialChannel,
    AITorqueBridgeTableChannel,
    AITorqueBridgeTwoPointLinChannel,
    AIVelocityIEPEChannel,
    AIVoltageChannel,
    AIVoltageRMSChannel,
    AIVoltageWithExcitChannel,
    AnalogReadConfig,
    AnalogWriteConfig,
    AOChannel,
    AOCurrentChannel,
    AOFuncGenChannel,
    AOVoltageChannel,
    BaseAIChannel,
    BaseAOChannel,
    BaseCIChannel,
    BridgeConfig,
    BuiltInCJC,
    ChanCJC,
    CIAngularPositionUnits,
    CIAngularVelocityUnits,
    CIChannel,
    CICountDirection,
    CIDecodingType,
    CIDutyCycleChannel,
    CIEdge,
    CIEdgeCountChannel,
    CIFrequencyChannel,
    CIFreqUnits,
    CILinearPositionUnits,
    CILinearVelocityUnits,
    CIMeasMethod,
    CIPeriodChannel,
    CIPositionAngularChannel,
    CIPositionLinearChannel,
    CIPulseWidthChannel,
    CISemiPeriodChannel,
    CITimeUnits,
    CITwoEdgeSepChannel,
    CIVelocityAngularChannel,
    CIVelocityLinearChannel,
    ConstValCJC,
    CounterReadConfig,
    DIChannel,
    DigitalReadConfig,
    DigitalWriteConfig,
    DOChannel,
    ElectricalUnits,
    ExcitationSource,
    ForceSensitivityUnits,
    ForceUnits,
    LinearScale,
    MapScale,
    MinMaxVal,
    NoneScale,
    PolynomialScale,
    PressureUnits,
    ResistanceConfig,
    RTDType,
    Scale,
    ScanConfig,
    ShuntResistorLocation,
    StrainConfig,
    TableScale,
    TemperatureUnits,
    TerminalConfig,
    ThermocoupleType,
    TorqueUnits,
    Units,
    VelocitySensitivityUnits,
    VelocityUnits,
    WaveType,
    WriteConfig,
    ZIndexPhase,
)
from x.deprecation import deprecated_getattr

_DEPRECATED: dict[str, str | tuple[str, str]] = {
    "AIChan": "AIChannel",
    "AIAccel4WireDCVoltageChan": "AIAccel4WireDCVoltageChannel",
    "AIAccelChan": "AIAccelChannel",
    "AIAccelChargeChan": "AIAccelChargeChannel",
    "AIBridgeChan": "AIBridgeChannel",
    "AIChargeChan": "AIChargeChannel",
    "AICurrentChan": "AICurrentChannel",
    "AICurrentRMSChan": "AICurrentRMSChannel",
    "AIForceBridgePolynomialChan": "AIForceBridgePolynomialChannel",
    "AIForceBridgeTableChan": "AIForceBridgeTableChannel",
    "AIForceBridgeTwoPointLinChan": "AIForceBridgeTwoPointLinChannel",
    "AIForceIEPEChan": "AIForceIEPEChannel",
    "AIFreqVoltageChan": "AIFreqVoltageChannel",
    "AIMicrophoneChan": "AIMicrophoneChannel",
    "AIPressureBridgePolynomialChan": "AIPressureBridgePolynomialChannel",
    "AIPressureBridgeTableChan": "AIPressureBridgeTableChannel",
    "AIPressureBridgeTwoPointLinChan": "AIPressureBridgeTwoPointLinChannel",
    "AIResistanceChan": "AIResistanceChannel",
    "AIRTDChan": "AIRTDChannel",
    "AIStrainGageChan": "AIStrainGaugeChannel",
    "AITempBuiltInChan": "AITempBuiltinChannel",
    "AIThermistorChanIex": "AIThermistorIexChannel",
    "AIThermistorChanVex": "AIThermistorVexChannel",
    "AIThermocoupleChan": "AIThermocoupleChannel",
    "AITorqueBridgePolynomialChan": "AITorqueBridgePolynomialChannel",
    "AITorqueBridgeTableChan": "AITorqueBridgeTableChannel",
    "AITorqueBridgeTwoPointLinChan": "AITorqueBridgeTwoPointLinChannel",
    "AIVelocityIEPEChan": "AIVelocityIEPEChannel",
    "AIVoltageChan": "AIVoltageChannel",
    "AIVoltageChanWithExcit": "AIVoltageWithExcitChannel",
    "AIVoltageRMSChan": "AIVoltageRMSChannel",
    "AnalogReadTaskConfig": "AnalogReadConfig",
    "AOChan": "AOChannel",
    "AOCurrentChan": "AOCurrentChannel",
    "AOFuncGenChan": "AOFuncGenChannel",
    "AOVoltageChan": "AOVoltageChannel",
    "BaseAIChan": "BaseAIChannel",
    "BaseAOChan": "BaseAOChannel",
    "BaseCIChan": "BaseCIChannel",
    "CIChan": "CIChannel",
    "CIAngularPositionChan": "CIPositionAngularChannel",
    "CIAngularVelocityChan": "CIVelocityAngularChannel",
    "CIDutyCycleChan": "CIDutyCycleChannel",
    "CIEdgeCountChan": "CIEdgeCountChannel",
    "CIFrequencyChan": "CIFrequencyChannel",
    "CILinearPositionChan": "CIPositionLinearChannel",
    "CILinearVelocityChan": "CIVelocityLinearChannel",
    "CIPeriodChan": "CIPeriodChannel",
    "CIPulseWidthChan": "CIPulseWidthChannel",
    "CISemiPeriodChan": "CISemiPeriodChannel",
    "CITwoEdgeSepChan": "CITwoEdgeSepChannel",
    "DIChan": "DIChannel",
    "DOChan": "DOChannel",
    "LinScale": "LinearScale",
    "NoScale": "NoneScale",
}

__getattr__ = deprecated_getattr(__name__, _DEPRECATED, globals())

__all__ = [
    "AccelChargeSensitivityUnits",
    "AccelSensitivityUnits",
    "AccelUnits",
    "AIAccel4WireDCVoltageChannel",
    "AIAccelChannel",
    "AIAccelChargeChannel",
    "AIBridgeChannel",
    "AIChannel",
    "AIChargeChannel",
    "AICurrentChannel",
    "AICurrentRMSChannel",
    "AIForceBridgePolynomialChannel",
    "AIForceBridgeTableChannel",
    "AIForceBridgeTwoPointLinChannel",
    "AIForceIEPEChannel",
    "AIFreqVoltageChannel",
    "AIMicrophoneChannel",
    "AIPressureBridgePolynomialChannel",
    "AIPressureBridgeTableChannel",
    "AIPressureBridgeTwoPointLinChannel",
    "AIResistanceChannel",
    "AIRTDChannel",
    "AIStrainGaugeChannel",
    "AITempBuiltinChannel",
    "AIThermistorIexChannel",
    "AIThermistorVexChannel",
    "AIThermocoupleChannel",
    "AITorqueBridgePolynomialChannel",
    "AITorqueBridgeTableChannel",
    "AITorqueBridgeTwoPointLinChannel",
    "AIVelocityIEPEChannel",
    "AIVoltageChannel",
    "AIVoltageRMSChannel",
    "AIVoltageWithExcitChannel",
    "AnalogReadConfig",
    "AnalogReadTask",
    "AnalogWriteConfig",
    "AnalogWriteTask",
    "AOChannel",
    "AOCurrentChannel",
    "AOFuncGenChannel",
    "AOVoltageChannel",
    "BaseAIChannel",
    "BaseAOChannel",
    "BaseCIChannel",
    "BridgeConfig",
    "BuiltInCJC",
    "ChanCJC",
    "CIAngularPositionUnits",
    "CIAngularVelocityUnits",
    "CIChannel",
    "CICountDirection",
    "CIDecodingType",
    "CIDutyCycleChannel",
    "CIEdge",
    "CIEdgeCountChannel",
    "CIFreqUnits",
    "CIFrequencyChannel",
    "CILinearPositionUnits",
    "CILinearVelocityUnits",
    "CIMeasMethod",
    "CIPeriodChannel",
    "CIPositionAngularChannel",
    "CIPositionLinearChannel",
    "CIPulseWidthChannel",
    "CISemiPeriodChannel",
    "CITimeUnits",
    "CITwoEdgeSepChannel",
    "CIVelocityAngularChannel",
    "CIVelocityLinearChannel",
    "CJC",
    "ConstValCJC",
    "CounterReadConfig",
    "CounterReadTask",
    "Device",
    "DigitalReadConfig",
    "DigitalReadTask",
    "DigitalWriteConfig",
    "DigitalWriteTask",
    "DIChannel",
    "DOChannel",
    "ElectricalUnits",
    "ExcitationSource",
    "ForceSensitivityUnits",
    "ForceUnits",
    "LinearScale",
    "MAKE",
    "MapScale",
    "MinMaxVal",
    "NoneScale",
    "PolynomialScale",
    "PressureUnits",
    "ResistanceConfig",
    "RTDType",
    "Scale",
    "ScanConfig",
    "ShuntResistorLocation",
    "StrainConfig",
    "TableScale",
    "TemperatureUnits",
    "TerminalConfig",
    "ThermocoupleType",
    "TorqueUnits",
    "Units",
    "VelocitySensitivityUnits",
    "VelocityUnits",
    "WaveType",
    "WriteConfig",
    "ZIndexPhase",
]
