// Copyright 2026 Synnax Labs, Inc.
//
// Use of this software is governed by the Business Source License included in the file
// licenses/BSL.txt.
//
// As of the Change Date specified in that file, in accordance with the Business Source
// License, use of this software will be governed by the Apache License, Version 2.0,
// included in the file licenses/APL.txt.

// Generated by oracle as a template. Edit this file.
//
// autoMigrate handles field copying. Customize non-zero defaults below.

package v1

import "github.com/synnaxlabs/x/gorp"

// Migration lifts stored racks from v0 to v1, dropping the persisted status field.
var Migration = gorp.NewEntryMigration("v54_drop_status", autoMigrateRack)
