# Copyright 2026 Synnax Labs, Inc.
#
# Use of this software is governed by the Business Source License included in the file
# licenses/BSL.txt.
#
# As of the Change Date specified in that file, in accordance with the Business Source
# License, use of this software will be governed by the Apache License, Version 2.0,
# included in the file licenses/APL.txt.

load("@rules_cc//cc:cc_library.bzl", "cc_library")

config_setting(
    name = "nilinuxrt",
    values = {
        "define": "platform=nilinuxrt",
    },
)

cc_library(
    name = "daemon",
    srcs = select({
        ":nilinuxrt": ["daemon_nilinuxrt.cpp"],
        "@platforms//os:linux": ["daemon_linux.cpp"],
        "//conditions:default": ["daemon_noop.cpp"],
    }),
    hdrs = ["daemon.h"],
    linkopts = select({
        ":nilinuxrt": [],
        "@platforms//os:linux": [
            "-lsystemd",
        ],
        "//conditions:default": [],
    }),
    visibility = ["//visibility:public"],
    deps = [
        "//x/cpp/errors",
        "//x/cpp/os",
        "//x/cpp/thread",
        "@glog",
    ],
)
