# Copyright 2026 Synnax Labs, Inc.
#
# Use of this software is governed by the Business Source License included in the file
# licenses/BSL.txt.
#
# As of the Change Date specified in that file, in accordance with the Business Source
# License, use of this software will be governed by the Apache License, Version 2.0,
# included in the file licenses/APL.txt.

load("@rules_cc//cc:cc_library.bzl", "cc_library")
load("@rules_cc//cc:cc_test.bzl", "cc_test")

cc_library(
    name = "backend",
    hdrs = ["backend.h"],
    visibility = ["//visibility:public"],
    deps = [
        "//client/cpp/arinc429",
        "//driver/bus:queue",
        "//driver/codec",
        "//x/cpp/errors",
        "//x/cpp/telem",
    ],
)

cc_library(
    name = "simulated",
    srcs = ["simulated/backend.cpp"],
    hdrs = ["simulated/backend.h"],
    visibility = ["//visibility:public"],
    deps = [
        ":backend",
        "//driver/errors",
    ],
)

cc_library(
    name = "ddc",
    srcs = [
        "ddc/api.cpp",
        "ddc/backend.cpp",
    ],
    hdrs = [
        "ddc/api.h",
        "ddc/backend.h",
    ],
    linkopts = select({
        "@platforms//os:windows": [],
        "//conditions:default": ["-ldl"],
    }),
    visibility = ["//visibility:public"],
    deps = [
        ":backend",
        "//driver/errors",
        "//x/cpp/lib",
    ],
)

cc_library(
    name = "ballard",
    srcs = ["ballard/backend.cpp"],
    hdrs = [
        "ballard/api.h",
        "ballard/backend.h",
    ],
    visibility = ["//visibility:public"],
    deps = [
        ":backend",
        "//driver/bus:vendor",
        "//driver/errors",
    ],
)

cc_library(
    name = "task",
    srcs = [
        "factory.cpp",
        "read.cpp",
        "write.cpp",
    ],
    hdrs = [
        "arinc429.h",
        "read.h",
        "write.h",
    ],
    visibility = ["//visibility:public"],
    deps = [
        ":backend",
        ":ballard",
        ":ddc",
        ":simulated",
        "//client/cpp/arinc429",
        "//client/cpp/library",
        "//driver/bus",
        "//driver/bus:scan",
        "//driver/codec",
        "//driver/common",
        "//driver/errors",
        "//driver/task",
        "//x/cpp/breaker",
        "//x/cpp/errors",
    ],
)

cc_test(
    name = "arinc429_test",
    srcs = [
        "ballard/backend_test.cpp",
        "ddc/backend_test.cpp",
        "simulated/backend_test.cpp",
    ],
    deps = [
        ":ballard",
        ":ddc",
        ":simulated",
        "//x/cpp/lib",
        "//x/cpp/test",
        "@googletest//:gtest_main",
    ],
)

cc_test(
    name = "task_test",
    size = "small",
    srcs = ["task_test.cpp"],
    tags = ["requires-core"],
    deps = [
        ":task",
        "//client/cpp/arinc429",
        "//driver/bus/testutil",
        "//driver/bus/testutil:core",
        "//x/cpp/test",
        "@googletest//:gtest_main",
    ],
)
