// Copyright 2026 Synnax Labs, Inc.
//
// Use of this software is governed by the Business Source License included in the file
// licenses/BSL.txt.
//
// As of the Change Date specified in that file, in accordance with the Business Source
// License, use of this software will be governed by the Apache License, Version 2.0,
// included in the file licenses/APL.txt.

// Code generated by oracle. DO NOT EDIT.

package user_test

import (
	"bytes"
	"github.com/google/uuid"
	"testing"

	. "github.com/onsi/ginkgo/v2"
	. "github.com/onsi/gomega"
	"github.com/synnaxlabs/x/encoding/orc"

	"github.com/synnaxlabs/synnax/pkg/service/user"
)

var _ = Describe("Codec", func() {
	Describe("User", func() {
		DescribeTable("should round-trip encode and decode",
			func(original user.User) {
				w := orc.NewWriter(0)
				Expect(original.EncodeOrc(w)).To(Succeed())
				var decoded user.User
				r := orc.NewReader(nil)
				r.ResetBytes(w.Bytes())
				Expect(decoded.DecodeOrc(r)).To(Succeed())
				Expect(decoded).To(Equal(original))
			},
			Entry("fully populated", user.User{
				Key:       uuid.MustParse("a1b2c3d4-e5f6-7890-abcd-ef1234567801"),
				Username:  "test_2",
				FirstName: "test_3",
				LastName:  "test_4",
				RootUser:  true,
			}),
			Entry("zero values", user.User{
				Key:       uuid.Nil,
				Username:  "",
				FirstName: "",
				LastName:  "",
				RootUser:  false,
			}),
		)
	})
})

func BenchmarkEncodeDecodeUser(b *testing.B) {
	u := user.User{
		Key:       uuid.MustParse("a1b2c3d4-e5f6-7890-abcd-ef1234567801"),
		Username:  "test_2",
		FirstName: "test_3",
		LastName:  "test_4",
		RootUser:  true,
	}
	w := orc.NewWriter(0)
	for i := 0; i < b.N; i++ {
		w.Reset()
		if err := u.EncodeOrc(w); err != nil {
			b.Fatal(err)
		}
		var decoded user.User
		r := orc.NewReader(nil)
		r.ResetBytes(w.Bytes())
		if err := decoded.DecodeOrc(r); err != nil {
			b.Fatal(err)
		}
	}
}

func FuzzDecodeUser(f *testing.F) {
	{
		seed := user.User{
			Key:       uuid.MustParse("a1b2c3d4-e5f6-7890-abcd-ef1234567801"),
			Username:  "test_2",
			FirstName: "test_3",
			LastName:  "test_4",
			RootUser:  true,
		}
		w := orc.NewWriter(0)
		if err := seed.EncodeOrc(w); err != nil {
			f.Fatal(err)
		}
		f.Add(w.Bytes())
	}
	{
		seed := user.User{
			Key:       uuid.Nil,
			Username:  "",
			FirstName: "",
			LastName:  "",
			RootUser:  false,
		}
		w := orc.NewWriter(0)
		if err := seed.EncodeOrc(w); err != nil {
			f.Fatal(err)
		}
		f.Add(w.Bytes())
	}
	f.Fuzz(func(t *testing.T, data []byte) {
		var decoded user.User
		r := orc.NewReader(nil)
		r.ResetBytes(data)
		if err := decoded.DecodeOrc(r); err != nil {
			return
		}
		w1 := orc.NewWriter(len(data))
		if err := decoded.EncodeOrc(w1); err != nil {
			t.Fatalf("encode after successful decode failed: %v", err)
		}
		var redecoded user.User
		r.ResetBytes(w1.Bytes())
		if err := redecoded.DecodeOrc(r); err != nil {
			t.Fatalf("re-decode failed: %v", err)
		}
		w2 := orc.NewWriter(w1.Len())
		if err := redecoded.EncodeOrc(w2); err != nil {
			t.Fatalf("re-encode failed: %v", err)
		}
		if !bytes.Equal(w1.Bytes(), w2.Bytes()) {
			t.Fatal("round-trip mismatch: encoded bytes differ after decode-encode cycle")
		}
	})
}
