version: "v2.12.2"
plugins:
  - module: "github.com/synnaxlabs/x"
    import: "github.com/synnaxlabs/x/analyzers/must"
    path: ../x/go
  - module: "github.com/synnaxlabs/x"
    import: "github.com/synnaxlabs/x/analyzers/set"
    path: ../x/go
  - module: "github.com/synnaxlabs/x"
    import: "github.com/synnaxlabs/x/analyzers/leak"
    path: ../x/go
