# Copyright 2026 Synnax Labs, Inc.
#
# Use of this software is governed by the Business Source License included in the file
# licenses/BSL.txt.
#
# As of the Change Date specified in that file, in accordance with the Business Source
# License, use of this software will be governed by the Apache License, Version 2.0,
# included in the file licenses/APL.txt.

load("@rules_cc//cc:cc_library.bzl", "cc_library")
load("@rules_cc//cc:cc_test.bzl", "cc_test")

cc_library(
    name = "thread",
    hdrs = [
        "thread.h",
    ],
    visibility = ["//visibility:public"],
    deps = [
        "//x/cpp/errors",
        "//x/cpp/log",
        "//x/cpp/telem",
        "@abseil-cpp//absl/log",
    ],
)

cc_test(
    name = "thread_test",
    srcs = [
        "thread_test.cpp",
    ],
    deps = [
        "//x/cpp/telem",
        "//x/cpp/test",
        "//x/cpp/thread",
        "@googletest//:gtest_main",
    ],
)
