// Copyright 2026 Synnax Labs, Inc.
//
// Use of this software is governed by the Business Source License included in the file
// licenses/BSL.txt.
//
// As of the Change Date specified in that file, in accordance with the Business Source
// License, use of this software will be governed by the Apache License, Version 2.0,
// included in the file licenses/APL.txt.

// Code generated by oracle. DO NOT EDIT.

#pragma once

#include <string>
#include <type_traits>

#include "x/cpp/json/json.h"
#include "x/cpp/status/types.gen.h"
#include "x/cpp/telem/json.gen.h"

namespace x::status {

template<typename Details>
Status<Details> Status<Details>::parse(x::json::Parser parser) {
    return Status<Details>{
        .variant = parser.field<std::string>("variant"),
        .message = parser.field<std::string>("message"),
        .description = parser.field<std::string>("description", ""),
        .time = parser.field<::x::telem::TimeStamp>("time"),
        .details = parser.field<Details>("details"),
    };
}

template<typename Details>
x::json::json Status<Details>::to_json() const {
    x::json::json j;
    j["variant"] = this->variant;
    j["message"] = this->message;
    j["description"] = this->description;
    j["time"] = this->time.nanoseconds();
    if constexpr (std::is_same_v<Details, x::json::json::object_t>)
        j["details"] = this->details;
    else if constexpr (std::is_same_v<Details, std::monostate>)
        j["details"] = nullptr;
    else
        j["details"] = this->details.to_json();
    return j;
}

}
