# Copyright 2026 Synnax Labs, Inc.
#
# Use of this software is governed by the Business Source License included in the file
# licenses/BSL.txt.
#
# As of the Change Date specified in that file, in accordance with the Business Source
# License, use of this software will be governed by the Apache License, Version 2.0,
# included in the file licenses/APL.txt.

load("@rules_cc//cc:cc_library.bzl", "cc_library")
load("@rules_cc//cc:cc_test.bzl", "cc_test")

cc_library(
    name = "bus",
    srcs = [
        "config.cpp",
        "connection.cpp",
        "decoder.cpp",
        "read.cpp",
        "write.cpp",
    ],
    hdrs = [
        "config.h",
        "connection.h",
        "decoder.h",
        "read.h",
        "registry.h",
        "task.h",
        "transport.h",
        "write.h",
    ],
    visibility = ["//visibility:public"],
    deps = [
        "//client/cpp:synnax",
        "//client/cpp/bus",
        "//client/cpp/library",
        "//driver/codec",
        "//driver/codec/framing",
        "//driver/common",
        "//driver/task",
        "//driver/transport",
        "//x/cpp/breaker",
        "//x/cpp/errors",
        "//x/cpp/json",
        "//x/cpp/strings",
        "//x/cpp/telem",
        "//x/cpp/thread",
    ],
)

cc_test(
    name = "bus_test",
    size = "small",
    srcs = [
        "config_test.cpp",
        "connection_test.cpp",
        "read_test.cpp",
        "write_test.cpp",
    ],
    deps = [
        ":bus",
        "//driver/bus/testutil",
        "//x/cpp/test",
        "@googletest//:gtest_main",
    ],
)

cc_library(
    name = "queue",
    hdrs = ["queue.h"],
    visibility = ["//visibility:public"],
    deps = ["//x/cpp/telem"],
)

cc_library(
    name = "vendor",
    srcs = ["vendor.cpp"],
    hdrs = ["vendor.h"],
    linkopts = select({
        "@platforms//os:windows": [],
        "//conditions:default": ["-ldl"],
    }),
    visibility = ["//visibility:public"],
    deps = [
        "//driver/errors",
        "//x/cpp/errors",
        "//x/cpp/lib",
    ],
)

cc_library(
    name = "scan",
    hdrs = ["scan.h"],
    visibility = ["//visibility:public"],
    deps = [
        ":vendor",
        "//driver/common",
        "//x/cpp/lib",
    ],
)

cc_test(
    name = "card_test",
    size = "small",
    srcs = [
        "queue_test.cpp",
        "scan_test.cpp",
        "vendor_test.cpp",
    ],
    deps = [
        ":queue",
        ":scan",
        ":vendor",
        "//driver/bus/testutil",
        "//x/cpp/lib",
        "//x/cpp/test",
        "@googletest//:gtest_main",
    ],
)
