load("@rules_cc//cc:cc_library.bzl", "cc_library")
load("@rules_cc//cc:cc_test.bzl", "cc_test")

cc_library(
    name = "color",
    srcs = ["color.cpp"],
    hdrs = [
        "color.h",
        "json.gen.h",
        "proto.gen.h",
        "types.gen.h",
    ],
    visibility = ["//visibility:public"],
    deps = [
        "//x/cpp/errors",
        "//x/cpp/json",
        "//x/cpp/pb",
        "//x/go/color:color_grpc",
    ],
)

cc_test(
    name = "color_test",
    srcs = [
        "color_test.cpp",
    ],
    deps = [
        ":color",
        "@googletest//:gtest_main",
    ],
)
