// Copyright 2026 Synnax Labs, Inc.
//
// Use of this software is governed by the Business Source License included in the file
// licenses/BSL.txt.
//
// As of the Change Date specified in that file, in accordance with the Business Source
// License, use of this software will be governed by the Apache License, Version 2.0,
// included in the file licenses/APL.txt.

// Code generated by oracle. DO NOT EDIT.

#pragma once

#include <cstdint>

#include "x/cpp/color/types.gen.h"
#include "x/cpp/json/json.h"

namespace x::color {

inline Color Color::parse(x::json::Parser parser) {
    return Color{
        .r = parser.field<std::uint8_t>("r"),
        .g = parser.field<std::uint8_t>("g"),
        .b = parser.field<std::uint8_t>("b"),
        .a = parser.field<double>("a"),
    };
}

inline x::json::json Color::to_json() const {
    x::json::json j;
    j["r"] = this->r;
    j["g"] = this->g;
    j["b"] = this->b;
    j["a"] = this->a;
    return j;
}

}
