// Copyright 2026 Synnax Labs, Inc.
//
// Use of this software is governed by the Business Source License included in the file
// licenses/BSL.txt.
//
// As of the Change Date specified in that file, in accordance with the Business Source
// License, use of this software will be governed by the Apache License, Version 2.0,
// included in the file licenses/APL.txt.

// Code generated by oracle. DO NOT EDIT.

package types

import text "github.com/synnaxlabs/x/text/types/v0"

// Level is a typography level identifier shared across visualizations. Mirrors the
// heading ladder (h1 through h5) plus paragraph (p) and small. Order is descending: h1
// is the largest, small is the smallest.
type Level = text.Level

const (
	LevelH1    = text.LevelH1
	LevelH2    = text.LevelH2
	LevelH3    = text.LevelH3
	LevelH4    = text.LevelH4
	LevelH5    = text.LevelH5
	LevelP     = text.LevelP
	LevelSmall = text.LevelSmall
)
