// Copyright 2026 Synnax Labs, Inc.
//
// Use of this software is governed by the Business Source License included in the file
// licenses/BSL.txt.
//
// As of the Change Date specified in that file, in accordance with the Business Source
// License, use of this software will be governed by the Apache License, Version 2.0,
// included in the file licenses/APL.txt.

// Code generated by oracle. DO NOT EDIT.

package lineplot

import (
	"context"
	"github.com/synnaxlabs/x/gorp"
)

// Retrieve is used to retrieve LinePlot records from the database using a
// builder pattern for constructing queries.
type Retrieve struct {
	baseTX gorp.Tx
	gorp   gorp.Retrieve[Key, LinePlot]
}

// Filter is a per-service filter that is bound to the Retrieve when passed to
// Where. Pure filters ignore the Retrieve argument; service-bound filters read
// from it (e.g. r.indexes, r.label, r.hostProvider) to evaluate. Use Match to
// construct one from a closure.
type Filter func(r Retrieve) gorp.Filter[Key, LinePlot]

// Match wraps a closure that needs the Retrieve into a Filter. The Retrieve
// value is supplied by Retrieve.Where at evaluation time.
func Match(
	f func(ctx gorp.Context, r Retrieve, e *LinePlot) (bool, error),
) Filter {
	return func(r Retrieve) gorp.Filter[Key, LinePlot] {
		return gorp.Match(func(ctx gorp.Context, e *LinePlot) (bool, error) {
			return f(ctx, r, e)
		})
	}
}

// And returns a filter that matches when all provided filters match.
func And(fs ...Filter) Filter {
	return func(r Retrieve) gorp.Filter[Key, LinePlot] {
		inner := make([]gorp.Filter[Key, LinePlot], len(fs))
		for i, f := range fs {
			inner[i] = f(r)
		}
		return gorp.And(inner...)
	}
}

// Or returns a filter that matches when any provided filter matches.
func Or(fs ...Filter) Filter {
	return func(r Retrieve) gorp.Filter[Key, LinePlot] {
		inner := make([]gorp.Filter[Key, LinePlot], len(fs))
		for i, f := range fs {
			inner[i] = f(r)
		}
		return gorp.Or(inner...)
	}
}

// Not returns a filter that inverts the provided filter.
func Not(f Filter) Filter {
	return func(r Retrieve) gorp.Filter[Key, LinePlot] {
		return gorp.Not(f(r))
	}
}

// WhereKeys filters for lineplots whose key matches any of the provided keys.
func (r Retrieve) WhereKeys(keys ...Key) Retrieve {
	r.gorp = r.gorp.WhereKeys(keys...)
	return r
}

// Where applies the provided filters to the query, binding each filter to the
// Retrieve so service-bound filters can read from r.indexes, r.label,
// r.hostProvider, etc.
func (r Retrieve) Where(filters ...Filter) Retrieve {
	bound := make([]gorp.Filter[Key, LinePlot], len(filters))
	for i, f := range filters {
		bound[i] = f(r)
	}
	r.gorp = r.gorp.Where(bound...)
	return r
}

// Entry binds the provided lineplot as the result container for the query. If
// multiple lineplots match, the first one is used.
func (r Retrieve) Entry(e *LinePlot) Retrieve {
	r.gorp = r.gorp.Entry(e)
	return r
}

// Entries binds the provided slice of lineplots as the result container for the query.
func (r Retrieve) Entries(es *[]LinePlot) Retrieve {
	r.gorp = r.gorp.Entries(es)
	return r
}

// Limit sets the maximum number of lineplots to return.
func (r Retrieve) Limit(limit int) Retrieve { r.gorp = r.gorp.Limit(limit); return r }

// Offset sets the starting index of the lineplots to return.
func (r Retrieve) Offset(offset int) Retrieve {
	r.gorp = r.gorp.Offset(offset)
	return r
}

// Exec executes the query against the provided transaction.
func (r Retrieve) Exec(ctx context.Context, tx gorp.Tx) error {
	return r.gorp.Exec(ctx, gorp.OverrideTx(r.baseTX, tx))
}

// Count returns the number of lineplots matching the query.
func (r Retrieve) Count(ctx context.Context, tx gorp.Tx) (int, error) {
	return r.gorp.Count(ctx, gorp.OverrideTx(r.baseTX, tx))
}

// Exists checks whether any lineplots match the query.
func (r Retrieve) Exists(ctx context.Context, tx gorp.Tx) (bool, error) {
	return r.gorp.Exists(ctx, gorp.OverrideTx(r.baseTX, tx))
}
