// Copyright 2026 Synnax Labs, Inc.
//
// Use of this software is governed by the Business Source License included in the file
// licenses/BSL.txt.
//
// As of the Change Date specified in that file, in accordance with the Business Source
// License, use of this software will be governed by the Apache License, Version 2.0,
// included in the file licenses/APL.txt.

// Code generated by oracle. DO NOT EDIT.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: core/pkg/distribution/channel/pb/channel.proto

package pb

import (
	pb "github.com/synnaxlabs/x/control/pb"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type OperationType int32

const (
	OperationType_OPERATION_TYPE_MIN  OperationType = 0
	OperationType_OPERATION_TYPE_MAX  OperationType = 1
	OperationType_OPERATION_TYPE_AVG  OperationType = 2
	OperationType_OPERATION_TYPE_NONE OperationType = 3
)

// Enum value maps for OperationType.
var (
	OperationType_name = map[int32]string{
		0: "OPERATION_TYPE_MIN",
		1: "OPERATION_TYPE_MAX",
		2: "OPERATION_TYPE_AVG",
		3: "OPERATION_TYPE_NONE",
	}
	OperationType_value = map[string]int32{
		"OPERATION_TYPE_MIN":  0,
		"OPERATION_TYPE_MAX":  1,
		"OPERATION_TYPE_AVG":  2,
		"OPERATION_TYPE_NONE": 3,
	}
)

func (x OperationType) Enum() *OperationType {
	p := new(OperationType)
	*p = x
	return p
}

func (x OperationType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OperationType) Descriptor() protoreflect.EnumDescriptor {
	return file_core_pkg_distribution_channel_pb_channel_proto_enumTypes[0].Descriptor()
}

func (OperationType) Type() protoreflect.EnumType {
	return &file_core_pkg_distribution_channel_pb_channel_proto_enumTypes[0]
}

func (x OperationType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OperationType.Descriptor instead.
func (OperationType) EnumDescriptor() ([]byte, []int) {
	return file_core_pkg_distribution_channel_pb_channel_proto_rawDescGZIP(), []int{0}
}

type Operation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          OperationType          `protobuf:"varint,1,opt,name=type,proto3,enum=distribution.channel.pb.OperationType" json:"type,omitempty"`
	ResetChannel  uint32                 `protobuf:"varint,2,opt,name=reset_channel,json=resetChannel,proto3" json:"reset_channel,omitempty"`
	Duration      int64                  `protobuf:"varint,3,opt,name=duration,proto3" json:"duration,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Operation) Reset() {
	*x = Operation{}
	mi := &file_core_pkg_distribution_channel_pb_channel_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Operation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Operation) ProtoMessage() {}

func (x *Operation) ProtoReflect() protoreflect.Message {
	mi := &file_core_pkg_distribution_channel_pb_channel_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Operation.ProtoReflect.Descriptor instead.
func (*Operation) Descriptor() ([]byte, []int) {
	return file_core_pkg_distribution_channel_pb_channel_proto_rawDescGZIP(), []int{0}
}

func (x *Operation) GetType() OperationType {
	if x != nil {
		return x.Type
	}
	return OperationType_OPERATION_TYPE_MIN
}

func (x *Operation) GetResetChannel() uint32 {
	if x != nil {
		return x.ResetChannel
	}
	return 0
}

func (x *Operation) GetDuration() int64 {
	if x != nil {
		return x.Duration
	}
	return 0
}

type Channel struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Leaseholder   uint32                 `protobuf:"varint,2,opt,name=leaseholder,proto3" json:"leaseholder,omitempty"`
	DataType      string                 `protobuf:"bytes,3,opt,name=data_type,json=dataType,proto3" json:"data_type,omitempty"`
	IsIndex       bool                   `protobuf:"varint,4,opt,name=is_index,json=isIndex,proto3" json:"is_index,omitempty"`
	LocalKey      uint32                 `protobuf:"varint,5,opt,name=local_key,json=localKey,proto3" json:"local_key,omitempty"`
	LocalIndex    uint32                 `protobuf:"varint,6,opt,name=local_index,json=localIndex,proto3" json:"local_index,omitempty"`
	Virtual       bool                   `protobuf:"varint,7,opt,name=virtual,proto3" json:"virtual,omitempty"`
	Concurrency   pb.Concurrency         `protobuf:"varint,8,opt,name=concurrency,proto3,enum=x.control.pb.Concurrency" json:"concurrency,omitempty"`
	Internal      bool                   `protobuf:"varint,9,opt,name=internal,proto3" json:"internal,omitempty"`
	Operations    []*Operation           `protobuf:"bytes,10,rep,name=operations,proto3" json:"operations,omitempty"`
	Expression    string                 `protobuf:"bytes,11,opt,name=expression,proto3" json:"expression,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Channel) Reset() {
	*x = Channel{}
	mi := &file_core_pkg_distribution_channel_pb_channel_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Channel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Channel) ProtoMessage() {}

func (x *Channel) ProtoReflect() protoreflect.Message {
	mi := &file_core_pkg_distribution_channel_pb_channel_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Channel.ProtoReflect.Descriptor instead.
func (*Channel) Descriptor() ([]byte, []int) {
	return file_core_pkg_distribution_channel_pb_channel_proto_rawDescGZIP(), []int{1}
}

func (x *Channel) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Channel) GetLeaseholder() uint32 {
	if x != nil {
		return x.Leaseholder
	}
	return 0
}

func (x *Channel) GetDataType() string {
	if x != nil {
		return x.DataType
	}
	return ""
}

func (x *Channel) GetIsIndex() bool {
	if x != nil {
		return x.IsIndex
	}
	return false
}

func (x *Channel) GetLocalKey() uint32 {
	if x != nil {
		return x.LocalKey
	}
	return 0
}

func (x *Channel) GetLocalIndex() uint32 {
	if x != nil {
		return x.LocalIndex
	}
	return 0
}

func (x *Channel) GetVirtual() bool {
	if x != nil {
		return x.Virtual
	}
	return false
}

func (x *Channel) GetConcurrency() pb.Concurrency {
	if x != nil {
		return x.Concurrency
	}
	return pb.Concurrency(0)
}

func (x *Channel) GetInternal() bool {
	if x != nil {
		return x.Internal
	}
	return false
}

func (x *Channel) GetOperations() []*Operation {
	if x != nil {
		return x.Operations
	}
	return nil
}

func (x *Channel) GetExpression() string {
	if x != nil {
		return x.Expression
	}
	return ""
}

var File_core_pkg_distribution_channel_pb_channel_proto protoreflect.FileDescriptor

const file_core_pkg_distribution_channel_pb_channel_proto_rawDesc = "" +
	"\n" +
	".core/pkg/distribution/channel/pb/channel.proto\x12\x17distribution.channel.pb\x1a\x1dx/go/control/pb/control.proto\"\x88\x01\n" +
	"\tOperation\x12:\n" +
	"\x04type\x18\x01 \x01(\x0e2&.distribution.channel.pb.OperationTypeR\x04type\x12#\n" +
	"\rreset_channel\x18\x02 \x01(\rR\fresetChannel\x12\x1a\n" +
	"\bduration\x18\x03 \x01(\x03R\bduration\"\x8c\x03\n" +
	"\aChannel\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vleaseholder\x18\x02 \x01(\rR\vleaseholder\x12\x1b\n" +
	"\tdata_type\x18\x03 \x01(\tR\bdataType\x12\x19\n" +
	"\bis_index\x18\x04 \x01(\bR\aisIndex\x12\x1b\n" +
	"\tlocal_key\x18\x05 \x01(\rR\blocalKey\x12\x1f\n" +
	"\vlocal_index\x18\x06 \x01(\rR\n" +
	"localIndex\x12\x18\n" +
	"\avirtual\x18\a \x01(\bR\avirtual\x12;\n" +
	"\vconcurrency\x18\b \x01(\x0e2\x19.x.control.pb.ConcurrencyR\vconcurrency\x12\x1a\n" +
	"\binternal\x18\t \x01(\bR\binternal\x12B\n" +
	"\n" +
	"operations\x18\n" +
	" \x03(\v2\".distribution.channel.pb.OperationR\n" +
	"operations\x12\x1e\n" +
	"\n" +
	"expression\x18\v \x01(\tR\n" +
	"expression*p\n" +
	"\rOperationType\x12\x16\n" +
	"\x12OPERATION_TYPE_MIN\x10\x00\x12\x16\n" +
	"\x12OPERATION_TYPE_MAX\x10\x01\x12\x16\n" +
	"\x12OPERATION_TYPE_AVG\x10\x02\x12\x17\n" +
	"\x13OPERATION_TYPE_NONE\x10\x03B\xe3\x01\n" +
	"\x1bcom.distribution.channel.pbB\fChannelProtoP\x01Z8github.com/synnaxlabs/synnax/pkg/distribution/channel/pb\xa2\x02\x03DCP\xaa\x02\x17Distribution.Channel.Pb\xca\x02\x17Distribution\\Channel\\Pb\xe2\x02#Distribution\\Channel\\Pb\\GPBMetadata\xea\x02\x19Distribution::Channel::Pbb\x06proto3"

var (
	file_core_pkg_distribution_channel_pb_channel_proto_rawDescOnce sync.Once
	file_core_pkg_distribution_channel_pb_channel_proto_rawDescData []byte
)

func file_core_pkg_distribution_channel_pb_channel_proto_rawDescGZIP() []byte {
	file_core_pkg_distribution_channel_pb_channel_proto_rawDescOnce.Do(func() {
		file_core_pkg_distribution_channel_pb_channel_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_core_pkg_distribution_channel_pb_channel_proto_rawDesc), len(file_core_pkg_distribution_channel_pb_channel_proto_rawDesc)))
	})
	return file_core_pkg_distribution_channel_pb_channel_proto_rawDescData
}

var file_core_pkg_distribution_channel_pb_channel_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_core_pkg_distribution_channel_pb_channel_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_core_pkg_distribution_channel_pb_channel_proto_goTypes = []any{
	(OperationType)(0),  // 0: distribution.channel.pb.OperationType
	(*Operation)(nil),   // 1: distribution.channel.pb.Operation
	(*Channel)(nil),     // 2: distribution.channel.pb.Channel
	(pb.Concurrency)(0), // 3: x.control.pb.Concurrency
}
var file_core_pkg_distribution_channel_pb_channel_proto_depIdxs = []int32{
	0, // 0: distribution.channel.pb.Operation.type:type_name -> distribution.channel.pb.OperationType
	3, // 1: distribution.channel.pb.Channel.concurrency:type_name -> x.control.pb.Concurrency
	1, // 2: distribution.channel.pb.Channel.operations:type_name -> distribution.channel.pb.Operation
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_core_pkg_distribution_channel_pb_channel_proto_init() }
func file_core_pkg_distribution_channel_pb_channel_proto_init() {
	if File_core_pkg_distribution_channel_pb_channel_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_core_pkg_distribution_channel_pb_channel_proto_rawDesc), len(file_core_pkg_distribution_channel_pb_channel_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_core_pkg_distribution_channel_pb_channel_proto_goTypes,
		DependencyIndexes: file_core_pkg_distribution_channel_pb_channel_proto_depIdxs,
		EnumInfos:         file_core_pkg_distribution_channel_pb_channel_proto_enumTypes,
		MessageInfos:      file_core_pkg_distribution_channel_pb_channel_proto_msgTypes,
	}.Build()
	File_core_pkg_distribution_channel_pb_channel_proto = out.File
	file_core_pkg_distribution_channel_pb_channel_proto_goTypes = nil
	file_core_pkg_distribution_channel_pb_channel_proto_depIdxs = nil
}
