VERSION 0.7
FROM golang:1.23
WORKDIR /synnax

deps:
    COPY ../freighter/go+source/* /freighter/go
    COPY ../alamos/go+source/* /alamos/go
    COPY ../x/go+source/* /x/go
    COPY ../cesium+source/* /cesium
    COPY ../aspen+source/* /aspen
    COPY ../computron+source/* /computron  # This references the built computron
    COPY go.mod go.sum ./
    RUN go mod download

build:
    FROM +deps
    COPY . .
    ARG driver=true
    IF [ "$driver" = "true" ]
        RUN go build -tags driver -o build/synnax .
    ELSE
        RUN go build -o build/synnax .
    END
    SAVE ARTIFACT build/synnax /synnax AS LOCAL build/synnax

docker:
    ARG tag="latest"
    COPY +build/synnax .
    ENTRYPOINT ["/synnax/synnax", "start"]
    SAVE IMAGE ghcr.io/synnaxlabs/synnax:$tag
