// Copyright 2026 Synnax Labs, Inc.
//
// Use of this software is governed by the Business Source License included in the file
// licenses/BSL.txt.
//
// As of the Change Date specified in that file, in accordance with the Business Source
// License, use of this software will be governed by the Apache License, Version 2.0,
// included in the file licenses/APL.txt.

// Code generated by Oracle. DO NOT EDIT.
import { array } from "@synnaxlabs/x";
import { type Draft } from "immer";
import { z } from "zod";

import { actions } from "@/actions";
import { channel } from "@/channel";
import { channelEntryZ, keyZ, type Log } from "@/log/types.gen";

/** Rename renames the log. */
export const renamePayloadZ = z.object({
  name: z.string(),
});

export type RenamePayload = z.infer<typeof renamePayloadZ>;

/**
 * AddChannel appends a default channel entry for the given channel. No-op when
 * the channel is already present.
 */
export const addChannelPayloadZ = z.object({
  channel: channel.keyZ,
});

export type AddChannelPayload = z.infer<typeof addChannelPayloadZ>;

/**
 * RemoveChannel removes the channel entry for the given channel. No-op when the
 * channel is not present.
 */
export const removeChannelPayloadZ = z.object({
  channel: channel.keyZ,
});

export type RemoveChannelPayload = z.infer<typeof removeChannelPayloadZ>;

/**
 * SetChannelEntry inserts the channel entry if no entry with the same channel exists,
 * otherwise replaces the existing entry in place. Used both when a
 * channel is added and when the user edits an existing channel's
 * display configuration.
 */
export const setChannelEntryPayloadZ = z.object({
  entry: channelEntryZ,
});

export type SetChannelEntryPayload = z.infer<typeof setChannelEntryPayloadZ>;

/**
 * SetChannels replaces the entire ordered list of channel entries. Used for bulk
 * channel selection and reordering.
 */
export const setChannelsPayloadZ = z.object({
  channels: array.nullishToEmpty(channelEntryZ),
});

export type SetChannelsPayload = z.infer<typeof setChannelsPayloadZ>;

/** SetTimestampPrecision sets the precision of displayed timestamps (0-3). */
export const setTimestampPrecisionPayloadZ = z.object({
  timestampPrecision: z.int32(),
});

export type SetTimestampPrecisionPayload = z.infer<
  typeof setTimestampPrecisionPayloadZ
>;

/** SetShowChannelNames controls whether channel names are displayed. */
export const setShowChannelNamesPayloadZ = z.object({
  showChannelNames: z.boolean(),
});

export type SetShowChannelNamesPayload = z.infer<typeof setShowChannelNamesPayloadZ>;

/** SetShowReceiptTimestamp controls whether the receipt timestamp column is displayed. */
export const setShowReceiptTimestampPayloadZ = z.object({
  showReceiptTimestamp: z.boolean(),
});

export type SetShowReceiptTimestampPayload = z.infer<
  typeof setShowReceiptTimestampPayloadZ
>;

export const actionZ = z.discriminatedUnion("type", [
  z.object({ type: z.literal("rename"), rename: renamePayloadZ }),
  z.object({ type: z.literal("add_channel"), addChannel: addChannelPayloadZ }),
  z.object({ type: z.literal("remove_channel"), removeChannel: removeChannelPayloadZ }),
  z.object({
    type: z.literal("set_channel_entry"),
    setChannelEntry: setChannelEntryPayloadZ,
  }),
  z.object({ type: z.literal("set_channels"), setChannels: setChannelsPayloadZ }),
  z.object({
    type: z.literal("set_timestamp_precision"),
    setTimestampPrecision: setTimestampPrecisionPayloadZ,
  }),
  z.object({
    type: z.literal("set_show_channel_names"),
    setShowChannelNames: setShowChannelNamesPayloadZ,
  }),
  z.object({
    type: z.literal("set_show_receipt_timestamp"),
    setShowReceiptTimestamp: setShowReceiptTimestampPayloadZ,
  }),
]);

export type Action = z.infer<typeof actionZ>;

export const rename = (payload: RenamePayload): Action => ({
  type: "rename",
  rename: payload,
});

export const addChannel = (payload: AddChannelPayload): Action => ({
  type: "add_channel",
  addChannel: payload,
});

export const removeChannel = (payload: RemoveChannelPayload): Action => ({
  type: "remove_channel",
  removeChannel: payload,
});

export const setChannelEntry = (payload: SetChannelEntryPayload): Action => ({
  type: "set_channel_entry",
  setChannelEntry: payload,
});

export const setChannels = (payload: SetChannelsPayload): Action => ({
  type: "set_channels",
  setChannels: payload,
});

export const setTimestampPrecision = (
  payload: SetTimestampPrecisionPayload,
): Action => ({
  type: "set_timestamp_precision",
  setTimestampPrecision: payload,
});

export const setShowChannelNames = (payload: SetShowChannelNamesPayload): Action => ({
  type: "set_show_channel_names",
  setShowChannelNames: payload,
});

export const setShowReceiptTimestamp = (
  payload: SetShowReceiptTimestampPayload,
): Action => ({
  type: "set_show_receipt_timestamp",
  setShowReceiptTimestamp: payload,
});

export type HandlerResult = actions.HandlerResult<Action>;

export type ReduceAllResult = actions.ReduceAllResult<Log, Action>;

export interface Handlers {
  rename: (state: Draft<Log>, payload: RenamePayload) => HandlerResult;
  addChannel: (state: Draft<Log>, payload: AddChannelPayload) => HandlerResult;
  removeChannel: (state: Draft<Log>, payload: RemoveChannelPayload) => HandlerResult;
  setChannelEntry: (
    state: Draft<Log>,
    payload: SetChannelEntryPayload,
  ) => HandlerResult;
  setChannels: (state: Draft<Log>, payload: SetChannelsPayload) => HandlerResult;
  setTimestampPrecision: (
    state: Draft<Log>,
    payload: SetTimestampPrecisionPayload,
  ) => HandlerResult;
  setShowChannelNames: (
    state: Draft<Log>,
    payload: SetShowChannelNamesPayload,
  ) => HandlerResult;
  setShowReceiptTimestamp: (
    state: Draft<Log>,
    payload: SetShowReceiptTimestampPayload,
  ) => HandlerResult;
}

export const createReduceAll = (handlers: Handlers) =>
  actions.createReduceAll<Log, Action>((state, action) => {
    switch (action.type) {
      case "rename":
        return handlers.rename(state, action.rename);
      case "add_channel":
        return handlers.addChannel(state, action.addChannel);
      case "remove_channel":
        return handlers.removeChannel(state, action.removeChannel);
      case "set_channel_entry":
        return handlers.setChannelEntry(state, action.setChannelEntry);
      case "set_channels":
        return handlers.setChannels(state, action.setChannels);
      case "set_timestamp_precision":
        return handlers.setTimestampPrecision(state, action.setTimestampPrecision);
      case "set_show_channel_names":
        return handlers.setShowChannelNames(state, action.setShowChannelNames);
      case "set_show_receipt_timestamp":
        return handlers.setShowReceiptTimestamp(state, action.setShowReceiptTimestamp);
    }
  });

export const scopedActionZ = actions.scopedZ(keyZ, actionZ);

export const dispatchReqZ = actions.dispatchReqZ(keyZ, actionZ);
