import "./registry.css";
import { type IconProps, type ReactElement } from "./Icon";
export declare const Pause: import("./Icon").FC;
export declare const Play: import("./Icon").FC;
export declare const Stop: import("./Icon").FC;
export declare const Circle: import("./Icon").FC;
export declare const Square: import("./Icon").FC;
export declare const Edit: import("./Icon").FC;
export declare const EditOff: import("./Icon").FC;
export declare const Add: import("./Icon").FC;
export declare const Subtract: import("./Icon").FC;
export declare const Copy: import("./Icon").FC;
export declare const Cut: import("./Icon").FC;
export declare const Paste: import("./Icon").FC;
export declare const Undo: import("./Icon").FC;
export declare const Redo: import("./Icon").FC;
export declare const Close: import("./Icon").FC;
export declare const CloseThin: import("./Icon").FC;
export declare const Info: import("./Icon").FC;
export declare const Warning: import("./Icon").FC;
export declare const Check: import("./Icon").FC;
export declare const Refresh: import("./Icon").FC;
export declare const View: import("./Icon").FC;
export declare const Delete: import("./Icon").FC & {
    Row: import("./Icon").FC;
    Col: import("./Icon").FC;
};
export declare const Eraser: import("./Icon").FC;
export declare const Time: import("./Icon").FC;
export declare const TimeOutline: import("./Icon").FC;
export declare const Acquire: import("./Icon").FC;
export declare const Analyze: import("./Icon").FC;
export declare const Concepts: import("./Icon").FC;
export declare const Visualize: import("./Icon").FC;
export declare const Panel: import("./Icon").FC;
export declare const LinePlot: import("./Icon").FC;
export declare const Expand: import("./Icon").FC;
export declare const Collapse: import("./Icon").FC;
export declare const Core: import("./Icon").FC;
export declare const Component: import("./Icon").FC;
export declare const Loading: import("./Icon").FC;
export declare const Schematic: import("./Icon").FC;
export declare const Caret: {
    Right: import("./Icon").FC;
    Bottom: import("./Icon").FC;
    Left: import("./Icon").FC;
    Up: import("./Icon").FC;
    Top: import("./Icon").FC;
    Down: import("./Icon").FC;
};
export declare const Settings: import("./Icon").FC;
export declare const Reference: import("./Icon").FC;
export declare const Bolt: import("./Icon").FC;
export declare const Import: import("./Icon").FC;
export declare const Export: import("./Icon").FC;
export declare const Download: import("./Icon").FC;
export declare const Range: import("./Icon").FC;
export declare const Node: import("./Icon").FC;
export declare const Channel: import("./Icon").FC;
export declare const Resources: import("./Icon").FC;
export declare const Group: import("./Icon").FC;
export declare const Ungroup: import("./Icon").FC;
export declare const Lock: import("./Icon").FC;
export declare const Unlock: import("./Icon").FC;
export declare const Project: import("./Icon").FC;
export declare const Box: import("./Icon").FC;
export declare const Boxes: import("./Icon").FC;
export declare const Python: import("./Icon").FC;
export declare const TypeScript: import("./Icon").FC;
export declare const CPlusPlus: import("./Icon").FC;
export declare const NPM: import("./Icon").FC;
export declare const PNPM: import("./Icon").FC;
export declare const Yarn: import("./Icon").FC;
export declare const QuestionMark: import("./Icon").FC;
export declare const Menu: import("./Icon").FC;
export declare const Logo: {
    Apple: import("./Icon").FC;
    Docker: import("./Icon").FC;
    Github: import("./Icon").FC;
    LabJack: import("./Icon").FC;
    LinkedIn: import("./Icon").FC;
    Linux: import("./Icon").FC;
    Modbus: import("./Icon").FC;
    NI: import("./Icon").FC;
    OPCUA: import("./Icon").FC;
    PagerDuty: import("./Icon").FC;
    Windows: import("./Icon").FC;
    EtherCAT: import("./Icon").FC;
    HTTP: import("./Icon").FC;
};
export declare const Arrow: {
    Right: import("./Icon").FC;
    Down: import("./Icon").FC;
    Bottom: import("./Icon").FC;
    Up: import("./Icon").FC;
    Left: import("./Icon").FC;
    Top: import("./Icon").FC;
};
export declare const Keyboard: {
    Command: import("./Icon").FC;
    Windows: import("./Icon").FC;
    Tab: import("./Icon").FC;
    Return: import("./Icon").FC;
    Backspace: import("./Icon").FC;
    Capslock: import("./Icon").FC;
    Hide: import("./Icon").FC;
    Control: import("./Icon").FC;
    Arrow: {
        Up: import("./Icon").FC;
        Down: import("./Icon").FC;
        Left: import("./Icon").FC;
        Right: import("./Icon").FC;
    };
    Alt: import("./Icon").FC;
    Option: import("./Icon").FC;
    Shift: import("./Icon").FC;
};
export declare const Tooltip: import("./Icon").FC;
export declare const Annotate: import("./Icon").FC;
export declare const Zoom: import("./Icon").FC;
export declare const Selection: import("./Icon").FC;
export declare const Pan: import("./Icon").FC;
export declare const Rule: import("./Icon").FC;
export declare const User: import("./Icon").FC;
export declare const Role: import("./Icon").FC;
export declare const Policy: import("./Icon").FC;
export declare const Rename: import("./Icon").FC;
export declare const Snapshot: import("./Icon").FC;
export declare const Sync: import("./Icon").FC;
export declare const Search: import("./Icon").FC;
export declare const Auto: import("./Icon").FC;
export declare const Table: import("./Icon").FC;
export declare const Insert: {
    Row: {
        Above: import("./Icon").FC;
        Below: import("./Icon").FC;
    };
    Col: {
        Left: import("./Icon").FC;
        Right: import("./Icon").FC;
    };
};
export declare const Wave: {
    Sawtooth: import("./Icon").FC;
    Sine: import("./Icon").FC;
    Triangle: import("./Icon").FC;
    Square: import("./Icon").FC;
};
export declare const Align: {
    Right: import("./Icon").FC;
    Left: import("./Icon").FC;
    XCenter: import("./Icon").FC;
    YCenter: import("./Icon").FC;
    Top: import("./Icon").FC;
    Bottom: import("./Icon").FC;
    BoxCenter: import("./Icon").FC;
    BoxTopLeft: import("./Icon").FC;
};
export declare const Distribute: {
    X: import("./Icon").FC;
    Y: import("./Icon").FC;
};
export declare const TextAlign: {
    Center: import("./Icon").FC;
    Left: import("./Icon").FC;
    Right: import("./Icon").FC;
};
export declare const Connect: import("./Icon").FC;
export declare const Disconnect: import("./Icon").FC;
export declare const Hardware: import("./Icon").FC;
export declare const Save: import("./Icon").FC;
export declare const Task: import("./Icon").FC;
export declare const Device: import("./Icon").FC;
export declare const Link: import("./Icon").FC;
export declare const Attachment: import("./Icon").FC;
export declare const Drag: import("./Icon").FC;
export declare const Dynamic: import("./Icon").FC;
export declare const Enable: import("./Icon").FC;
export declare const Disable: import("./Icon").FC;
export declare const Variable: import("./Icon").FC;
export declare const Type: import("./Icon").FC;
export declare const Array: import("./Icon").FC;
export declare const Label: import("./Icon").FC;
export declare const Details: import("./Icon").FC;
export declare const LinkExternal: import("./Icon").FC;
export declare const Access: import("./Icon").FC;
export declare const JSON: import("./Icon").FC;
export declare const Guide: import("./Icon").FC;
export declare const Focus: import("./Icon").FC;
export declare const OpenInNewWindow: import("./Icon").FC;
export declare const MoveToMainWindow: import("./Icon").FC;
export declare const SplitX: import("./Icon").FC;
export declare const SplitY: import("./Icon").FC;
export declare const AutoFitWidth: import("./Icon").FC;
export declare const Commit: import("./Icon").FC;
export declare const Snooze: import("./Icon").FC;
export declare const Log: import("./Icon").FC;
export declare const Tare: import("./Icon").FC;
export declare const Rotate: import("./Icon").FC;
export declare const RotateGroup: {
    CW: import("./Icon").FC;
    CCW: import("./Icon").FC;
};
export declare const RotateAroundCenter: {
    CW: import("./Icon").FC;
    CCW: import("./Icon").FC;
};
export declare const Text: import("./Icon").FC;
export declare const Value: import("./Icon").FC;
export declare const Calendar: import("./Icon").FC;
export declare const Release: import("./Icon").FC;
export declare const OpenExternal: import("./Icon").FC;
export declare const Feedback: import("./Icon").FC;
export declare const Calculation: import("./Icon").FC;
export declare const Binary: import("./Icon").FC;
export declare const Decimal: import("./Icon").FC;
export declare const Scientific: import("./Icon").FC;
export declare const Engineering: import("./Icon").FC;
export declare const String: import("./Icon").FC;
export declare const Control: import("./Icon").FC;
export declare const Rack: import("./Icon").FC;
export declare const Units: {
    Acceleration: import("./Icon").FC;
    Current: import("./Icon").FC;
    Force: import("./Icon").FC;
    Pressure: import("./Icon").FC;
    Resistance: import("./Icon").FC;
    Strain: import("./Icon").FC;
    Temperature: import("./Icon").FC;
    Torque: import("./Icon").FC;
    Velocity: import("./Icon").FC;
    Voltage: import("./Icon").FC;
};
export declare const Bridge: import("./Icon").FC;
export declare const Sound: import("./Icon").FC;
export declare const Function: import("./Icon").FC;
export declare const Visible: import("./Icon").FC;
export declare const Hidden: import("./Icon").FC;
export declare const Virtual: import("./Icon").FC;
export declare const Explore: import("./Icon").FC;
export declare const Filter: import("./Icon").FC;
export declare const StarFilled: import("./Icon").FC;
export declare const StarOutlined: import("./Icon").FC;
export declare const Heart: import("./Icon").FC;
export declare const StrokeWidth: import("./Icon").FC;
export declare const Downsample: import("./Icon").FC;
export declare const Terminal: import("./Icon").FC;
export declare const TerminalOutline: import("./Icon").FC;
export declare const Map: import("./Icon").FC;
export declare const Linear: import("./Icon").FC;
export declare const None: import("./Icon").FC;
export declare const Arc: import("./Icon").FC;
export declare const ArcFlow: import("./Icon").FC;
export declare const ArcFunc: import("./Icon").FC;
export declare const Select: import("./Icon").FC;
export declare const Notification: import("./Icon").FC;
export declare const Status: import("./Icon").FC;
export declare const InProgress: import("./Icon").FC;
export declare const Completed: import("./Icon").FC;
export declare const ToDo: import("./Icon").FC;
export declare const Constant: import("./Icon").FC;
export declare const Boolean: import("./Icon").FC;
export declare const True: import("./Icon").FC;
export declare const False: import("./Icon").FC;
export declare const KebabMenu: import("./Icon").FC;
export declare const Annotation: import("./Icon").FC;
export declare const Click: import("./Icon").FC;
export declare const DarkMode: import("./Icon").FC;
export declare const LightMode: import("./Icon").FC;
export declare const Safety: import("./Icon").FC;
export declare const CSV: import("./Icon").FC;
export declare const Reset: import("./Icon").FC;
export declare const FillColor: import("./Icon").FC;
export declare const StrokeColor: import("./Icon").FC;
export declare const Logout: import("./Icon").FC;
export declare const Dashboard: import("./Icon").FC;
export declare const Err: import("./Icon").FC;
export interface CreateProps extends Omit<IconProps, "topRight"> {
}
interface Resolve {
    (icon?: ReactElement | string, overrides?: IconProps): ReactElement | undefined;
    (icon: ReactElement | string, overrides?: IconProps): ReactElement;
}
export declare const resolve: Resolve;
export {};
//# sourceMappingURL=registry.d.ts.map