// Code generated by oracle. DO NOT EDIT.

package pb

import (
	"context"
	"github.com/google/uuid"
	"github.com/synnaxlabs/synnax/pkg/service/workspace/lineplot"
)


// LinePlotToPB converts LinePlot to LinePlot.
func LinePlotToPB(_ context.Context, r lineplot.LinePlot) (*LinePlot, error) {
	pb := &LinePlot{
		Key: r.Key.String(),
		Name: r.Name,
		Data: r.Data,
	}
	return pb, nil
}

// LinePlotFromPB converts LinePlot to LinePlot.
func LinePlotFromPB(_ context.Context, pb *LinePlot) (lineplot.LinePlot, error) {
	var r lineplot.LinePlot
	if pb == nil {
		return r, nil
	}
	r.Key = uuid.MustParse(pb.Key)
	r.Name = pb.Name
	r.Data = pb.Data
	return r, nil
}

// LinePlotsToPB converts a slice of LinePlot to LinePlot.
func LinePlotsToPB(ctx context.Context, rs []lineplot.LinePlot) ([]*LinePlot, error) {
	result := make([]*LinePlot, len(rs))
	for i := range rs {
		var err error
		result[i], err = LinePlotToPB(ctx, rs[i])
		if err != nil {
			return nil, err
		}
	}
	return result, nil
}

// LinePlotsFromPB converts a slice of LinePlot to LinePlot.
func LinePlotsFromPB(ctx context.Context, pbs []*LinePlot) ([]lineplot.LinePlot, error) {
	result := make([]lineplot.LinePlot, len(pbs))
	for i, pb := range pbs {
		var err error
		result[i], err = LinePlotFromPB(ctx, pb)
		if err != nil {
			return nil, err
		}
	}
	return result, nil
}
