// Copyright 2026 Synnax Labs, Inc.
//
// Use of this software is governed by the Business Source License included in the file
// licenses/BSL.txt.
//
// As of the Change Date specified in that file, in accordance with the Business Source
// License, use of this software will be governed by the Apache License, Version 2.0,
// included in the file licenses/APL.txt.

// Code generated by oracle. DO NOT EDIT.

package pb

import (
	"context"

	"github.com/synnaxlabs/x/gorp"

	table "github.com/synnaxlabs/synnax/pkg/service/table"
)

type tableCodec struct{}

func (tableCodec) Marshal(
	ctx context.Context,
	s table.Table,
) ([]byte, error) {
	p, err := TableToPB(ctx, s)
	if err != nil {
		return nil, err
	}
	return p.MarshalVT()
}

func (tableCodec) Unmarshal(
	ctx context.Context,
	data []byte,
) (table.Table, error) {
	p := &Table{}
	if err := p.UnmarshalVT(data); err != nil {
		return table.Table{}, err
	}
	return TableFromPB(ctx, p)
}

var TableCodec gorp.Codec[table.Table] = tableCodec{}
