// Copyright 2026 Synnax Labs, Inc.
//
// Use of this software is governed by the Business Source License included in the file
// licenses/BSL.txt.
//
// As of the Change Date specified in that file, in accordance with the Business Source
// License, use of this software will be governed by the Apache License, Version 2.0,
// included in the file licenses/APL.txt.

syntax = "proto3";

package freighter.grpc.v1;

option go_package = "github.com/synnaxlabs/freighter/grpc/v1";

message Request {
  int32 id = 1;
  string message = 2;
}

message Response {
  int32 id = 1;
  string message = 2;
}

service TestUnaryService {
  rpc Exec(Request) returns (Response);
}

service TestStreamService {
  rpc Exec(stream Request) returns (stream Response);
}
