VERSION 0.6

deps:
    FROM node:18.7.0-alpine3.16
    COPY ../../../pluto+build/* /pluto/
    WORKDIR /delta/pkg/ui
    COPY package.json ./
    COPY yarn.lock ./
    RUN yarn install

build:
    FROM +deps
    COPY . .
    RUN yarn build
    SAVE ARTIFACT .
