VERSION 0.6

deps:
    FROM node:18.7.0-alpine3.16
    RUN npm install -g pnpm
    WORKDIR /delta/pkg/ui
    COPY package.json ./
    COPY pnpm-lock.yaml ./
    RUN pnpm i

build:
    FROM +deps
    COPY . .
    RUN pnpm i
    SAVE ARTIFACT .
