VERSION 0.6

deps:
    FROM node:18.7.0-alpine3.16
    COPY ../../../pluto+build/* /pluto/
    WORKDIR /delta/pkg/ui
    COPY package.json ./
    COPY yarn.lock ./
    RUN yarn install

build:
    FROM +deps
    COPY . .
    RUN yarn build
    SAVE ARTIFACT .

dev:
    LOCALLY
    IF [ ! -d "node_modules" ]
        RUN yarn
    END
    RUN earthly ../../../+link
    IF [ ! -d "../../../pluto/dist" ]
        RUN earthly ../../../pluto+build --local=true
    END
    RUN yarn dev
