VERSION 0.6
FROM golang:1.19-alpine3.16
RUN apk add build-base
WORKDIR /delta

deps:
    COPY ./pkg/ui+build/* ./pkg/ui
    COPY ../x+base-artifact/* /x
    COPY ../cesium+base-artifact/* /cesium
    COPY ../aspen+base-artifact/* /aspen
    COPY ../freighter/go+base-artifact/* /freighter/go
    COPY ../client/go+base-artifact/* /client/go
    COPY go.mod go.sum ./
    RUN go mod download

build:
    FROM +deps
    COPY . .
    RUN go build -o build/delta main.go
    SAVE ARTIFACT build/delta /delta AS LOCAL build/delta

docker:
    COPY +build/delta .
    ENTRYPOINT ["/delta/delta", "start"]
    SAVE IMAGE arya/delta:latest