// Copyright 2026 Synnax Labs, Inc.
//
// Use of this software is governed by the Business Source License included in the file
// licenses/BSL.txt.
//
// As of the Change Date specified in that file, in accordance with the Business Source
// License, use of this software will be governed by the Apache License, Version 2.0,
// included in the file licenses/APL.txt.

// Code generated by Oracle. DO NOT EDIT.

import { array, caseconv, color, record, spatial, zod } from "@synnaxlabs/x";
import { z } from "zod";

import { ontology } from "@/ontology";

/** Node is a diagram node representing a symbol in the schematic. */
export const nodeZ = z.object({
  /** key is the unique node identifier within the schematic. */
  key: z.string(),
  /** position is the top-left position of the node. */
  position: spatial.xyZ,
  /**
   * zIndex is the stacking order of the node within the schematic. Higher
   * values render above lower values. Set by the user via
   * send-to-back / bring-to-front actions.
   */
  zIndex: zod.int16.optional(),
  /**
   * measured is the rendered pixel size of the node. Populated by the
   * renderer after the node is mounted and used to keep diagram
   * measurements consistent across re-renders.
   */
  measured: spatial.dimensionsZ.optional(),
});
export interface Node extends z.infer<typeof nodeZ> {}

/**
 * Handle is a reference to a specific connection point on a specific node.
 * For schematics, param is the symbol handle key (e.g. inlet, outlet).
 */
export const handleZ = z.object({
  /** node is the node identifier. */
  node: z.string(),
  /** param is the connection point identifier on the node. */
  param: z.string(),
});
export interface Handle extends z.infer<typeof handleZ> {}

/** Segment is a single orthogonal run in an edge's connector path. */
export const segmentZ = z.object({
  /** direction is the axis along which the segment travels. */
  direction: spatial.directionZ,
  /** length is the signed length of the segment in pixels. */
  length: z.number(),
});
export interface Segment extends z.infer<typeof segmentZ> {}

export const keyZ = z.uuid();
export type Key = z.infer<typeof keyZ>;

/** Edge is a connection between two nodes in the schematic. */
export const edgeZ = z.object({
  /** key is the unique edge identifier within the schematic. */
  key: z.string(),
  /** source is the source endpoint of the edge. */
  source: handleZ,
  /** target is the target endpoint of the edge. */
  target: handleZ,
});
export interface Edge extends z.infer<typeof edgeZ> {}

/** SegmentedEdgeConfig is the configuration shared by every segmented edge variant. */
export const segmentedEdgeConfigZ = z.object({
  /** color is the stroke color of the edge. */
  color: color.colorZ,
  /**
   * segments is the ordered list of orthogonal runs that trace the connector
   * path from the source handle to the target handle.
   */
  segments: array.nullishToEmpty(segmentZ),
});
export interface SegmentedEdgeConfig extends z.infer<typeof segmentedEdgeConfigZ> {}

/**
 * Schematic is a visual diagram editor component for drawing system schematics,
 * control flows, and process diagrams. Schematics support interactive
 * symbols, connection handles, and dynamic state visualization.
 */
export const schematicZ = z.object({
  /** key is the unique identifier for this schematic. */
  key: keyZ,
  /** name is a human-readable name for the schematic. */
  name: z.string(),
  /** snapshot indicates whether this schematic represents a saved snapshot state. */
  snapshot: z.boolean(),
  /** nodes contains all diagram nodes in the schematic. */
  nodes: array.nullishToEmpty(nodeZ),
  /** edges contains all connections between nodes. */
  edges: array.nullishToEmpty(edgeZ),
  /**
   * configs contains per-element configuration keyed by node or edge key. The
   * shape of each value is determined by the element's variant; the
   * wire format intentionally stores it as an opaque record.
   */
  configs: caseconv.preserveCase(record.nullishToEmpty(z.string(), record.unknownZ())),
});
export interface Schematic extends z.infer<typeof schematicZ> {}

export const edgeConfigPipeZ = segmentedEdgeConfigZ.extend({
  variant: z.literal("pipe"),
});
export interface EdgeConfigPipe extends z.infer<typeof edgeConfigPipeZ> {}

export const edgeConfigElectricZ = segmentedEdgeConfigZ.extend({
  variant: z.literal("electric"),
});
export interface EdgeConfigElectric extends z.infer<typeof edgeConfigElectricZ> {}

export const edgeConfigSecondaryZ = segmentedEdgeConfigZ.extend({
  variant: z.literal("secondary"),
});
export interface EdgeConfigSecondary extends z.infer<typeof edgeConfigSecondaryZ> {}

export const edgeConfigJacketedZ = segmentedEdgeConfigZ.extend({
  variant: z.literal("jacketed"),
});
export interface EdgeConfigJacketed extends z.infer<typeof edgeConfigJacketedZ> {}

export const edgeConfigHydraulicZ = segmentedEdgeConfigZ.extend({
  variant: z.literal("hydraulic"),
});
export interface EdgeConfigHydraulic extends z.infer<typeof edgeConfigHydraulicZ> {}

export const edgeConfigPneumaticZ = segmentedEdgeConfigZ.extend({
  variant: z.literal("pneumatic"),
});
export interface EdgeConfigPneumatic extends z.infer<typeof edgeConfigPneumaticZ> {}

export const edgeConfigDataZ = segmentedEdgeConfigZ.extend({
  variant: z.literal("data"),
});
export interface EdgeConfigData extends z.infer<typeof edgeConfigDataZ> {}

export const EDGE_CONFIG_TYPES = [
  "pipe",
  "electric",
  "secondary",
  "jacketed",
  "hydraulic",
  "pneumatic",
  "data",
] as const;
export const edgeConfigTypeZ = z.enum(EDGE_CONFIG_TYPES);
export type EdgeConfigType = z.infer<typeof edgeConfigTypeZ>;

/**
 * EdgeConfig is the per-edge configuration stored in the schematic configs map.
 * The variant selects the visual style of the connection.
 */
export const edgeConfigZ = z.discriminatedUnion("variant", [
  edgeConfigPipeZ,
  edgeConfigElectricZ,
  edgeConfigSecondaryZ,
  edgeConfigJacketedZ,
  edgeConfigHydraulicZ,
  edgeConfigPneumaticZ,
  edgeConfigDataZ,
]);
export type EdgeConfig = z.infer<typeof edgeConfigZ>;

export const EDGE_CONFIG_SCHEMAS: Record<EdgeConfigType, z.ZodType<EdgeConfig>> = {
  pipe: edgeConfigPipeZ,
  electric: edgeConfigElectricZ,
  secondary: edgeConfigSecondaryZ,
  jacketed: edgeConfigJacketedZ,
  hydraulic: edgeConfigHydraulicZ,
  pneumatic: edgeConfigPneumaticZ,
  data: edgeConfigDataZ,
};

export const newZ = schematicZ.partial({ key: true, snapshot: true });
export interface New extends z.input<typeof newZ> {}

export const ontologyID = ontology.createIDFactory<Key>("schematic");
export const TYPE_ONTOLOGY_ID = ontologyID("");
