// Copyright 2026 Synnax Labs, Inc.
//
// Use of this software is governed by the Business Source License included in the file
// licenses/BSL.txt.
//
// As of the Change Date specified in that file, in accordance with the Business Source
// License, use of this software will be governed by the Apache License, Version 2.0,
// included in the file licenses/APL.txt.

// Code generated by Oracle. DO NOT EDIT.

import { caseconv, record, spatial, uuid, zod } from "@synnaxlabs/x";
import { z } from "zod";

import { ontology } from "@/ontology";

/** Node is a diagram node representing a symbol in the schematic. */
export const nodeZ = z.object({
  /** key is the unique node identifier within the schematic. */
  key: z.string(),
  /** position is the top-left position of the node. */
  position: spatial.xyZ,
  /**
   * zIndex is the stacking order of the node within the schematic. Higher values render
   * above lower values. Set by the user via send-to-back / bring-to-front actions.
   */
  zIndex: zod.int16.default(0),
});
export interface Node extends z.infer<typeof nodeZ> {}

/**
 * Handle is a reference to a specific connection point on a specific node. For
 * schematics, param is the symbol handle key (e.g. inlet, outlet).
 */
export const handleZ = z.object({
  /** node is the node identifier. */
  node: z.string(),
  /** param is the connection point identifier on the node. */
  param: z.string(),
});
export interface Handle extends z.infer<typeof handleZ> {}

export const keyZ = z.uuid();
export type Key = z.infer<typeof keyZ>;

/** Edge is a connection between two nodes in the schematic. */
export const edgeZ = z.object({
  /** key is the unique edge identifier within the schematic. */
  key: z.string(),
  /** source is the source endpoint of the edge. */
  source: handleZ,
  /** target is the target endpoint of the edge. */
  target: handleZ,
});
export interface Edge extends z.infer<typeof edgeZ> {}

/**
 * Schematic is a visual diagram editor component for drawing system schematics, control
 * flows, and process diagrams. Schematics support interactive symbols, connection
 * handles, and dynamic state visualization.
 */
export const schematicZ = z.object({
  /** key is the unique identifier for this schematic. */
  key: keyZ.default(uuid.create),
  /** name is a human-readable name for the schematic. */
  name: z.string().min(1, "name is required"),
  /** snapshot indicates whether this schematic represents a saved snapshot state. */
  snapshot: z.boolean().default(false),
  /** nodes contains all diagram nodes in the schematic. */
  nodes: nodeZ.array().default(() => []),
  /** edges contains all connections between nodes. */
  edges: edgeZ.array().default(() => []),
  /**
   * configs contains per-element configuration keyed by node or edge key. The shape of
   * each value is determined by the element's variant; the wire format intentionally
   * stores it as an opaque record.
   */
  configs: caseconv.preserveCase(
    z.record(z.string(), record.unknownZ()).default(() => ({})),
  ),
});
export interface Schematic extends z.infer<typeof schematicZ> {}
export interface New extends z.input<typeof schematicZ> {}

export const ontologyID = ontology.createIDFactory<Key>("schematic");
export const TYPE_ONTOLOGY_ID = ontologyID("");
