// Copyright 2026 Synnax Labs, Inc.
//
// Use of this software is governed by the Business Source License included in the file
// licenses/BSL.txt.
//
// As of the Change Date specified in that file, in accordance with the Business Source
// License, use of this software will be governed by the Apache License, Version 2.0,
// included in the file licenses/APL.txt.

// Code generated by oracle. DO NOT EDIT.

package schematic

import (
	"encoding/json"
	"github.com/google/uuid"
	"github.com/synnaxlabs/x/color"
	"github.com/synnaxlabs/x/encoding/msgpack"
	"github.com/synnaxlabs/x/errors"
	"github.com/synnaxlabs/x/spatial"
)

// Key is a unique identifier for a schematic, represented as a UUID.
type Key = uuid.UUID

// Node is a diagram node representing a symbol in the schematic.
type Node struct {
	// Key is the unique node identifier within the schematic.
	Key string `json:"key" msgpack:"key"`
	// Position is the top-left position of the node.
	Position spatial.XY `json:"position" msgpack:"position"`
	// ZIndex is the stacking order of the node within the schematic. Higher values render
	// above lower values. Set by the user via send-to-back / bring-to-front actions.
	ZIndex int16 `json:"z_index" msgpack:"z_index"`
	// Measured is the rendered pixel size of the node. Populated by the renderer after the
	// node is mounted and used to keep diagram measurements consistent across re-renders.
	Measured spatial.Dimensions `json:"measured" msgpack:"measured"`
}

// Handle is a reference to a specific connection point on a specific node. For
// schematics, param is the symbol handle key (e.g. inlet, outlet).
type Handle struct {
	// Node is the node identifier.
	Node string `json:"node" msgpack:"node"`
	// Param is the connection point identifier on the node.
	Param string `json:"param" msgpack:"param"`
}

// Edge is a connection between two nodes in the schematic.
type Edge struct {
	// Key is the unique edge identifier within the schematic.
	Key string `json:"key" msgpack:"key"`
	// Source is the source endpoint of the edge.
	Source Handle `json:"source" msgpack:"source"`
	// Target is the target endpoint of the edge.
	Target Handle `json:"target" msgpack:"target"`
}

// Segment is a single orthogonal run in an edge's connector path.
type Segment struct {
	// Direction is the axis along which the segment travels.
	Direction spatial.Direction `json:"direction" msgpack:"direction"`
	// Length is the signed length of the segment in pixels.
	Length float64 `json:"length" msgpack:"length"`
}

// SegmentedEdgeConfig is the configuration shared by every segmented edge variant.
type SegmentedEdgeConfig struct {
	// Color is the stroke color of the edge.
	Color color.Color `json:"color" msgpack:"color"`
	// Segments is the ordered list of orthogonal runs that trace the connector path from
	// the source handle to the target handle.
	Segments []Segment `json:"segments" msgpack:"segments"`
}

// Schematic is a visual diagram editor component for drawing system schematics, control
// flows, and process diagrams. Schematics support interactive symbols, connection
// handles, and dynamic state visualization.
type Schematic struct {
	// Key is the unique identifier for this schematic.
	Key Key `json:"key" msgpack:"key"`
	// Name is a human-readable name for the schematic.
	Name string `json:"name" msgpack:"name"`
	// Snapshot indicates whether this schematic represents a saved snapshot state.
	Snapshot bool `json:"snapshot" msgpack:"snapshot"`
	// Nodes contains all diagram nodes in the schematic.
	Nodes []Node `json:"nodes" msgpack:"nodes"`
	// Edges contains all connections between nodes.
	Edges []Edge `json:"edges" msgpack:"edges"`
	// Configs contains per-element configuration keyed by node or edge key. The shape of
	// each value is determined by the element's variant; the wire format intentionally
	// stores it as an opaque record.
	Configs map[string]msgpack.EncodedJSON `json:"configs" msgpack:"configs"`
}

type EdgeConfigType string

const (
	EdgeConfigTypePipe      EdgeConfigType = "pipe"
	EdgeConfigTypeElectric  EdgeConfigType = "electric"
	EdgeConfigTypeSecondary EdgeConfigType = "secondary"
	EdgeConfigTypeJacketed  EdgeConfigType = "jacketed"
	EdgeConfigTypeHydraulic EdgeConfigType = "hydraulic"
	EdgeConfigTypePneumatic EdgeConfigType = "pneumatic"
	EdgeConfigTypeData      EdgeConfigType = "data"
)

type EdgeConfigVariant interface {
	isEdgeConfigVariant()
}

type EdgeConfigPipe struct {
	SegmentedEdgeConfig
}

func (EdgeConfigPipe) isEdgeConfigVariant() {}

type EdgeConfigElectric struct {
	SegmentedEdgeConfig
}

func (EdgeConfigElectric) isEdgeConfigVariant() {}

type EdgeConfigSecondary struct {
	SegmentedEdgeConfig
}

func (EdgeConfigSecondary) isEdgeConfigVariant() {}

type EdgeConfigJacketed struct {
	SegmentedEdgeConfig
}

func (EdgeConfigJacketed) isEdgeConfigVariant() {}

type EdgeConfigHydraulic struct {
	SegmentedEdgeConfig
}

func (EdgeConfigHydraulic) isEdgeConfigVariant() {}

type EdgeConfigPneumatic struct {
	SegmentedEdgeConfig
}

func (EdgeConfigPneumatic) isEdgeConfigVariant() {}

type EdgeConfigData struct {
	SegmentedEdgeConfig
}

func (EdgeConfigData) isEdgeConfigVariant() {}

// EdgeConfig is the per-edge configuration stored in the schematic configs map. The
// variant selects the visual style of the connection.
type EdgeConfig struct {
	Variant EdgeConfigVariant
}

func (u EdgeConfig) MarshalJSON() ([]byte, error) {
	var t EdgeConfigType
	switch u.Variant.(type) {
	case EdgeConfigPipe:
		t = EdgeConfigTypePipe
	case EdgeConfigElectric:
		t = EdgeConfigTypeElectric
	case EdgeConfigSecondary:
		t = EdgeConfigTypeSecondary
	case EdgeConfigJacketed:
		t = EdgeConfigTypeJacketed
	case EdgeConfigHydraulic:
		t = EdgeConfigTypeHydraulic
	case EdgeConfigPneumatic:
		t = EdgeConfigTypePneumatic
	case EdgeConfigData:
		t = EdgeConfigTypeData
	default:
		return nil, errors.Newf("EdgeConfig: nil or unknown variant %T", u.Variant)
	}
	raw, err := json.Marshal(u.Variant)
	if err != nil {
		return nil, err
	}
	fields := map[string]json.RawMessage{}
	if err := json.Unmarshal(raw, &fields); err != nil {
		return nil, err
	}
	tag, err := json.Marshal(t)
	if err != nil {
		return nil, err
	}
	fields["variant"] = tag
	return json.Marshal(fields)
}

func (u *EdgeConfig) UnmarshalJSON(data []byte) error {
	var disc struct {
		Type EdgeConfigType `json:"variant"`
	}
	if err := json.Unmarshal(data, &disc); err != nil {
		return err
	}
	switch disc.Type {
	case EdgeConfigTypePipe:
		var v EdgeConfigPipe
		if err := json.Unmarshal(data, &v); err != nil {
			return err
		}
		u.Variant = v
	case EdgeConfigTypeElectric:
		var v EdgeConfigElectric
		if err := json.Unmarshal(data, &v); err != nil {
			return err
		}
		u.Variant = v
	case EdgeConfigTypeSecondary:
		var v EdgeConfigSecondary
		if err := json.Unmarshal(data, &v); err != nil {
			return err
		}
		u.Variant = v
	case EdgeConfigTypeJacketed:
		var v EdgeConfigJacketed
		if err := json.Unmarshal(data, &v); err != nil {
			return err
		}
		u.Variant = v
	case EdgeConfigTypeHydraulic:
		var v EdgeConfigHydraulic
		if err := json.Unmarshal(data, &v); err != nil {
			return err
		}
		u.Variant = v
	case EdgeConfigTypePneumatic:
		var v EdgeConfigPneumatic
		if err := json.Unmarshal(data, &v); err != nil {
			return err
		}
		u.Variant = v
	case EdgeConfigTypeData:
		var v EdgeConfigData
		if err := json.Unmarshal(data, &v); err != nil {
			return err
		}
		u.Variant = v
	default:
		return errors.Newf("EdgeConfig: unknown variant %q", disc.Type)
	}
	return nil
}
