// Copyright 2026 Synnax Labs, Inc.
//
// Use of this software is governed by the Business Source License included in the file
// licenses/BSL.txt.
//
// As of the Change Date specified in that file, in accordance with the Business Source
// License, use of this software will be governed by the Apache License, Version 2.0,
// included in the file licenses/APL.txt.

// Code generated by oracle. DO NOT EDIT.

package channel

import (
	"context"
	"github.com/samber/lo"
	"github.com/synnaxlabs/synnax/pkg/distribution/cluster"
	"github.com/synnaxlabs/synnax/pkg/distribution/ontology"
	"github.com/synnaxlabs/synnax/pkg/distribution/search"
	"github.com/synnaxlabs/x/gorp"
	"github.com/synnaxlabs/x/telem"
)

// Retrieve is used to retrieve Channel records from the database using a
// builder pattern for constructing queries.
type Retrieve struct {
	baseTX     gorp.Tx
	gorp       gorp.Retrieve[Key, Channel]
	search     *search.Index
	searchTerm string
}

// Filter is a per-service filter that is bound to the Retrieve when passed to
// Where. Pure filters ignore the Retrieve argument; service-bound filters read
// from it (e.g. r.indexes, r.label, r.hostProvider) to evaluate. Use Match to
// construct one from a closure.
//
// Filter is a type alias for gorp.BoundFilter[Retrieve, K, E] so the
// composition helpers (Match / And / Or / Not) can be one-line wrappers
// around their gorp.*Bound counterparts instead of re-emitting closure
// plumbing per service.
type Filter = gorp.BoundFilter[Retrieve, Key, Channel]

// Match wraps a closure that needs the Retrieve into a Filter. The Retrieve
// value is supplied by Retrieve.Where at evaluation time.
func Match(f func(ctx gorp.Context, r Retrieve, e *Channel) (bool, error)) Filter {
	return gorp.MatchBound[Retrieve, Key, Channel](f)
}

// And returns a filter that matches when all provided filters match.
func And(fs ...Filter) Filter {
	return gorp.AndBound[Retrieve, Key, Channel](fs...)
}

// Or returns a filter that matches when any provided filter matches.
func Or(fs ...Filter) Filter {
	return gorp.OrBound[Retrieve, Key, Channel](fs...)
}

// Not returns a filter that inverts the provided filter.
func Not(f Filter) Filter {
	return gorp.NotBound[Retrieve, Key, Channel](f)
}

// Search sets a fuzzy search term that Retrieve will use to filter results.
func (r Retrieve) Search(term string) Retrieve { r.searchTerm = term; return r }

// MatchKeys returns a filter that restricts results to channels whose key
// matches any of the provided values. Composing MatchKeys at the top level
// of a Where clause (i.e. r.Where(MatchKeys(...))) dispatches Exec to the
// multi-get fast path; composing inside Or / Not falls back to a full scan.
func MatchKeys(keys ...Key) Filter {
	return func(_ Retrieve) gorp.Filter[Key, Channel] {
		return gorp.MatchKeys[Key, Channel](keys...)
	}
}

// MatchLeaseholders returns a filter for channels whose Leaseholder matches any of the provided values.
func MatchLeaseholders(vals ...cluster.NodeKey) Filter {
	return func(_ Retrieve) gorp.Filter[Key, Channel] {
		return gorp.Match(func(_ gorp.Context, e *Channel) (bool, error) {
			return lo.Contains(vals, e.Leaseholder), nil
		})
	}
}

// MatchDataTypes returns a filter for channels whose DataType matches any of the provided values.
func MatchDataTypes(vals ...telem.DataType) Filter {
	return func(_ Retrieve) gorp.Filter[Key, Channel] {
		return gorp.Match(func(_ gorp.Context, e *Channel) (bool, error) {
			return lo.Contains(vals, e.DataType), nil
		})
	}
}

// MatchIsIndex returns a filter for channels by their IsIndex field.
func MatchIsIndex(v bool) Filter {
	return func(_ Retrieve) gorp.Filter[Key, Channel] {
		return gorp.Match(func(_ gorp.Context, e *Channel) (bool, error) {
			return e.IsIndex == v, nil
		})
	}
}

// MatchInternal returns a filter for channels by their Internal field.
func MatchInternal(v bool) Filter {
	return func(_ Retrieve) gorp.Filter[Key, Channel] {
		return gorp.Match(func(_ gorp.Context, e *Channel) (bool, error) {
			return e.Internal == v, nil
		})
	}
}

// Where applies the provided filters to the query, binding each filter to the
// Retrieve so service-bound filters can read from r.indexes, r.label,
// r.hostProvider, etc.
func (r Retrieve) Where(filters ...Filter) Retrieve {
	bound := make([]gorp.Filter[Key, Channel], len(filters))
	for i, f := range filters {
		bound[i] = f(r)
	}
	r.gorp = r.gorp.Where(bound...)
	return r
}

// Entry binds the provided channel as the result container for the query. If
// multiple channels match, the first one is used.
func (r Retrieve) Entry(e *Channel) Retrieve {
	r.gorp = r.gorp.Entry(e)
	return r
}

// Entries binds the provided slice of channels as the result container for the query.
func (r Retrieve) Entries(es *[]Channel) Retrieve {
	r.gorp = r.gorp.Entries(es)
	return r
}

// Limit sets the maximum number of channels to return.
func (r Retrieve) Limit(limit int) Retrieve { r.gorp = r.gorp.Limit(limit); return r }

// Offset sets the starting index of the channels to return.
func (r Retrieve) Offset(offset int) Retrieve {
	r.gorp = r.gorp.Offset(offset)
	return r
}

func (r Retrieve) execSearch(ctx context.Context) (Retrieve, error) {
	if r.searchTerm == "" {
		return r, nil
	}
	ids, err := r.search.Search(ctx, search.Request{
		Type: ontology.ResourceTypeChannel,
		Term: r.searchTerm,
	})
	if err != nil {
		return Retrieve{}, err
	}
	keys, err := KeysFromOntologyIDs(ids)
	if err != nil {
		return Retrieve{}, err
	}
	return r.Where(MatchKeys(keys...)), nil
}

// Exec executes the query against the provided transaction.
func (r Retrieve) Exec(ctx context.Context, tx gorp.Tx) error {
	var err error
	if r, err = r.execSearch(ctx); err != nil {
		return err
	}
	return r.gorp.Exec(ctx, gorp.OverrideTx(r.baseTX, tx))
}

// Count returns the number of channels matching the query.
func (r Retrieve) Count(ctx context.Context, tx gorp.Tx) (int, error) {
	var err error
	if r, err = r.execSearch(ctx); err != nil {
		return 0, err
	}
	return r.gorp.Count(ctx, gorp.OverrideTx(r.baseTX, tx))
}

// Exists checks whether any channels match the query.
func (r Retrieve) Exists(ctx context.Context, tx gorp.Tx) (bool, error) {
	var err error
	if r, err = r.execSearch(ctx); err != nil {
		return false, err
	}
	return r.gorp.Exists(ctx, gorp.OverrideTx(r.baseTX, tx))
}
