# Copyright 2026 Synnax Labs, Inc.
#
# Use of this software is governed by the Business Source License included in the file
# licenses/BSL.txt.
#
# As of the Change Date specified in that file, in accordance with the Business Source
# License, use of this software will be governed by the Apache License, Version 2.0,
# included in the file licenses/APL.txt.

load("@rules_cc//cc:cc_library.bzl", "cc_library")
load("@rules_cc//cc:cc_test.bzl", "cc_test")

cc_library(
    name = "can",
    srcs = [
        "can.cpp",
        "timing.cpp",
    ],
    hdrs = [
        "can.h",
        "timing.h",
    ],
    visibility = ["//visibility:public"],
    deps = [
        "//client/cpp/can",
        "//driver/errors",
        "//x/cpp/errors",
        "//x/cpp/telem",
    ],
)

cc_library(
    name = "task",
    srcs = [
        "factory.cpp",
        "link.cpp",
        "read.cpp",
        "scan_task.cpp",
        "write.cpp",
    ],
    hdrs = [
        "factory.h",
        "link.h",
        "read.h",
        "scan_task.h",
        "write.h",
    ],
    visibility = ["//visibility:public"],
    deps = [
        ":can",
        "//client/cpp/can",
        "//driver/bus",
        "//driver/common",
        "//driver/task",
        "@abseil-cpp//absl/log",
    ],
)

cc_test(
    name = "can_test",
    srcs = [
        "can_test.cpp",
        "timing_test.cpp",
    ],
    deps = [
        ":can",
        "//driver/can/loopback",
        "//x/cpp/test",
        "@googletest//:gtest_main",
    ],
)

cc_test(
    name = "task_test",
    size = "small",
    srcs = ["task_test.cpp"],
    deps = [
        ":task",
        "//driver/bus",
        "//driver/bus/testutil",
        "//driver/can/loopback",
        "//driver/can/slcan",
        "//driver/pipeline/mock",
        "//x/cpp/test",
        "@googletest//:gtest_main",
    ],
)

cc_test(
    name = "factory_test",
    size = "small",
    srcs = ["factory_test.cpp"],
    tags = ["requires-core"],
    deps = [
        ":task",
        "//client/cpp/can",
        "//client/cpp/testutil",
        "//driver/bus/testutil",
        "//driver/bus/testutil:core",
        "//driver/can/loopback",
        "//x/cpp/test",
        "@googletest//:gtest_main",
    ],
)
