// Code generated by Oracle. DO NOT EDIT.

import { zod } from "@synnaxlabs/x";
import { z } from "zod";

import { ontology } from "@/ontology";

export const keyZ = z.uuid();
export type Key = z.infer<typeof keyZ>;

export const schematicZ = z.object({
  key: keyZ,
  name: z.string(),
  data: zod.stringifiedJSON(),
  snapshot: z.boolean(),
});
export type Schematic = z.infer<typeof schematicZ>;

export const newZ = z.object({
  key: keyZ.optional(),
  name: z.string(),
  data: zod.jsonStringifier(),
  snapshot: z.boolean().optional(),
});
export type New = z.input<typeof newZ>;

export const ontologyID = ontology.createIDFactory<Key>("schematic");
export const TYPE_ONTOLOGY_ID = ontologyID("");
