# Copyright 2026 Synnax Labs, Inc.
#
# Use of this software is governed by the Business Source License included in the file
# licenses/BSL.txt.
#
# As of the Change Date specified in that file, in accordance with the Business Source
# License, use of this software will be governed by the Apache License, Version 2.0,
# included in the file licenses/APL.txt.

exports_files(["VERSION"])

genrule(
    name = "version",
    srcs = ["VERSION"],
    outs = ["version.h"],
    cmd = """
        echo '#pragma once' > $@ &&
        echo '#define SYNNAX_VERSION \"'$$(cat $(location VERSION))'\"' >> $@ &&
        echo '#define SYNNAX_DRIVER_VERSION SYNNAX_VERSION' >> $@ &&
        echo '#define SYNNAX_BUILD_TIMESTAMP \"'$$(date "+%Y-%m-%d %H:%M:%S")'\"' >> $@
    """,
    stamp = 1,
    visibility = ["//visibility:public"],
)
