// Copyright 2026 Synnax Labs, Inc.
//
// Use of this software is governed by the Business Source License included in the file
// licenses/BSL.txt.
//
// As of the Change Date specified in that file, in accordance with the Business Source
// License, use of this software will be governed by the Apache License, Version 2.0,
// included in the file licenses/APL.txt.

// Code generated by oracle. DO NOT EDIT.

package label

import label "github.com/synnaxlabs/synnax/pkg/service/label/types"

// Key is a unique identifier for a label, represented as a UUID.
type Key = label.Key

// Label is a tagging and categorization entity with a name and associated color. Labels
// can be attached to resources like ranges for organization and filtering.
type Label = label.Label
