// Copyright 2026 Synnax Labs, Inc.
//
// Use of this software is governed by the Business Source License included in the file
// licenses/BSL.txt.
//
// As of the Change Date specified in that file, in accordance with the Business Source
// License, use of this software will be governed by the Apache License, Version 2.0,
// included in the file licenses/APL.txt.

// Package imex generates the portable import/export version constant for any Oracle
// struct that declares the bare `@go imex` marker. The constant equals the type's @go
// version, keeping the wire envelope version and the storage schema version a single
// sequence per resource.
package imex

import (
	"bytes"
	"text/template"

	"github.com/synnaxlabs/oracle/exec"
	"github.com/synnaxlabs/oracle/plugin"
	"github.com/synnaxlabs/oracle/plugin/domain"
	"github.com/synnaxlabs/oracle/plugin/go/internal/naming"
	"github.com/synnaxlabs/oracle/plugin/go/internal/versioning"
	"github.com/synnaxlabs/oracle/plugin/output"
	"github.com/synnaxlabs/x/errors"
)

// Options configures the imex plugin output.
type Options struct {
	// FileNamePattern is the basename written for each output package.
	FileNamePattern string
}

// DefaultOptions returns the production defaults: imex.gen.go.
func DefaultOptions() Options { return Options{FileNamePattern: "imex.gen.go"} }

// Plugin emits the generated imex version constant.
type Plugin struct{ Options Options }

// New constructs a Plugin with the given options.
func New(opts Options) *Plugin { return &Plugin{Options: opts} }

func (*Plugin) Name() string                { return "go/imex" }
func (*Plugin) Domains() []string           { return []string{"go"} }
func (*Plugin) Requires() []string          { return []string{"go/types"} }
func (*Plugin) Check(*plugin.Request) error { return nil }

var goPostWriter = &exec.PostWriter{Commands: [][]string{{"gofmt", "-w"}}}

// PostWrite runs gofmt on the generated files.
func (*Plugin) PostWrite(files []string) error { return goPostWriter.PostWrite(files) }

// Generate emits one imex.gen.go per output package whose type declares @go imex. It
// errors when a marked type lacks a @go version or when two types at the same path both
// carry the marker.
func (p *Plugin) Generate(req *plugin.Request) (*plugin.Response, error) {
	resp := &plugin.Response{}
	declared := make(map[string]string)
	for _, typ := range req.Resolutions.TypesWithDomain("go") {
		if !domain.HasExprFromType(typ, "go", "imex") {
			continue
		}
		outputPath := output.GetPath(typ, "go")
		if outputPath == "" {
			continue
		}
		version, ok := versioning.Version(typ)
		if !ok {
			return nil, errors.Newf(
				"%s declares @go imex without @go version", typ.QualifiedName,
			)
		}
		if prev, dup := declared[outputPath]; dup {
			return nil, errors.Newf(
				"duplicate @go imex declarations for %s: %s and %s",
				outputPath, prev, typ.QualifiedName,
			)
		}
		declared[outputPath] = typ.QualifiedName
		var buf bytes.Buffer
		if err := fileTemplate.Execute(&buf, &templateData{
			Package: naming.DerivePackageName(outputPath),
			Type:    naming.GetGoName(typ),
			Version: version,
		}); err != nil {
			return nil, err
		}
		resp.Files = append(resp.Files, plugin.File{
			Path:    outputPath + "/" + p.Options.FileNamePattern,
			Content: buf.Bytes(),
		})
	}
	return resp, nil
}

type templateData struct {
	Package string
	Type    string
	Version int
}

var fileTemplate = template.Must(template.New("go-imex").Parse(`// Code generated by oracle. DO NOT EDIT.

package {{.Package}}

import "github.com/synnaxlabs/synnax/pkg/service/imex"

// Version is the portable schema version stamped on exported {{.Type}} envelopes and
// the highest version import accepts. It equals the resource's schema version.
const Version imex.Version = {{.Version}}
`))
