VERSION 0.6

deps:
    FROM node:18.7.0-alpine3.16
    WORKDIR /pluto
    COPY package.json ./
    COPY yarn.lock ./
    RUN yarn install


build:
    ARG local=false
    FROM +deps
    COPY . .
    RUN yarn build
    IF [ "$local" = "true" ]
        SAVE ARTIFACT node_modules /node_modules AS LOCAL node_modules
        SAVE ARTIFACT dist /dist AS LOCAL dist
    ELSE
        SAVE ARTIFACT .
    END