// Copyright 2026 Synnax Labs, Inc.
//
// Use of this software is governed by the Business Source License included in the file
// licenses/BSL.txt.
//
// As of the Change Date specified in that file, in accordance with the Business Source
// License, use of this software will be governed by the Apache License, Version 2.0,
// included in the file licenses/APL.txt.

// Code generated by oracle. DO NOT EDIT.

package v1

import (
	"context"
	compilerv0 "github.com/synnaxlabs/arc/compiler/types/v0"
	irv1 "github.com/synnaxlabs/arc/ir/types/v1"
	v0 "github.com/synnaxlabs/arc/program/types/v0"
)

func autoMigrateProgram(ctx context.Context, old v0.Program) (Program, error) {
	ir, err := irv1.MigrateIR(ctx, old.IR)
	if err != nil {
		return Program{}, err
	}
	return Program{
		IR:     ir,
		Output: compilerv0.Output(old.Output),
	}, nil
}
