# Copyright 2026 Synnax Labs, Inc.
#
# Use of this software is governed by the Business Source License included in the file
# licenses/BSL.txt.
#
# As of the Change Date specified in that file, in accordance with the Business Source
# License, use of this software will be governed by the Apache License, Version 2.0,
# included in the file licenses/APL.txt.

load("@rules_cc//cc:cc_library.bzl", "cc_library")
load("@rules_cc//cc:cc_test.bzl", "cc_test")

cc_library(
    name = "engine",
    srcs = [
        "engine.cpp",
        "pool.cpp",
        "reader.cpp",
        "writer.cpp",
    ],
    hdrs = [
        "engine.h",
        "pool.h",
    ],
    visibility = ["//visibility:public"],
    deps = [
        "//driver/ethercat/errors",
        "//driver/ethercat/master",
        "//driver/ethercat/telem",
        "//x/cpp/breaker",
        "//x/cpp/lib",
        "//x/cpp/loop",
        "//x/cpp/telem",
        "//x/cpp/thread",
        "//x/cpp/thread/rt",
    ],
)

cc_test(
    name = "engine_test",
    srcs = ["engine_test.cpp"],
    visibility = ["//visibility:public"],
    deps = [
        "//driver/ethercat/engine",
        "//driver/ethercat/mock",
        "//x/cpp/test",
        "@googletest//:gtest_main",
    ],
)
