// Copyright 2025 Synnax Labs, Inc.
//
// Use of this software is governed by the Business Source License included in the file
// licenses/BSL.txt.
//
// As of the Change Date specified in that file, in accordance with the Business Source
// License, use of this software will be governed by the Apache License, Version 2.0,
// included in the file licenses/APL.txt.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: core/pkg/api/grpc/rack/rack.proto

package rack

import (
	pb "github.com/synnaxlabs/synnax/pkg/service/rack/pb"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Racks         []*pb.Rack             `protobuf:"bytes,1,rep,name=racks,proto3" json:"racks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRequest) Reset() {
	*x = CreateRequest{}
	mi := &file_core_pkg_api_grpc_rack_rack_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRequest) ProtoMessage() {}

func (x *CreateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_core_pkg_api_grpc_rack_rack_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRequest.ProtoReflect.Descriptor instead.
func (*CreateRequest) Descriptor() ([]byte, []int) {
	return file_core_pkg_api_grpc_rack_rack_proto_rawDescGZIP(), []int{0}
}

func (x *CreateRequest) GetRacks() []*pb.Rack {
	if x != nil {
		return x.Racks
	}
	return nil
}

type CreateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Racks         []*pb.Rack             `protobuf:"bytes,1,rep,name=racks,proto3" json:"racks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateResponse) Reset() {
	*x = CreateResponse{}
	mi := &file_core_pkg_api_grpc_rack_rack_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateResponse) ProtoMessage() {}

func (x *CreateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_core_pkg_api_grpc_rack_rack_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateResponse.ProtoReflect.Descriptor instead.
func (*CreateResponse) Descriptor() ([]byte, []int) {
	return file_core_pkg_api_grpc_rack_rack_proto_rawDescGZIP(), []int{1}
}

func (x *CreateResponse) GetRacks() []*pb.Rack {
	if x != nil {
		return x.Racks
	}
	return nil
}

type RetrieveRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Keys          []uint32               `protobuf:"varint,1,rep,packed,name=keys,proto3" json:"keys,omitempty"`
	Names         []string               `protobuf:"bytes,2,rep,name=names,proto3" json:"names,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RetrieveRequest) Reset() {
	*x = RetrieveRequest{}
	mi := &file_core_pkg_api_grpc_rack_rack_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RetrieveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RetrieveRequest) ProtoMessage() {}

func (x *RetrieveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_core_pkg_api_grpc_rack_rack_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RetrieveRequest.ProtoReflect.Descriptor instead.
func (*RetrieveRequest) Descriptor() ([]byte, []int) {
	return file_core_pkg_api_grpc_rack_rack_proto_rawDescGZIP(), []int{2}
}

func (x *RetrieveRequest) GetKeys() []uint32 {
	if x != nil {
		return x.Keys
	}
	return nil
}

func (x *RetrieveRequest) GetNames() []string {
	if x != nil {
		return x.Names
	}
	return nil
}

type RetrieveResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Racks         []*pb.Rack             `protobuf:"bytes,1,rep,name=racks,proto3" json:"racks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RetrieveResponse) Reset() {
	*x = RetrieveResponse{}
	mi := &file_core_pkg_api_grpc_rack_rack_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RetrieveResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RetrieveResponse) ProtoMessage() {}

func (x *RetrieveResponse) ProtoReflect() protoreflect.Message {
	mi := &file_core_pkg_api_grpc_rack_rack_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RetrieveResponse.ProtoReflect.Descriptor instead.
func (*RetrieveResponse) Descriptor() ([]byte, []int) {
	return file_core_pkg_api_grpc_rack_rack_proto_rawDescGZIP(), []int{3}
}

func (x *RetrieveResponse) GetRacks() []*pb.Rack {
	if x != nil {
		return x.Racks
	}
	return nil
}

type DeleteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Keys          []uint32               `protobuf:"varint,1,rep,packed,name=keys,proto3" json:"keys,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteRequest) Reset() {
	*x = DeleteRequest{}
	mi := &file_core_pkg_api_grpc_rack_rack_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRequest) ProtoMessage() {}

func (x *DeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_core_pkg_api_grpc_rack_rack_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRequest.ProtoReflect.Descriptor instead.
func (*DeleteRequest) Descriptor() ([]byte, []int) {
	return file_core_pkg_api_grpc_rack_rack_proto_rawDescGZIP(), []int{4}
}

func (x *DeleteRequest) GetKeys() []uint32 {
	if x != nil {
		return x.Keys
	}
	return nil
}

var File_core_pkg_api_grpc_rack_rack_proto protoreflect.FileDescriptor

const file_core_pkg_api_grpc_rack_rack_proto_rawDesc = "" +
	"\n" +
	"!core/pkg/api/grpc/rack/rack.proto\x12\tgrpc.rack\x1a#core/pkg/service/rack/pb/rack.proto\x1a\x1bgoogle/protobuf/empty.proto\"<\n" +
	"\rCreateRequest\x12+\n" +
	"\x05racks\x18\x01 \x03(\v2\x15.service.rack.pb.RackR\x05racks\"=\n" +
	"\x0eCreateResponse\x12+\n" +
	"\x05racks\x18\x01 \x03(\v2\x15.service.rack.pb.RackR\x05racks\";\n" +
	"\x0fRetrieveRequest\x12\x12\n" +
	"\x04keys\x18\x01 \x03(\rR\x04keys\x12\x14\n" +
	"\x05names\x18\x02 \x03(\tR\x05names\"?\n" +
	"\x10RetrieveResponse\x12+\n" +
	"\x05racks\x18\x01 \x03(\v2\x15.service.rack.pb.RackR\x05racks\"#\n" +
	"\rDeleteRequest\x12\x12\n" +
	"\x04keys\x18\x01 \x03(\rR\x04keys2P\n" +
	"\x11RackCreateService\x12;\n" +
	"\x04Exec\x12\x18.grpc.rack.CreateRequest\x1a\x19.grpc.rack.CreateResponse2V\n" +
	"\x13RackRetrieveService\x12?\n" +
	"\x04Exec\x12\x1a.grpc.rack.RetrieveRequest\x1a\x1b.grpc.rack.RetrieveResponse2M\n" +
	"\x11RackDeleteService\x128\n" +
	"\x04Exec\x12\x18.grpc.rack.DeleteRequest\x1a\x16.google.protobuf.EmptyB\x8f\x01\n" +
	"\rcom.grpc.rackB\tRackProtoP\x01Z.github.com/synnaxlabs/synnax/pkg/api/grpc/rack\xa2\x02\x03GRX\xaa\x02\tGrpc.Rack\xca\x02\tGrpc\\Rack\xe2\x02\x15Grpc\\Rack\\GPBMetadata\xea\x02\n" +
	"Grpc::Rackb\x06proto3"

var (
	file_core_pkg_api_grpc_rack_rack_proto_rawDescOnce sync.Once
	file_core_pkg_api_grpc_rack_rack_proto_rawDescData []byte
)

func file_core_pkg_api_grpc_rack_rack_proto_rawDescGZIP() []byte {
	file_core_pkg_api_grpc_rack_rack_proto_rawDescOnce.Do(func() {
		file_core_pkg_api_grpc_rack_rack_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_core_pkg_api_grpc_rack_rack_proto_rawDesc), len(file_core_pkg_api_grpc_rack_rack_proto_rawDesc)))
	})
	return file_core_pkg_api_grpc_rack_rack_proto_rawDescData
}

var file_core_pkg_api_grpc_rack_rack_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_core_pkg_api_grpc_rack_rack_proto_goTypes = []any{
	(*CreateRequest)(nil),    // 0: grpc.rack.CreateRequest
	(*CreateResponse)(nil),   // 1: grpc.rack.CreateResponse
	(*RetrieveRequest)(nil),  // 2: grpc.rack.RetrieveRequest
	(*RetrieveResponse)(nil), // 3: grpc.rack.RetrieveResponse
	(*DeleteRequest)(nil),    // 4: grpc.rack.DeleteRequest
	(*pb.Rack)(nil),          // 5: service.rack.pb.Rack
	(*emptypb.Empty)(nil),    // 6: google.protobuf.Empty
}
var file_core_pkg_api_grpc_rack_rack_proto_depIdxs = []int32{
	5, // 0: grpc.rack.CreateRequest.racks:type_name -> service.rack.pb.Rack
	5, // 1: grpc.rack.CreateResponse.racks:type_name -> service.rack.pb.Rack
	5, // 2: grpc.rack.RetrieveResponse.racks:type_name -> service.rack.pb.Rack
	0, // 3: grpc.rack.RackCreateService.Exec:input_type -> grpc.rack.CreateRequest
	2, // 4: grpc.rack.RackRetrieveService.Exec:input_type -> grpc.rack.RetrieveRequest
	4, // 5: grpc.rack.RackDeleteService.Exec:input_type -> grpc.rack.DeleteRequest
	1, // 6: grpc.rack.RackCreateService.Exec:output_type -> grpc.rack.CreateResponse
	3, // 7: grpc.rack.RackRetrieveService.Exec:output_type -> grpc.rack.RetrieveResponse
	6, // 8: grpc.rack.RackDeleteService.Exec:output_type -> google.protobuf.Empty
	6, // [6:9] is the sub-list for method output_type
	3, // [3:6] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_core_pkg_api_grpc_rack_rack_proto_init() }
func file_core_pkg_api_grpc_rack_rack_proto_init() {
	if File_core_pkg_api_grpc_rack_rack_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_core_pkg_api_grpc_rack_rack_proto_rawDesc), len(file_core_pkg_api_grpc_rack_rack_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   3,
		},
		GoTypes:           file_core_pkg_api_grpc_rack_rack_proto_goTypes,
		DependencyIndexes: file_core_pkg_api_grpc_rack_rack_proto_depIdxs,
		MessageInfos:      file_core_pkg_api_grpc_rack_rack_proto_msgTypes,
	}.Build()
	File_core_pkg_api_grpc_rack_rack_proto = out.File
	file_core_pkg_api_grpc_rack_rack_proto_goTypes = nil
	file_core_pkg_api_grpc_rack_rack_proto_depIdxs = nil
}
