# Copyright 2026 Synnax Labs, Inc.
#
# Use of this software is governed by the Business Source License included in the file
# licenses/BSL.txt.
#
# As of the Change Date specified in that file, in accordance with the Business Source
# License, use of this software will be governed by the Apache License, Version 2.0,
# included in the file licenses/APL.txt.

load("@rules_cc//cc:cc_library.bzl", "cc_library")
load("@rules_cc//cc:cc_test.bzl", "cc_test")

cc_library(
    name = "reporter",
    hdrs = ["reporter.h"],
    visibility = ["//visibility:public"],
)

cc_library(
    name = "arc",
    srcs = ["factory.cpp"],
    hdrs = [
        "arc.h",
        "task.h",
    ],
    visibility = ["//visibility:public"],
    deps = [
        "//arc/cpp/program",
        "//arc/cpp/runtime",
        "//arc/cpp/runtime/loop",
        "//client/cpp/arc",
        "//driver/arc/ranges",
        "//driver/arc/status",
        "//driver/bypass",
        "//driver/common",
        "//driver/pipeline",
        "//driver/task",
        "//x/cpp/breaker",
        "//x/cpp/json",
        "//x/cpp/telem",
        "//x/cpp/uuid",
    ],
)

cc_test(
    name = "arc_test",
    srcs = ["arc_test.cpp"],
    deps = [
        "//client/cpp/testutil",
        "//driver/arc",
        "//driver/pipeline/mock",
        "//driver/task",
        "//x/cpp/defer",
        "//x/cpp/test",
        "@googletest//:gtest_main",
    ],
)
