#  Copyright 2025 Synnax Labs, Inc.
#
#  Use of this software is governed by the Business Source License included in the file
#  licenses/BSL.txt.
#
#  As of the Change Date specified in that file, in accordance with the Business Source
#  License, use of this software will be governed by the Apache License, Version 2.0,
#  included in the file licenses/APL.txt.


import pytest

from synnax import ValidationError
from synnax.hardware.ni import (
    AIVoltageChan,
    AnalogReadTask,
    AnalogReadTaskConfig,
    AnalogWriteConfig,
    CounterWriteConfig,
    DigitalReadConfig,
    DigitalWriteConfig,
)


@pytest.mark.ni
class TestNITask:
    def test_parse_analog_read_task(self):
        data = {
            "sample_rate": 10,
            "stream_rate": 5,
            "auto_start": True,
            "channels": [
                {
                    "name": "",
                    "device": "474503CF-49FD-11EF-80E5-91C59E7C9645",
                    "key": "k09AWoiyLxN",
                    "type": "ai_voltage",
                    "terminal_config": "Cfg_Default",
                    "channel": 1048582,
                    "port": 0,
                    "enabled": True,
                    "min_val": 0,
                    "max_val": 1,
                    "units": "Volts",
                    "custom_scale": {"type": "none"},
                },
                {
                    "name": "",
                    "device": "474503CF-49FD-11EF-80E5-91C59E7C9645",
                    "key": "Ar7iVF6Tjzf",
                    "type": "ai_thermocouple",
                    "channel": 1048583,
                    "port": 1,
                    "enabled": True,
                    "min_val": 0,
                    "max_val": 1,
                    "units": "DegC",
                    "thermocouple_type": "J",
                    "cjc_source": "BuiltIn",
                    "cjc_val": 0,
                    "cjc_port": 0,
                },
                {
                    "name": "",
                    "device": "474503CF-49FD-11EF-80E5-91C59E7C9645",
                    "key": "3zRNCIt6H0A",
                    "channel": 1048584,
                    "type": "ai_rtd",
                    "port": 2,
                    "enabled": True,
                    "min_val": 0,
                    "max_val": 1,
                    "units": "DegC",
                    "rtd_type": "Pt3750",
                    "resistance_config": "2Wire",
                    "current_excit_source": "Internal",
                    "current_excit_val": 0,
                    "r0": 0,
                },
                {
                    "name": "",
                    "device": "474503CF-49FD-11EF-80E5-91C59E7C9645",
                    "key": "2dYSMHhZHtt",
                    "type": "ai_pressure_bridge_two_point_lin",
                    "channel": 1048585,
                    "port": 3,
                    "enabled": True,
                    "min_val": 0,
                    "max_val": 1,
                    "terminal_config": "Cfg_Default",
                    "units": "PoundsPerSquareInch",
                    "bridge_config": "FullBridge",
                    "voltage_excit_source": "Internal",
                    "voltage_excit_val": 0,
                    "nominal_bridge_resistance": 0,
                    "electrical_units": "mVoltsPerVolt",
                    "physical_units": "PoundsPerSquareInch",
                    "first_electrical_val": 0,
                    "first_physical_val": 0,
                    "second_electrical_val": 1,
                    "second_physical_val": 1,
                    "custom_scale": {"type": "none"},
                },
                {
                    "name": "",
                    "device": "474503CF-49FD-11EF-80E5-91C59E7C9645",
                    "key": "h6aNsbt9iXo",
                    "type": "ai_accel",
                    "channel": 1048586,
                    "port": 4,
                    "units": "g",
                    "enabled": True,
                    "min_val": 0,
                    "max_val": 1,
                    "terminal_config": "Cfg_Default",
                    "sensitivity": 0,
                    "sensitivity_units": "mVoltsPerG",
                    "current_excit_source": "Internal",
                    "current_excit_val": 0,
                    "custom_scale": {"type": "none"},
                },
                {
                    "name": "",
                    "device": "474503CF-49FD-11EF-80E5-91C59E7C9645",
                    "key": "88xDWnrIF90",
                    "type": "ai_bridge",
                    "units": "mVoltsPerVolt",
                    "channel": 1048587,
                    "port": 5,
                    "enabled": True,
                    "min_val": 0,
                    "max_val": 1,
                    "terminal_config": "Cfg_Default",
                    "bridge_config": "FullBridge",
                    "voltage_excit_source": "Internal",
                    "voltage_excit_val": 0,
                    "nominal_bridge_resistance": 1,
                    "custom_scale": {"type": "none"},
                },
                {
                    "name": "",
                    "device": "474503CF-49FD-11EF-80E5-91C59E7C9645",
                    "key": "9AvgGUrtyvw",
                    "channel": 1048588,
                    "port": 6,
                    "type": "ai_current",
                    "enabled": True,
                    "min_val": 0,
                    "max_val": 1,
                    "terminal_config": "Cfg_Default",
                    "units": "Amps",
                    "shunt_resistor_loc": "Default",
                    "ext_shunt_resistor_val": 1,
                    "custom_scale": {"type": "none"},
                },
                {
                    "name": "",
                    "device": "474503CF-49FD-11EF-80E5-91C59E7C9645",
                    "key": "fo88BkNspw0",
                    "type": "ai_force_bridge_table",
                    "channel": 1048589,
                    "port": 7,
                    "enabled": True,
                    "min_val": 0,
                    "max_val": 1,
                    "units": "Newtons",
                    "bridge_config": "FullBridge",
                    "voltage_excit_source": "Internal",
                    "voltage_excit_val": 0,
                    "nominal_bridge_resistance": 0,
                    "electrical_units": "mVoltsPerVolt",
                    "electrical_vals": [],
                    "physical_units": "Newtons",
                    "physical_vals": [],
                    "custom_scale": {"type": "none"},
                },
                {
                    "name": "",
                    "device": "474503CF-49FD-11EF-80E5-91C59E7C9645",
                    "key": "FN8PbpvQvBt",
                    "type": "ai_force_bridge_two_point_lin",
                    "channel": 1048590,
                    "port": 8,
                    "enabled": True,
                    "min_val": 0,
                    "max_val": 1,
                    "terminal_config": "Cfg_Default",
                    "units": "Newtons",
                    "bridge_config": "FullBridge",
                    "voltage_excit_source": "Internal",
                    "voltage_excit_val": 0,
                    "nominal_bridge_resistance": 0,
                    "electrical_units": "mVoltsPerVolt",
                    "physical_units": "Newtons",
                    "first_electrical_val": 0,
                    "first_physical_val": 0,
                    "second_electrical_val": 1,
                    "second_physical_val": 1,
                    "custom_scale": {"type": "none"},
                },
                {
                    "name": "",
                    "device": "474503CF-49FD-11EF-80E5-91C59E7C9645",
                    "key": "s3KtqxSs6cD",
                    "type": "ai_force_iepe",
                    "channel": 1048591,
                    "port": 9,
                    "enabled": True,
                    "min_val": 0,
                    "max_val": 1,
                    "terminal_config": "Cfg_Default",
                    "units": "Newtons",
                    "sensitivity": 0,
                    "sensitivity_units": "mVoltsPerVolt",
                    "current_excit_source": "Internal",
                    "current_excit_val": 0,
                    "custom_scale": {"type": "none"},
                },
                {
                    "name": "",
                    "device": "474503CF-49FD-11EF-80E5-91C59E7C9645",
                    "key": "VNUF26p0JC2",
                    "type": "ai_microphone",
                    "channel": 1048592,
                    "port": 10,
                    "enabled": True,
                    "terminal_config": "Cfg_Default",
                    "mic_sensitivity": 0,
                    "max_snd_press_level": 0,
                    "current_excit_source": "Internal",
                    "current_excit_val": 0,
                    "units": "Pascals",
                    "custom_scale": {"type": "none"},
                },
                {
                    "name": "",
                    "device": "474503CF-49FD-11EF-80E5-91C59E7C9645",
                    "key": "9b5IgxtRYIx",
                    "type": "ai_pressure_bridge_table",
                    "channel": 1048593,
                    "port": 11,
                    "enabled": True,
                    "min_val": 0,
                    "max_val": 1,
                    "units": "PoundsPerSquareInch",
                    "bridge_config": "FullBridge",
                    "voltage_excit_source": "Internal",
                    "voltage_excit_val": 0,
                    "nominal_bridge_resistance": 0,
                    "electrical_units": "mVoltsPerVolt",
                    "electrical_vals": [],
                    "physical_units": "PoundsPerSquareInch",
                    "physical_vals": [],
                    "custom_scale": {"type": "none"},
                },
                {
                    "name": "",
                    "device": "474503CF-49FD-11EF-80E5-91C59E7C9645",
                    "key": "i6dz8FDpPwp",
                    "type": "ai_resistance",
                    "channel": 1048594,
                    "port": 12,
                    "enabled": True,
                    "min_val": 0,
                    "max_val": 1,
                    "terminal_config": "Cfg_Default",
                    "units": "Ohms",
                    "resistance_config": "2Wire",
                    "current_excit_source": "Internal",
                    "current_excit_val": 0,
                    "custom_scale": {"type": "none"},
                },
                {
                    "name": "",
                    "device": "474503CF-49FD-11EF-80E5-91C59E7C9645",
                    "key": "hfADiXS6IMR",
                    "type": "ai_strain_gauge",
                    "channel": 1048595,
                    "port": 13,
                    "enabled": True,
                    "min_val": 0,
                    "max_val": 1,
                    "terminal_config": "Cfg_Default",
                    "units": "strain",
                    "strain_config": "full-bridge-I",
                    "voltage_excit_source": "Internal",
                    "voltage_excit_val": 0,
                    "gage_factor": 0,
                    "initial_bridge_voltage": 0,
                    "nominal_gage_resistance": 0,
                    "poisson_ratio": 0,
                    "lead_wire_resistance": 0,
                    "custom_scale": {"type": "none"},
                },
                {
                    "name": "",
                    "device": "474503CF-49FD-11EF-80E5-91C59E7C9645",
                    "key": "afSn8BOZ8Nv",
                    "type": "ai_temp_builtin",
                    "channel": 1048596,
                    "port": 14,
                    "enabled": True,
                    "units": "DegC",
                },
                {
                    "name": "",
                    "device": "474503CF-49FD-11EF-80E5-91C59E7C9645",
                    "key": "LuzjMHtLTR9",
                    "type": "ai_torque_bridge_table",
                    "channel": 1048597,
                    "port": 15,
                    "enabled": True,
                    "min_val": 0,
                    "max_val": 1,
                    "units": "NewtonMeters",
                    "bridge_config": "FullBridge",
                    "voltage_excit_source": "Internal",
                    "voltage_excit_val": 0,
                    "nominal_bridge_resistance": 0,
                    "electrical_units": "mVoltsPerVolt",
                    "electrical_vals": [],
                    "physical_units": "NewtonMeters",
                    "physical_vals": [],
                    "custom_scale": {"type": "none"},
                },
                {
                    "name": "",
                    "device": "474503CF-49FD-11EF-80E5-91C59E7C9645",
                    "key": "IPJbBSbVf7F",
                    "type": "ai_torque_bridge_two_point_lin",
                    "channel": 1048598,
                    "port": 16,
                    "enabled": True,
                    "min_val": 0,
                    "max_val": 1,
                    "units": "NewtonMeters",
                    "bridge_config": "FullBridge",
                    "voltage_excit_source": "Internal",
                    "voltage_excit_val": 0,
                    "nominal_bridge_resistance": 0,
                    "electrical_units": "mVoltsPerVolt",
                    "physical_units": "NewtonMeters",
                    "first_electrical_val": 0,
                    "first_physical_val": 0,
                    "second_electrical_val": 1,
                    "second_physical_val": 1,
                    "custom_scale": {"type": "none"},
                },
                {
                    "name": "",
                    "device": "474503CF-49FD-11EF-80E5-91C59E7C9645",
                    "key": "ZayvFgaGurP",
                    "type": "ai_velocity_iepe",
                    "channel": 1048599,
                    "port": 17,
                    "enabled": True,
                    "terminal_config": "Cfg_Default",
                    "min_val": 0,
                    "max_val": 1,
                    "units": "MetersPerSecond",
                    "sensitivity": 0,
                    "sensitivity_units": "MillivoltsPerMillimeterPerSecond",
                    "current_excit_source": "Internal",
                    "current_excit_val": 0,
                    "custom_scale": {"type": "none"},
                },
            ],
            "data_saving": True,
        }
        AnalogReadTaskConfig.model_validate(data)

    def test_parse_analog_read_task_default_device_none_provided(self):
        with pytest.raises(ValidationError):
            AnalogReadTask(
                sample_rate=10,
                stream_rate=5,
                channels=[
                    AIVoltageChan(
                        key="k09AWoiyLxN",
                        terminal_config="Cfg_Default",
                        channel=1048582,
                        port=0,
                        enabled=True,
                        min_val=0,
                        max_val=1,
                        units="Volts",
                    )
                ],
            )

    def test_parse_analog_read_task_default_device_provided(self):
        AnalogReadTask(
            device="474503CF-49FD-11EF-80E5-91C59E7C9645",
            sample_rate=10,
            stream_rate=5,
            channels=[
                AIVoltageChan(
                    key="k09AWoiyLxN",
                    terminal_config="Cfg_Default",
                    channel=1048582,
                    port=0,
                    enabled=True,
                    min_val=0,
                    max_val=1,
                    units="Volts",
                )
            ],
        )

    def test_parse_analog_write_task(self):
        data = {
            "device": "474503CF-49FD-11EF-80E5-91C59E7C9645",
            "state_rate": 10,
            "channels": [
                {
                    "key": "AnalogOut1",
                    "type": "ao_voltage",
                    "enabled": True,
                    "device": "474503CF-49FD-11EF-80E5-91C59E7C9645",
                    "cmd_channel": 1048610,
                    "state_channel": 1048611,
                    "port": 0,
                    "min_val": -10.0,
                    "max_val": 10.0,
                    "units": "Volts",
                    "custom_scale": {"type": "none"},
                }
            ],
            "data_saving": True,
            "auto_start": False,
        }
        AnalogWriteConfig.model_validate(data)

    def test_parse_counter_write_task(self):
        data = {
            "device": "474503CF-49FD-11EF-80E5-91C59E7C9645",
            "state_rate": 100,
            "channels": [
                {
                    "key": "CounterOut1",
                    "type": "co_pulse_output",
                    "enabled": True,
                    "device": "474503CF-49FD-11EF-80E5-91C59E7C9645",
                    "cmd_channel": 1048620,
                    "state_channel": 1048621,
                    "port": 0,
                    "idle_state": "Low",
                    "initial_delay": 0.0,
                    "high_time": 0.01,
                    "low_time": 0.01,
                    "min_val": 0.0,
                    "max_val": 1.0,
                    "units": "Seconds",
                }
            ],
            "data_saving": False,
            "auto_start": True,
        }
        CounterWriteConfig.model_validate(data)

    def test_parse_digital_read_task(self):
        data = {
            "device": "474503CF-49FD-11EF-80E5-91C59E7C9645",
            "channels": [
                {
                    "key": "5DSZbDQy6a4",
                    "type": "digital_input",
                    "enabled": True,
                    "port": 0,
                    "line": 1,
                    "channel": 1048601,
                }
            ],
            "sample_rate": 50,
            "stream_rate": 25,
            "data_saving": True,
            "auto_start": False,
        }
        DigitalReadConfig.model_validate(data)

    def test_parse_digital_write_task(self):
        data = {
            "device": "474503CF-49FD-11EF-80E5-91C59E7C9645",
            "state_rate": 10,
            "channels": [
                {
                    "key": "Xph3kNL7twt",
                    "type": "digital_output",
                    "enabled": True,
                    "cmd_channel": 1048605,
                    "state_channel": 1048603,
                    "port": 0,
                    "line": 1,
                }
            ],
            "data_saving": True,
            "auto_start": True,
        }
        DigitalWriteConfig.model_validate(data)
