// Copyright 2026 Synnax Labs, Inc.
//
// Use of this software is governed by the Business Source License included in the file
// licenses/BSL.txt.
//
// As of the Change Date specified in that file, in accordance with the Business Source
// License, use of this software will be governed by the Apache License, Version 2.0,
// included in the file licenses/APL.txt.

// Code generated by oracle. DO NOT EDIT.

package ontology_test

import (
	"bytes"
	"testing"

	. "github.com/onsi/ginkgo/v2"
	. "github.com/onsi/gomega"
	"github.com/synnaxlabs/x/encoding/orc"

	"github.com/synnaxlabs/synnax/pkg/distribution/ontology"
)

var _ = Describe("Codec", func() {
	Describe("ID", func() {
		DescribeTable("should round-trip encode and decode",
			func(original ontology.ID) {
				w := orc.NewWriter(0)
				Expect(original.EncodeOrc(w)).To(Succeed())
				var decoded ontology.ID
				r := orc.NewReader(nil)
				r.ResetBytes(w.Bytes())
				Expect(decoded.DecodeOrc(r)).To(Succeed())
				Expect(decoded).To(Equal(original))
			},
			Entry("fully populated", ontology.ID{Type: ontology.ResourceType("arc"), Key: "test_2"}),
			Entry("zero values", ontology.ID{Type: ontology.ResourceType(""), Key: ""}),
		)
	})
	Describe("Relationship", func() {
		DescribeTable("should round-trip encode and decode",
			func(original ontology.Relationship) {
				w := orc.NewWriter(0)
				Expect(original.EncodeOrc(w)).To(Succeed())
				var decoded ontology.Relationship
				r := orc.NewReader(nil)
				r.ResetBytes(w.Bytes())
				Expect(decoded.DecodeOrc(r)).To(Succeed())
				Expect(decoded).To(Equal(original))
			},
			Entry("fully populated", ontology.Relationship{
				From: ontology.ID{Type: ontology.ResourceType("arc"), Key: "test_3"},
				Type: ontology.RelationshipType("test_4"),
				To:   ontology.ID{Type: ontology.ResourceType("arc"), Key: "test_7"},
			}),
			Entry("zero values", ontology.Relationship{
				From: ontology.ID{Type: ontology.ResourceType(""), Key: ""},
				Type: ontology.RelationshipType(""),
				To:   ontology.ID{Type: ontology.ResourceType(""), Key: ""},
			}),
		)
	})
	Describe("Resource", func() {
		DescribeTable("should round-trip encode and decode",
			func(original ontology.Resource) {
				w := orc.NewWriter(0)
				Expect(original.EncodeOrc(w)).To(Succeed())
				var decoded ontology.Resource
				r := orc.NewReader(nil)
				r.ResetBytes(w.Bytes())
				Expect(decoded.DecodeOrc(r)).To(Succeed())
				Expect(decoded).To(Equal(original))
			},
			Entry("fully populated", ontology.Resource{
				ID: ontology.ID{Type: ontology.ResourceType("arc"), Key: "test_3"},
			}),
			Entry("zero values", ontology.Resource{ID: ontology.ID{Type: ontology.ResourceType(""), Key: ""}}),
		)
	})
})

func BenchmarkEncodeDecodeID(b *testing.B) {
	id := ontology.ID{Type: ontology.ResourceType("arc"), Key: "test_2"}
	w := orc.NewWriter(0)
	r := orc.NewReader(nil)
	for i := 0; i < b.N; i++ {
		w.Reset()
		if err := id.EncodeOrc(w); err != nil {
			b.Fatal(err)
		}
		var decoded ontology.ID
		r.ResetBytes(w.Bytes())
		if err := decoded.DecodeOrc(r); err != nil {
			b.Fatal(err)
		}
	}
}

func BenchmarkEncodeDecodeRelationship(b *testing.B) {
	rv := ontology.Relationship{
		From: ontology.ID{Type: ontology.ResourceType("arc"), Key: "test_3"},
		Type: ontology.RelationshipType("test_4"),
		To:   ontology.ID{Type: ontology.ResourceType("arc"), Key: "test_7"},
	}
	w := orc.NewWriter(0)
	r := orc.NewReader(nil)
	for i := 0; i < b.N; i++ {
		w.Reset()
		if err := rv.EncodeOrc(w); err != nil {
			b.Fatal(err)
		}
		var decoded ontology.Relationship
		r.ResetBytes(w.Bytes())
		if err := decoded.DecodeOrc(r); err != nil {
			b.Fatal(err)
		}
	}
}

func BenchmarkEncodeDecodeResource(b *testing.B) {
	rv := ontology.Resource{
		ID: ontology.ID{Type: ontology.ResourceType("arc"), Key: "test_3"},
	}
	w := orc.NewWriter(0)
	r := orc.NewReader(nil)
	for i := 0; i < b.N; i++ {
		w.Reset()
		if err := rv.EncodeOrc(w); err != nil {
			b.Fatal(err)
		}
		var decoded ontology.Resource
		r.ResetBytes(w.Bytes())
		if err := decoded.DecodeOrc(r); err != nil {
			b.Fatal(err)
		}
	}
}

func FuzzDecodeID(f *testing.F) {
	{
		seed := ontology.ID{Type: ontology.ResourceType("arc"), Key: "test_2"}
		w := orc.NewWriter(0)
		if err := seed.EncodeOrc(w); err != nil {
			f.Fatal(err)
		}
		f.Add(w.Bytes())
	}
	{
		seed := ontology.ID{Type: ontology.ResourceType(""), Key: ""}
		w := orc.NewWriter(0)
		if err := seed.EncodeOrc(w); err != nil {
			f.Fatal(err)
		}
		f.Add(w.Bytes())
	}
	f.Fuzz(func(t *testing.T, data []byte) {
		var decoded ontology.ID
		r := orc.NewReader(nil)
		r.ResetBytes(data)
		if err := decoded.DecodeOrc(r); err != nil {
			return
		}
		w1 := orc.NewWriter(len(data))
		if err := decoded.EncodeOrc(w1); err != nil {
			t.Fatalf("encode after successful decode failed: %v", err)
		}
		var redecoded ontology.ID
		r.ResetBytes(w1.Bytes())
		if err := redecoded.DecodeOrc(r); err != nil {
			t.Fatalf("re-decode failed: %v", err)
		}
		w2 := orc.NewWriter(w1.Len())
		if err := redecoded.EncodeOrc(w2); err != nil {
			t.Fatalf("re-encode failed: %v", err)
		}
		if !bytes.Equal(w1.Bytes(), w2.Bytes()) {
			t.Fatal("round-trip mismatch: encoded bytes differ after decode-encode cycle")
		}
	})
}

func FuzzDecodeRelationship(f *testing.F) {
	{
		seed := ontology.Relationship{
			From: ontology.ID{Type: ontology.ResourceType("arc"), Key: "test_3"},
			Type: ontology.RelationshipType("test_4"),
			To:   ontology.ID{Type: ontology.ResourceType("arc"), Key: "test_7"},
		}
		w := orc.NewWriter(0)
		if err := seed.EncodeOrc(w); err != nil {
			f.Fatal(err)
		}
		f.Add(w.Bytes())
	}
	{
		seed := ontology.Relationship{
			From: ontology.ID{Type: ontology.ResourceType(""), Key: ""},
			Type: ontology.RelationshipType(""),
			To:   ontology.ID{Type: ontology.ResourceType(""), Key: ""},
		}
		w := orc.NewWriter(0)
		if err := seed.EncodeOrc(w); err != nil {
			f.Fatal(err)
		}
		f.Add(w.Bytes())
	}
	f.Fuzz(func(t *testing.T, data []byte) {
		var decoded ontology.Relationship
		r := orc.NewReader(nil)
		r.ResetBytes(data)
		if err := decoded.DecodeOrc(r); err != nil {
			return
		}
		w1 := orc.NewWriter(len(data))
		if err := decoded.EncodeOrc(w1); err != nil {
			t.Fatalf("encode after successful decode failed: %v", err)
		}
		var redecoded ontology.Relationship
		r.ResetBytes(w1.Bytes())
		if err := redecoded.DecodeOrc(r); err != nil {
			t.Fatalf("re-decode failed: %v", err)
		}
		w2 := orc.NewWriter(w1.Len())
		if err := redecoded.EncodeOrc(w2); err != nil {
			t.Fatalf("re-encode failed: %v", err)
		}
		if !bytes.Equal(w1.Bytes(), w2.Bytes()) {
			t.Fatal("round-trip mismatch: encoded bytes differ after decode-encode cycle")
		}
	})
}

func FuzzDecodeResource(f *testing.F) {
	{
		seed := ontology.Resource{
			ID: ontology.ID{Type: ontology.ResourceType("arc"), Key: "test_3"},
		}
		w := orc.NewWriter(0)
		if err := seed.EncodeOrc(w); err != nil {
			f.Fatal(err)
		}
		f.Add(w.Bytes())
	}
	{
		seed := ontology.Resource{ID: ontology.ID{Type: ontology.ResourceType(""), Key: ""}}
		w := orc.NewWriter(0)
		if err := seed.EncodeOrc(w); err != nil {
			f.Fatal(err)
		}
		f.Add(w.Bytes())
	}
	f.Fuzz(func(t *testing.T, data []byte) {
		var decoded ontology.Resource
		r := orc.NewReader(nil)
		r.ResetBytes(data)
		if err := decoded.DecodeOrc(r); err != nil {
			return
		}
		w1 := orc.NewWriter(len(data))
		if err := decoded.EncodeOrc(w1); err != nil {
			t.Fatalf("encode after successful decode failed: %v", err)
		}
		var redecoded ontology.Resource
		r.ResetBytes(w1.Bytes())
		if err := redecoded.DecodeOrc(r); err != nil {
			t.Fatalf("re-decode failed: %v", err)
		}
		w2 := orc.NewWriter(w1.Len())
		if err := redecoded.EncodeOrc(w2); err != nil {
			t.Fatalf("re-encode failed: %v", err)
		}
		if !bytes.Equal(w1.Bytes(), w2.Bytes()) {
			t.Fatal("round-trip mismatch: encoded bytes differ after decode-encode cycle")
		}
	})
}
