// Copyright 2026 Synnax Labs, Inc.
//
// Use of this software is governed by the Business Source License included in the file
// licenses/BSL.txt.
//
// As of the Change Date specified in that file, in accordance with the Business Source
// License, use of this software will be governed by the Apache License, Version 2.0,
// included in the file licenses/APL.txt.

// Package format provides language-aware formatters that produce canonical
// output for oracle's generated code. Plugins emit raw template output; the
// format layer turns that into the byte-identical state that would otherwise
// be produced by running gofmt / prettier / clang-format / etc. on the file
// after writing it to disk. That lets the sync step compare in-memory
// formatter output against the existing on-disk file and skip the write when
// they match.
package format

// Formatter produces canonical bytes for a single generated file.
//
// Implementations must be idempotent: Format(Format(x)) == Format(x). They
// must also be deterministic given the same content and path; the sync layer
// relies on byte-identical output across invocations to decide whether a
// write is needed.
type Formatter interface {
	// Format takes raw generated bytes and the absolute path the file would be
	// written to (used for tooling config discovery, e.g. .clang-format /
	// .prettierrc lookups), and returns the canonically-formatted bytes.
	Format(content []byte, absPath string) ([]byte, error)
}
