// Copyright 2026 Synnax Labs, Inc.
//
// Use of this software is governed by the Business Source License included in the file
// licenses/BSL.txt.
//
// As of the Change Date specified in that file, in accordance with the Business Source
// License, use of this software will be governed by the Apache License, Version 2.0,
// included in the file licenses/APL.txt.

// Code generated by oracle. DO NOT EDIT.

package v1

import (
	"context"

	"github.com/synnaxlabs/synnax/pkg/service/device/types/v0"
)

func autoMigrateDevice(_ context.Context, old v0.Device) (Device, error) {
	return Device{
		Key:        old.Key,
		Rack:       old.Rack,
		Location:   old.Location,
		Make:       old.Make,
		Model:      old.Model,
		Name:       old.Name,
		Configured: old.Configured,
		Properties: old.Properties,
	}, nil
}
