// Copyright 2025 Synnax Labs, Inc.
//
// Use of this software is governed by the Business Source License included in the file
// licenses/BSL.txt.
//
// As of the Change Date specified in that file, in accordance with the Business Source
// License, use of this software will be governed by the Apache License, Version 2.0,
// included in the file licenses/APL.txt.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: arc/go/types/types.proto

package types

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PBKind int32

const (
	PBKind_PB_KIND_UNSPECIFIED PBKind = 0
	PBKind_PB_KIND_U8          PBKind = 1
	PBKind_PB_KIND_U16         PBKind = 2
	PBKind_PB_KIND_U32         PBKind = 3
	PBKind_PB_KIND_U64         PBKind = 4
	PBKind_PB_KIND_I8          PBKind = 5
	PBKind_PB_KIND_I16         PBKind = 6
	PBKind_PB_KIND_I32         PBKind = 7
	PBKind_PB_KIND_I64         PBKind = 8
	PBKind_PB_KIND_F32         PBKind = 9
	PBKind_PB_KIND_F64         PBKind = 10
	PBKind_PB_KIND_STRING      PBKind = 11
	PBKind_PB_KIND_TIMESTAMP   PBKind = 12
	PBKind_PB_KIND_TIMESPAN    PBKind = 13
	PBKind_PB_KIND_CHAN        PBKind = 14
	PBKind_PB_KIND_SERIES      PBKind = 15
)

// Enum value maps for PBKind.
var (
	PBKind_name = map[int32]string{
		0:  "PB_KIND_UNSPECIFIED",
		1:  "PB_KIND_U8",
		2:  "PB_KIND_U16",
		3:  "PB_KIND_U32",
		4:  "PB_KIND_U64",
		5:  "PB_KIND_I8",
		6:  "PB_KIND_I16",
		7:  "PB_KIND_I32",
		8:  "PB_KIND_I64",
		9:  "PB_KIND_F32",
		10: "PB_KIND_F64",
		11: "PB_KIND_STRING",
		12: "PB_KIND_TIMESTAMP",
		13: "PB_KIND_TIMESPAN",
		14: "PB_KIND_CHAN",
		15: "PB_KIND_SERIES",
	}
	PBKind_value = map[string]int32{
		"PB_KIND_UNSPECIFIED": 0,
		"PB_KIND_U8":          1,
		"PB_KIND_U16":         2,
		"PB_KIND_U32":         3,
		"PB_KIND_U64":         4,
		"PB_KIND_I8":          5,
		"PB_KIND_I16":         6,
		"PB_KIND_I32":         7,
		"PB_KIND_I64":         8,
		"PB_KIND_F32":         9,
		"PB_KIND_F64":         10,
		"PB_KIND_STRING":      11,
		"PB_KIND_TIMESTAMP":   12,
		"PB_KIND_TIMESPAN":    13,
		"PB_KIND_CHAN":        14,
		"PB_KIND_SERIES":      15,
	}
)

func (x PBKind) Enum() *PBKind {
	p := new(PBKind)
	*p = x
	return p
}

func (x PBKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PBKind) Descriptor() protoreflect.EnumDescriptor {
	return file_arc_go_types_types_proto_enumTypes[0].Descriptor()
}

func (PBKind) Type() protoreflect.EnumType {
	return &file_arc_go_types_types_proto_enumTypes[0]
}

func (x PBKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PBKind.Descriptor instead.
func (PBKind) EnumDescriptor() ([]byte, []int) {
	return file_arc_go_types_types_proto_rawDescGZIP(), []int{0}
}

type PBType struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Kind          PBKind                 `protobuf:"varint,1,opt,name=kind,proto3,enum=x.arc.types.PBKind" json:"kind,omitempty"`
	Elem          *PBType                `protobuf:"bytes,2,opt,name=elem,proto3" json:"elem,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PBType) Reset() {
	*x = PBType{}
	mi := &file_arc_go_types_types_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PBType) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PBType) ProtoMessage() {}

func (x *PBType) ProtoReflect() protoreflect.Message {
	mi := &file_arc_go_types_types_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PBType.ProtoReflect.Descriptor instead.
func (*PBType) Descriptor() ([]byte, []int) {
	return file_arc_go_types_types_proto_rawDescGZIP(), []int{0}
}

func (x *PBType) GetKind() PBKind {
	if x != nil {
		return x.Kind
	}
	return PBKind_PB_KIND_UNSPECIFIED
}

func (x *PBType) GetElem() *PBType {
	if x != nil {
		return x.Elem
	}
	return nil
}

type PBParam struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Type          *PBType                `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Value         *structpb.Value        `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PBParam) Reset() {
	*x = PBParam{}
	mi := &file_arc_go_types_types_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PBParam) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PBParam) ProtoMessage() {}

func (x *PBParam) ProtoReflect() protoreflect.Message {
	mi := &file_arc_go_types_types_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PBParam.ProtoReflect.Descriptor instead.
func (*PBParam) Descriptor() ([]byte, []int) {
	return file_arc_go_types_types_proto_rawDescGZIP(), []int{1}
}

func (x *PBParam) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PBParam) GetType() *PBType {
	if x != nil {
		return x.Type
	}
	return nil
}

func (x *PBParam) GetValue() *structpb.Value {
	if x != nil {
		return x.Value
	}
	return nil
}

var File_arc_go_types_types_proto protoreflect.FileDescriptor

const file_arc_go_types_types_proto_rawDesc = "" +
	"\n" +
	"\x18arc/go/types/types.proto\x12\vx.arc.types\x1a\x1cgoogle/protobuf/struct.proto\"Z\n" +
	"\x06PBType\x12'\n" +
	"\x04kind\x18\x01 \x01(\x0e2\x13.x.arc.types.PBKindR\x04kind\x12'\n" +
	"\x04elem\x18\x02 \x01(\v2\x13.x.arc.types.PBTypeR\x04elem\"t\n" +
	"\aPBParam\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12'\n" +
	"\x04type\x18\x02 \x01(\v2\x13.x.arc.types.PBTypeR\x04type\x12,\n" +
	"\x05value\x18\x03 \x01(\v2\x16.google.protobuf.ValueR\x05value*\xb0\x02\n" +
	"\x06PBKind\x12\x17\n" +
	"\x13PB_KIND_UNSPECIFIED\x10\x00\x12\x0e\n" +
	"\n" +
	"PB_KIND_U8\x10\x01\x12\x0f\n" +
	"\vPB_KIND_U16\x10\x02\x12\x0f\n" +
	"\vPB_KIND_U32\x10\x03\x12\x0f\n" +
	"\vPB_KIND_U64\x10\x04\x12\x0e\n" +
	"\n" +
	"PB_KIND_I8\x10\x05\x12\x0f\n" +
	"\vPB_KIND_I16\x10\x06\x12\x0f\n" +
	"\vPB_KIND_I32\x10\a\x12\x0f\n" +
	"\vPB_KIND_I64\x10\b\x12\x0f\n" +
	"\vPB_KIND_F32\x10\t\x12\x0f\n" +
	"\vPB_KIND_F64\x10\n" +
	"\x12\x12\n" +
	"\x0ePB_KIND_STRING\x10\v\x12\x15\n" +
	"\x11PB_KIND_TIMESTAMP\x10\f\x12\x14\n" +
	"\x10PB_KIND_TIMESPAN\x10\r\x12\x10\n" +
	"\fPB_KIND_CHAN\x10\x0e\x12\x12\n" +
	"\x0ePB_KIND_SERIES\x10\x0fB\x8c\x01\n" +
	"\x0fcom.x.arc.typesB\n" +
	"TypesProtoP\x01Z\x1fgithub.com/synnaxlabs/arc/types\xa2\x02\x03XAT\xaa\x02\vX.Arc.Types\xca\x02\vX\\Arc\\Types\xe2\x02\x17X\\Arc\\Types\\GPBMetadata\xea\x02\rX::Arc::Typesb\x06proto3"

var (
	file_arc_go_types_types_proto_rawDescOnce sync.Once
	file_arc_go_types_types_proto_rawDescData []byte
)

func file_arc_go_types_types_proto_rawDescGZIP() []byte {
	file_arc_go_types_types_proto_rawDescOnce.Do(func() {
		file_arc_go_types_types_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_arc_go_types_types_proto_rawDesc), len(file_arc_go_types_types_proto_rawDesc)))
	})
	return file_arc_go_types_types_proto_rawDescData
}

var file_arc_go_types_types_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_arc_go_types_types_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_arc_go_types_types_proto_goTypes = []any{
	(PBKind)(0),            // 0: x.arc.types.PBKind
	(*PBType)(nil),         // 1: x.arc.types.PBType
	(*PBParam)(nil),        // 2: x.arc.types.PBParam
	(*structpb.Value)(nil), // 3: google.protobuf.Value
}
var file_arc_go_types_types_proto_depIdxs = []int32{
	0, // 0: x.arc.types.PBType.kind:type_name -> x.arc.types.PBKind
	1, // 1: x.arc.types.PBType.elem:type_name -> x.arc.types.PBType
	1, // 2: x.arc.types.PBParam.type:type_name -> x.arc.types.PBType
	3, // 3: x.arc.types.PBParam.value:type_name -> google.protobuf.Value
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_arc_go_types_types_proto_init() }
func file_arc_go_types_types_proto_init() {
	if File_arc_go_types_types_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_arc_go_types_types_proto_rawDesc), len(file_arc_go_types_types_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_arc_go_types_types_proto_goTypes,
		DependencyIndexes: file_arc_go_types_types_proto_depIdxs,
		EnumInfos:         file_arc_go_types_types_proto_enumTypes,
		MessageInfos:      file_arc_go_types_types_proto_msgTypes,
	}.Build()
	File_arc_go_types_types_proto = out.File
	file_arc_go_types_types_proto_goTypes = nil
	file_arc_go_types_types_proto_depIdxs = nil
}
