[tool.poetry]
name = "modbus-dev"
version = "0.1.0"
description = "Development tools for Modbus driver testing"
authors = ["Synnax Labs <support@synnaxlabs.com>"]
package-mode = false

[tool.poetry.dependencies]
python = "^3.11"
pymodbus = "^3.7.4"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
