// Copyright 2026 Synnax Labs, Inc.
//
// Use of this software is governed by the Business Source License included in the file
// licenses/BSL.txt.
//
// As of the Change Date specified in that file, in accordance with the Business Source
// License, use of this software will be governed by the Apache License, Version 2.0,
// included in the file licenses/APL.txt.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: core/pkg/api/grpc/arc/arc.proto

package arc

import (
	pb "github.com/synnaxlabs/synnax/pkg/service/arc/pb"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Arcs          []*pb.Arc              `protobuf:"bytes,1,rep,name=arcs,proto3" json:"arcs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRequest) Reset() {
	*x = CreateRequest{}
	mi := &file_core_pkg_api_grpc_arc_arc_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRequest) ProtoMessage() {}

func (x *CreateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_core_pkg_api_grpc_arc_arc_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRequest.ProtoReflect.Descriptor instead.
func (*CreateRequest) Descriptor() ([]byte, []int) {
	return file_core_pkg_api_grpc_arc_arc_proto_rawDescGZIP(), []int{0}
}

func (x *CreateRequest) GetArcs() []*pb.Arc {
	if x != nil {
		return x.Arcs
	}
	return nil
}

type CreateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Arcs          []*pb.Arc              `protobuf:"bytes,1,rep,name=arcs,proto3" json:"arcs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateResponse) Reset() {
	*x = CreateResponse{}
	mi := &file_core_pkg_api_grpc_arc_arc_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateResponse) ProtoMessage() {}

func (x *CreateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_core_pkg_api_grpc_arc_arc_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateResponse.ProtoReflect.Descriptor instead.
func (*CreateResponse) Descriptor() ([]byte, []int) {
	return file_core_pkg_api_grpc_arc_arc_proto_rawDescGZIP(), []int{1}
}

func (x *CreateResponse) GetArcs() []*pb.Arc {
	if x != nil {
		return x.Arcs
	}
	return nil
}

type RetrieveRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Keys          []string               `protobuf:"bytes,1,rep,name=keys,proto3" json:"keys,omitempty"`
	Names         []string               `protobuf:"bytes,2,rep,name=names,proto3" json:"names,omitempty"`
	SearchTerm    string                 `protobuf:"bytes,3,opt,name=search_term,json=searchTerm,proto3" json:"search_term,omitempty"`
	Limit         int32                  `protobuf:"varint,4,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32                  `protobuf:"varint,5,opt,name=offset,proto3" json:"offset,omitempty"`
	IncludeStatus bool                   `protobuf:"varint,6,opt,name=include_status,json=includeStatus,proto3" json:"include_status,omitempty"`
	Compile       bool                   `protobuf:"varint,7,opt,name=compile,proto3" json:"compile,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RetrieveRequest) Reset() {
	*x = RetrieveRequest{}
	mi := &file_core_pkg_api_grpc_arc_arc_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RetrieveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RetrieveRequest) ProtoMessage() {}

func (x *RetrieveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_core_pkg_api_grpc_arc_arc_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RetrieveRequest.ProtoReflect.Descriptor instead.
func (*RetrieveRequest) Descriptor() ([]byte, []int) {
	return file_core_pkg_api_grpc_arc_arc_proto_rawDescGZIP(), []int{2}
}

func (x *RetrieveRequest) GetKeys() []string {
	if x != nil {
		return x.Keys
	}
	return nil
}

func (x *RetrieveRequest) GetNames() []string {
	if x != nil {
		return x.Names
	}
	return nil
}

func (x *RetrieveRequest) GetSearchTerm() string {
	if x != nil {
		return x.SearchTerm
	}
	return ""
}

func (x *RetrieveRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *RetrieveRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *RetrieveRequest) GetIncludeStatus() bool {
	if x != nil {
		return x.IncludeStatus
	}
	return false
}

func (x *RetrieveRequest) GetCompile() bool {
	if x != nil {
		return x.Compile
	}
	return false
}

type RetrieveResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Arcs          []*pb.Arc              `protobuf:"bytes,1,rep,name=arcs,proto3" json:"arcs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RetrieveResponse) Reset() {
	*x = RetrieveResponse{}
	mi := &file_core_pkg_api_grpc_arc_arc_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RetrieveResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RetrieveResponse) ProtoMessage() {}

func (x *RetrieveResponse) ProtoReflect() protoreflect.Message {
	mi := &file_core_pkg_api_grpc_arc_arc_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RetrieveResponse.ProtoReflect.Descriptor instead.
func (*RetrieveResponse) Descriptor() ([]byte, []int) {
	return file_core_pkg_api_grpc_arc_arc_proto_rawDescGZIP(), []int{3}
}

func (x *RetrieveResponse) GetArcs() []*pb.Arc {
	if x != nil {
		return x.Arcs
	}
	return nil
}

type DeleteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Keys          []string               `protobuf:"bytes,1,rep,name=keys,proto3" json:"keys,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteRequest) Reset() {
	*x = DeleteRequest{}
	mi := &file_core_pkg_api_grpc_arc_arc_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRequest) ProtoMessage() {}

func (x *DeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_core_pkg_api_grpc_arc_arc_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRequest.ProtoReflect.Descriptor instead.
func (*DeleteRequest) Descriptor() ([]byte, []int) {
	return file_core_pkg_api_grpc_arc_arc_proto_rawDescGZIP(), []int{4}
}

func (x *DeleteRequest) GetKeys() []string {
	if x != nil {
		return x.Keys
	}
	return nil
}

var File_core_pkg_api_grpc_arc_arc_proto protoreflect.FileDescriptor

const file_core_pkg_api_grpc_arc_arc_proto_rawDesc = "" +
	"\n" +
	"\x1fcore/pkg/api/grpc/arc/arc.proto\x12\bgrpc.arc\x1a!core/pkg/service/arc/pb/arc.proto\x1a\x1bgoogle/protobuf/empty.proto\"8\n" +
	"\rCreateRequest\x12'\n" +
	"\x04arcs\x18\x01 \x03(\v2\x13.service.arc.pb.ArcR\x04arcs\"9\n" +
	"\x0eCreateResponse\x12'\n" +
	"\x04arcs\x18\x01 \x03(\v2\x13.service.arc.pb.ArcR\x04arcs\"\xcb\x01\n" +
	"\x0fRetrieveRequest\x12\x12\n" +
	"\x04keys\x18\x01 \x03(\tR\x04keys\x12\x14\n" +
	"\x05names\x18\x02 \x03(\tR\x05names\x12\x1f\n" +
	"\vsearch_term\x18\x03 \x01(\tR\n" +
	"searchTerm\x12\x14\n" +
	"\x05limit\x18\x04 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x05 \x01(\x05R\x06offset\x12%\n" +
	"\x0einclude_status\x18\x06 \x01(\bR\rincludeStatus\x12\x18\n" +
	"\acompile\x18\a \x01(\bR\acompile\";\n" +
	"\x10RetrieveResponse\x12'\n" +
	"\x04arcs\x18\x01 \x03(\v2\x13.service.arc.pb.ArcR\x04arcs\"#\n" +
	"\rDeleteRequest\x12\x12\n" +
	"\x04keys\x18\x01 \x03(\tR\x04keys2O\n" +
	"\x10ArcCreateService\x12;\n" +
	"\x04Exec\x12\x17.grpc.arc.CreateRequest\x1a\x18.grpc.arc.CreateResponse\"\x002U\n" +
	"\x12ArcRetrieveService\x12?\n" +
	"\x04Exec\x12\x19.grpc.arc.RetrieveRequest\x1a\x1a.grpc.arc.RetrieveResponse\"\x002M\n" +
	"\x10ArcDeleteService\x129\n" +
	"\x04Exec\x12\x17.grpc.arc.DeleteRequest\x1a\x16.google.protobuf.Empty\"\x00B\x88\x01\n" +
	"\fcom.grpc.arcB\bArcProtoP\x01Z-github.com/synnaxlabs/synnax/pkg/api/grpc/arc\xa2\x02\x03GAX\xaa\x02\bGrpc.Arc\xca\x02\bGrpc\\Arc\xe2\x02\x14Grpc\\Arc\\GPBMetadata\xea\x02\tGrpc::Arcb\x06proto3"

var (
	file_core_pkg_api_grpc_arc_arc_proto_rawDescOnce sync.Once
	file_core_pkg_api_grpc_arc_arc_proto_rawDescData []byte
)

func file_core_pkg_api_grpc_arc_arc_proto_rawDescGZIP() []byte {
	file_core_pkg_api_grpc_arc_arc_proto_rawDescOnce.Do(func() {
		file_core_pkg_api_grpc_arc_arc_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_core_pkg_api_grpc_arc_arc_proto_rawDesc), len(file_core_pkg_api_grpc_arc_arc_proto_rawDesc)))
	})
	return file_core_pkg_api_grpc_arc_arc_proto_rawDescData
}

var file_core_pkg_api_grpc_arc_arc_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_core_pkg_api_grpc_arc_arc_proto_goTypes = []any{
	(*CreateRequest)(nil),    // 0: grpc.arc.CreateRequest
	(*CreateResponse)(nil),   // 1: grpc.arc.CreateResponse
	(*RetrieveRequest)(nil),  // 2: grpc.arc.RetrieveRequest
	(*RetrieveResponse)(nil), // 3: grpc.arc.RetrieveResponse
	(*DeleteRequest)(nil),    // 4: grpc.arc.DeleteRequest
	(*pb.Arc)(nil),           // 5: service.arc.pb.Arc
	(*emptypb.Empty)(nil),    // 6: google.protobuf.Empty
}
var file_core_pkg_api_grpc_arc_arc_proto_depIdxs = []int32{
	5, // 0: grpc.arc.CreateRequest.arcs:type_name -> service.arc.pb.Arc
	5, // 1: grpc.arc.CreateResponse.arcs:type_name -> service.arc.pb.Arc
	5, // 2: grpc.arc.RetrieveResponse.arcs:type_name -> service.arc.pb.Arc
	0, // 3: grpc.arc.ArcCreateService.Exec:input_type -> grpc.arc.CreateRequest
	2, // 4: grpc.arc.ArcRetrieveService.Exec:input_type -> grpc.arc.RetrieveRequest
	4, // 5: grpc.arc.ArcDeleteService.Exec:input_type -> grpc.arc.DeleteRequest
	1, // 6: grpc.arc.ArcCreateService.Exec:output_type -> grpc.arc.CreateResponse
	3, // 7: grpc.arc.ArcRetrieveService.Exec:output_type -> grpc.arc.RetrieveResponse
	6, // 8: grpc.arc.ArcDeleteService.Exec:output_type -> google.protobuf.Empty
	6, // [6:9] is the sub-list for method output_type
	3, // [3:6] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_core_pkg_api_grpc_arc_arc_proto_init() }
func file_core_pkg_api_grpc_arc_arc_proto_init() {
	if File_core_pkg_api_grpc_arc_arc_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_core_pkg_api_grpc_arc_arc_proto_rawDesc), len(file_core_pkg_api_grpc_arc_arc_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   3,
		},
		GoTypes:           file_core_pkg_api_grpc_arc_arc_proto_goTypes,
		DependencyIndexes: file_core_pkg_api_grpc_arc_arc_proto_depIdxs,
		MessageInfos:      file_core_pkg_api_grpc_arc_arc_proto_msgTypes,
	}.Build()
	File_core_pkg_api_grpc_arc_arc_proto = out.File
	file_core_pkg_api_grpc_arc_arc_proto_goTypes = nil
	file_core_pkg_api_grpc_arc_arc_proto_depIdxs = nil
}
