// Copyright 2026 Synnax Labs, Inc.
//
// Use of this software is governed by the Business Source License included in the file
// licenses/BSL.txt.
//
// As of the Change Date specified in that file, in accordance with the Business Source
// License, use of this software will be governed by the Apache License, Version 2.0,
// included in the file licenses/APL.txt.

// Code generated by oracle. DO NOT EDIT.

package status

import (
	xbinary "github.com/synnaxlabs/x/binary"
	"github.com/synnaxlabs/x/label"
	"github.com/synnaxlabs/x/telem"
)

func EncodeStatus[Details any](w *xbinary.Writer, s *Status[Details], encodeDetails func(*xbinary.Writer, *Details) error) error {
	w.String(s.Key)
	w.String(s.Name)
	w.String(string(s.Variant))
	w.String(s.Message)
	w.String(s.Description)
	w.Int64(int64(s.Time))
	if s.Labels != nil {
		w.Bool(true)
		w.Uint32(uint32(len(s.Labels)))
		for j := range s.Labels {
			if err := label.EncodeLabel(w, &s.Labels[j]); err != nil {
				return err
			}
		}
	} else {
		w.Bool(false)
	}
	return nil
}

func DecodeStatus[Details any](r *xbinary.Reader, s *Status[Details], decodeDetails func(*xbinary.Reader, *Details) error) error {
	var err error
	if s.Key, err = r.String(); err != nil {
		return err
	}
	if s.Name, err = r.String(); err != nil {
		return err
	}
	{
		v, err := r.String()
		if err != nil {
			return err
		}
		s.Variant = Variant(v)
	}
	if s.Message, err = r.String(); err != nil {
		return err
	}
	if s.Description, err = r.String(); err != nil {
		return err
	}
	{
		v, err := r.Int64()
		if err != nil {
			return err
		}
		s.Time = telem.TimeStamp(v)
	}
	{
		present, err := r.Bool()
		if err != nil {
			return err
		}
		if present {
			{
				n, err := r.Uint32()
				if err != nil {
					return err
				}
				s.Labels = make([]label.Label, n)
				for j := range s.Labels {
					if err = label.DecodeLabel(r, &s.Labels[j]); err != nil {
						return err
					}
				}
			}
		}
	}
	return nil
}
