// Copyright 2026 Synnax Labs, Inc.
//
// Use of this software is governed by the Business Source License included in the file
// licenses/BSL.txt.
//
// As of the Change Date specified in that file, in accordance with the Business Source
// License, use of this software will be governed by the Apache License, Version 2.0,
// included in the file licenses/APL.txt.

// Code generated by oracle. DO NOT EDIT.

package common

import "github.com/synnaxlabs/synnax/pkg/service/task/common/versions"

// KeyedConfig is the base for every stored task configuration record.
type KeyedConfig = versions.KeyedConfig

// BaseStartConfig carries the configuration fields shared by every task.
type BaseStartConfig = versions.BaseStartConfig

// BasePersistConfig carries the configuration fields shared by tasks that write
// telemetry.
type BasePersistConfig = versions.BasePersistConfig

// BaseReadConfig carries the configuration fields shared by hardware acquisition tasks.
type BaseReadConfig = versions.BaseReadConfig

// BaseWriteConfig carries the configuration fields shared by hardware control tasks.
type BaseWriteConfig = versions.BaseWriteConfig

// BaseScanConfig carries the fields shared by every scan task configuration.
type BaseScanConfig = versions.BaseScanConfig
