# Copyright 2026 Synnax Labs, Inc.
#
# Use of this software is governed by the Business Source License included in the file
# licenses/BSL.txt.
#
# As of the Change Date specified in that file, in accordance with the Business Source
# License, use of this software will be governed by the Apache License, Version 2.0,
# included in the file licenses/APL.txt.

name: Label - Pull Request

on:
  pull_request_target:

permissions:
  contents: read
  pull-requests: write

jobs:
  label:
    name: Label
    runs-on: ubuntu-latest
    steps:
      - name: Label From Changed Paths
        uses: actions/labeler@v7
