# Copyright 2026 Synnax Labs, Inc.
#
# Use of this software is governed by the Business Source License included in the file
# licenses/BSL.txt.
#
# As of the Change Date specified in that file, in accordance with the Business Source
# License, use of this software will be governed by the Apache License, Version 2.0,
# included in the file licenses/APL.txt.

name: Test - Freighter (C++)

on:
  workflow_call:
    inputs:
      os:
        description: JSON list of runner labels to test on
        required: false
        type: string
        default: '["ubuntu-build-bot"]'
  workflow_dispatch:
    inputs:
      os:
        description: JSON list of runner labels to test on
        required: false
        type: string
        default: '["ubuntu-build-bot"]'
env:
  BAZEL_REMOTE_CACHE_FLAGS:
    --remote_cache=${{ vars.BAZEL_REMOTE_CACHE_GRPC_URL }}
    --remote_cache_compression=true

jobs:
  test:
    name: Test (${{ matrix.os }})
    strategy:
      fail-fast: false
      matrix:
        os: ${{ fromJSON(inputs.os) }}
        include:
          - os: ubuntu-build-bot
            format: true
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Setup Bazel
        uses: bazel-contrib/setup-bazel@0.19.0
        with:
          bazelisk-cache: false
          disk-cache: false
          repository-cache: false

      - name: Install clang-format
        if: matrix.format
        run: scripts/install_clang_format.sh

      - name: Check formatting
        if: matrix.format
        run: scripts/check_clang_format.sh freighter/cpp

      - name: Test (macOS)
        if: matrix.os == 'macos-build-bot'
        run:
          bazel test --config=asan --test_output=all //freighter/cpp/...
          --test_tag_filters=-no-asan
        shell: bash

      - name: Test (Ubuntu)
        if: matrix.os == 'ubuntu-build-bot'
        run:
          bazel test $BAZEL_REMOTE_CACHE_FLAGS --config=asan-leak --test_output=all
          //freighter/cpp/...
        shell: bash

      - name: Test (Windows)
        if: matrix.os == 'windows-build-bot'
        run: |
          export MSYS_NO_PATHCONV=1
          scripts/run_bazel.sh test $BAZEL_REMOTE_CACHE_FLAGS --test_output=all \
            //freighter/cpp/...
        shell: bash

      - name: Clean build caches (Ubuntu)
        if: always() && matrix.os == 'ubuntu-build-bot'
        run: integration/scripts/clean_build_caches.sh 25

      - name: Clean build caches (Windows)
        if: always() && matrix.os == 'windows-build-bot'
        shell: powershell
        run: integration/scripts/CleanBuildCaches.ps1 -MinFreeGB 30
