# Copyright 2026 Synnax Labs, Inc.
#
# Use of this software is governed by the Business Source License included in the file
# licenses/BSL.txt.
#
# As of the Change Date specified in that file, in accordance with the Business Source
# License, use of this software will be governed by the Apache License, Version 2.0,
# included in the file licenses/APL.txt.

name: Test - SOEM

on:
  workflow_call:
jobs:
  test:
    name: Test (macOS)
    runs-on: macos-build-bot
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Update submodules
        run: git submodule update --init --recursive

      - name: Setup Bazel
        uses: bazel-contrib/setup-bazel@0.19.0
        with:
          bazelisk-cache: false
          disk-cache: false
          repository-cache: false

      - name: Test
        run: bazel test --test_output=all //vendor/soem:all
