# Copyright 2026 Synnax Labs, Inc.
#
# Use of this software is governed by the Business Source License included in the file
# licenses/BSL.txt.
#
# As of the Change Date specified in that file, in accordance with the Business Source
# License, use of this software will be governed by the Apache License, Version 2.0,
# included in the file licenses/APL.txt.

name: Test - Pluto

on:
  workflow_call:
    inputs:
      image:
        description: Core Docker image tag to test against
        required: true
        type: string
  workflow_dispatch:
    inputs:
      image:
        description: Core Docker image tag to test against
        required: true
        type: string
jobs:
  test:
    runs-on: ubuntu-latest
    env:
      TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
      TURBO_TEAM: ${{ vars.TURBO_TEAM }}
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
    services:
      synnax:
        image: ${{ inputs.image }}
        env:
          SYNNAX_VERBOSE: true
          SYNNAX_INSECURE: true
          SYNNAX_MEM: true
          SYNNAX_LICENSE_KEY: ${{ secrets.SYNNAX_LICENSE_KEY }}
        credentials:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
        ports:
          - 9090:9090
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Test TypeScript
        uses: ./.github/actions/test-typescript
        with:
          package: pluto
          coverage_flag: pluto
          directory: pluto
          test_args: -- --no-file-parallelism
