name: Test - Console

on:
  pull_request:
    paths:
      - .github/actions/test-typescript/**
      - .github/workflows/test.console.yaml
      - alamos/go/**
      - alamos/ts/**
      - arc/ts/**
      - aspen/**
      - cesium/**
      - client/ts/**
      - codecov.yaml
      - configs/eslint/**
      - configs/ts/**
      - configs/vite/**
      - console/**
      - core/**
      - drift/**
      - freighter/go/**
      - freighter/ts/**
      - package.json
      - pluto/**
      - pnpm-lock.yaml
      - pnpm-workspace.yaml
      - turbo.json
      - x/go/**
      - x/media/**
      - x/ts/**
  push:
    branches:
      - main
      - rc
    paths:
      - .github/actions/test-typescript/**
      - .github/workflows/test.console.yaml
      - alamos/go/**
      - alamos/ts/**
      - arc/ts/**
      - aspen/**
      - cesium/**
      - client/ts/**
      - codecov.yaml
      - configs/eslint/**
      - configs/ts/**
      - configs/vite/**
      - console/**
      - core/**
      - drift/**
      - freighter/go/**
      - freighter/ts/**
      - package.json
      - pluto/**
      - pnpm-lock.yaml
      - pnpm-workspace.yaml
      - turbo.json
      - x/go/**
      - x/media/**
      - x/ts/**
  workflow_dispatch:

jobs:
  server:
    uses: ./.github/workflows/build.docker.yaml
    permissions:
      packages: write
    with:
      module: core
      tag: ghcr.io/synnaxlabs/synnax:${{ github.sha }}

  test:
    runs-on: ubuntu-latest
    needs: server
    env:
      NODE_OPTIONS: "--max_old_space_size=4096"
      TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
      TURBO_TEAM: ${{ vars.TURBO_TEAM }}
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
    services:
      synnax:
        image: ghcr.io/synnaxlabs/synnax:${{ github.sha }}
        env:
          SYNNAX_VERBOSE: true
          SYNNAX_INSECURE: true
          SYNNAX_MEM: true
          SYNNAX_LICENSE_KEY: ${{ secrets.SYNNAX_LICENSE_KEY }}
        credentials:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
        ports:
          - 9090:9090
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Test TypeScript
        uses: ./.github/actions/test-typescript
        with:
          package: console
          coverage_flag: console
          directory: console
          lint: true
          test_args: -- --no-file-parallelism
