# Copyright 2026 Synnax Labs, Inc.
#
# Use of this software is governed by the Business Source License included in the file
# licenses/BSL.txt.
#
# As of the Change Date specified in that file, in accordance with the Business Source
# License, use of this software will be governed by the Apache License, Version 2.0,
# included in the file licenses/APL.txt.

name: Test - Protobuf

on:
  pull_request:
    paths:
      - "**/*.proto"
      - .github/workflows/test.protobuf.yaml
      - buf.yaml
      - buf.gen.yaml
  push:
    branches:
      - main
      - rc
    paths:
      - "**/*.proto"
      - .github/workflows/test.protobuf.yaml
      - buf.yaml
      - buf.gen.yaml
  workflow_dispatch:

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v7

      - name: Buf CI
        uses: bufbuild/buf-action@v1
        with:
          breaking: false
          pr_comment: false
