# Copyright 2026 Synnax Labs, Inc.
#
# Use of this software is governed by the Business Source License included in the file
# licenses/BSL.txt.
#
# As of the Change Date specified in that file, in accordance with the Business Source
# License, use of this software will be governed by the Apache License, Version 2.0,
# included in the file licenses/APL.txt.

name: Test - Arc (Go)

on:
  pull_request:
    paths:
      - .github/workflows/test.arc.go.yaml
      - .github/workflows/test.go.yaml
      - .golangci.yaml
      - alamos/go/**
      - arc/go/**
      - codecov.yaml
      - freighter/go/**
      - scripts/check_go_generate.sh
      - scripts/install_antlr4.sh
      - x/go/**
  push:
    branches:
      - main
      - rc
    paths:
      - .github/workflows/test.arc.go.yaml
      - .github/workflows/test.go.yaml
      - .golangci.yaml
      - alamos/go/**
      - arc/go/**
      - codecov.yaml
      - freighter/go/**
      - scripts/check_go_generate.sh
      - scripts/install_antlr4.sh
      - x/go/**
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    uses: ./.github/workflows/test.go.yaml
    secrets: inherit
    with:
      directory: arc/go
      coverage_flag: arc-go
      install_antlr4: true
