# Copyright 2026 Synnax Labs, Inc.
#
# Use of this software is governed by the Business Source License included in the file
# licenses/BSL.txt.
#
# As of the Change Date specified in that file, in accordance with the Business Source
# License, use of this software will be governed by the Apache License, Version 2.0,
# included in the file licenses/APL.txt.

name: Test - Freighter (TypeScript)

on:
  workflow_call:
    inputs:
      image:
        description: Freighter integration server image tag to test against
        required: true
        type: string
  workflow_dispatch:
    inputs:
      image:
        description: Freighter integration server image tag to test against
        required: true
        type: string

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    env:
      TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
      TURBO_TEAM: ${{ vars.TURBO_TEAM }}
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
    services:
      integration:
        image: ${{ inputs.image }}
        credentials:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
        ports:
          - 8080:8080
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Test TypeScript
        uses: ./.github/actions/test-typescript
        with:
          package: freighter
          coverage_flag: freighter-ts
          directory: freighter/ts
