# Copyright 2026 Synnax Labs, Inc.
#
# Use of this software is governed by the Business Source License included in the file
# licenses/BSL.txt.
#
# As of the Change Date specified in that file, in accordance with the Business Source
# License, use of this software will be governed by the Apache License, Version 2.0,
# included in the file licenses/APL.txt.

name: Test - X (TypeScript)

on:
  workflow_call:
    inputs: &inputs
      macos:
        description: Whether to test on macOS
        required: false
        type: boolean
        default: false
      ubuntu:
        description: Whether to test on Ubuntu
        required: false
        type: boolean
        default: true
      windows:
        description: Whether to test on Windows
        required: false
        type: boolean
        default: false
  workflow_dispatch:
    inputs: *inputs
jobs:
  test:
    name: Test (${{ matrix.os }})
    env:
      TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
      TURBO_TEAM: ${{ vars.TURBO_TEAM }}
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
        exclude:
          - os: ${{ !inputs.macos && 'macos-latest' }}
          - os: ${{ !inputs.ubuntu && 'ubuntu-latest' }}
          - os: ${{ !inputs.windows && 'windows-latest' }}
        include:
          - os: ubuntu-latest
            lint: true
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Test TypeScript
        uses: ./.github/actions/test-typescript
        with:
          package: x
          coverage_flag: x-ts
          directory: x/ts
          lint: ${{ matrix.lint }}
          knip: ${{ matrix.lint }}
