# Copyright 2026 Synnax Labs, Inc.
#
# Use of this software is governed by the Business Source License included in the file
# licenses/BSL.txt.
#
# As of the Change Date specified in that file, in accordance with the Business Source
# License, use of this software will be governed by the Apache License, Version 2.0,
# included in the file licenses/APL.txt.

name: Check Versions

on:
  pull_request:
  push:
    branches:
      - main
      - rc
  workflow_dispatch:

jobs:
  check-versions:
    name: Check Versions
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v7

      - name: Check Versions
        run: scripts/check_versions.sh
