# Copyright 2026 Synnax Labs, Inc.
#
# Use of this software is governed by the Business Source License included in the file
# licenses/BSL.txt.
#
# As of the Change Date specified in that file, in accordance with the Business Source
# License, use of this software will be governed by the Apache License, Version 2.0,
# included in the file licenses/APL.txt.

name: Test - Scripts

on:
  pull_request:
    paths:
      - .github/workflows/test.scripts.yaml
      - scripts/**
  push:
    branches:
      - main
      - rc
    paths:
      - .github/workflows/test.scripts.yaml
      - scripts/**
  workflow_dispatch:

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v7

      - name: Install uv
        uses: astral-sh/setup-uv@v9.0.0

      - name: Run Tests
        run: uvx pytest scripts
