name: Test - Server

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
      - rc
    paths:
      - .github/workflows/test.server.yaml
      - alamos/go/**
      - aspen/**
      - cesium/**
      - freighter/go/**
      - synnax/**
      - x/go/**
  workflow_dispatch:

jobs:
  test:
    name: Test (${{ matrix.os }})
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            format: true
          - os: ${{ (github.ref == 'refs/heads/main' || github.base_ref == 'main') && 'macos-latest' }}
          - os: ${{ (github.ref == 'refs/heads/main' || github.base_ref == 'main') && 'windows-latest' }}
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.work
          cache-dependency-path: go.work.sum

      - name: Check Formatting
        if: matrix.format
        run: scripts/gofmt-check.sh synnax

      - name: Build
        run: go build -v ./...
        working-directory: synnax

      - name: Test
        run: go test -v -shuffle=on ./...
        working-directory: synnax
